force-app/main/default/objects/Campaign/fields/Family_Member_Attendance__c.field-meta.xml
<CustomField>
    <fullName>Family_Member_Attendance__c</fullName>
    <label>Family Member Attendance</label>
    <summarizedField>Family_Attendance__c.Attended_Members__c</summarizedField>
    <summaryForeignKey>Family_Attendance__c.Event__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Campaign/fields/Volunteer_Attendance__c.field-meta.xml
<CustomField>
    <fullName>Volunteer_Attendance__c</fullName>
    <label>Volunteer Attendance</label>
    <summaryFilterItems>
        <field>Volunteer_Attendance__c.Attendance__c</field>
        <operation>equals</operation>
        <value>Attended</value>
    </summaryFilterItems>
    <summaryForeignKey>Volunteer_Attendance__c.Event__c</summaryForeignKey>
    <summaryOperation>count</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Age__c.field-meta.xml
<CustomField>
    <fullName>Age__c</fullName>
    <formula>IF( NOT (ISBLANK(  Deceased_Date__c )), YEAR(Deceased_Date__c) - YEAR(Birthdate),

IF( NOT( ISBLANK( Birthdate ) ) ,
IF( DATE( 2000 , MONTH( Birthdate ) , DAY( Birthdate ) ) &lt;= DATE( 2000 , MONTH( TODAY() ) , DAY( TODAY() ) ),
YEAR (Today()) - YEAR ( Birthdate ),
YEAR (Today()) - YEAR ( Birthdate ) -1 ),
NULL))</formula>
    <label>Age</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Family_Member_Type__c.field-meta.xml
<CustomField>
    <fullName>Family_Member_Type__c</fullName>
    <label>Family Member Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Aunt</fullName>
            </value>
            <value>
                <fullName>Deceased Parent</fullName>
            </value>
            <value>
                <fullName>Father</fullName>
            </value>
            <value>
                <fullName>Grandparent</fullName>
            </value>
            <value>
                <fullName>Hospital</fullName>
            </value>
            <value>
                <fullName>Legal Guardian</fullName>
            </value>
            <value>
                <fullName>Mother</fullName>
            </value>
            <value>
                <fullName>Patient</fullName>
            </value>
            <value>
                <fullName>School</fullName>
            </value>
            <value>
                <fullName>Sibling</fullName>
            </value>
            <value>
                <fullName>Stepfather</fullName>
            </value>
            <value>
                <fullName>Stepmother</fullName>
            </value>
            <value>
                <fullName>Stepsibling</fullName>
            </value>
            <value>
                <fullName>Uncle</fullName>
            </value>
            <value>
                <fullName>Cousin</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/Volunteer_Attendance__c.field-meta.xml
<CustomField>
    <fullName>Volunteer_Attendance__c</fullName>
    <label>Last Volunteer Attendance</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Family_Member_Attendance__c/Family_Member_Attendance__c.object-meta.xml
<CustomObject>
    <description>Used for recording individual family member attendances on programs linked to family attendance</description>
    <label>Family Member Attendance</label>
    <nameField>
        <displayFormat>FMA{00000}</displayFormat>
        <label>Family Member Attendance</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Family Member Attendance</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Family_Member_Attendance__c/fields/Age__c.field-meta.xml
<CustomField>
    <fullName>Age__c</fullName>
    <formula>TEXT(Contact__r.Age__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Age</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Family_Member_Attendance__c/fields/Attendance__c.field-meta.xml
<CustomField>
    <fullName>Attendance__c</fullName>
    <label>Attendance</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Invited</fullName>
            </value>
            <value>
                <fullName>Request to Attend</fullName>
            </value>
            <value>
                <fullName>Accepted</fullName>
            </value>
            <value>
                <fullName>Attended</fullName>
            </value>
            <value>
                <fullName>Declined</fullName>
            </value>
            <value>
                <fullName>Unsuccessful</fullName>
            </value>
            <value>
                <fullName>No Show</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Cancelled &lt; 24 hours</fullName>
            </value>
            <value>
                <fullName>Medical Withdrawal</fullName>
            </value>
            <value>
                <fullName>Unsuccessful – Waitlist</fullName>
            </value>
            <value>
                <fullName>Unsuccessful – Declined</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Family_Member_Attendance__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Family Member Attendance</relationshipLabel>
    <relationshipName>Family_Member_Attendance</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Family_Member_Attendance__c/fields/Event__c.field-meta.xml
<CustomField>
    <fullName>Event__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Event</label>
    <referenceTo>Campaign</referenceTo>
    <relationshipLabel>Family Member Attendance</relationshipLabel>
    <relationshipName>Family_Member_Attendance</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Family_Member_Attendance__c/fields/Family_Member_Type__c.field-meta.xml
<CustomField>
    <fullName>Family_Member_Type__c</fullName>
    <formula>TEXT(Contact__r.Family_Member_Type__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Family Member Type</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Special_Needs__c/Special_Needs__c.object-meta.xml
<CustomObject>
    <label>Dietary &amp; Special Needs</label>
    <nameField>
        <displayFormat>SN - {0000}</displayFormat>
        <label>Special Needs Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Dietary &amp; Special Needs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Special_Needs__c/fields/Comments__c.field-meta.xml
<CustomField>
    <fullName>Comments__c</fullName>
    <label>Comments</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Special_Needs__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipName>Special_Needs</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Special_Needs__c/fields/Legacy_Comments_To_Be_Purged_June_2017__c.field-meta.xml
<CustomField>
    <fullName>Legacy_Comments_To_Be_Purged_June_2017__c</fullName>
    <label>Legacy Comments To Be Purged June 2017</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Special_Needs__c/fields/Long_Description__c.field-meta.xml
<CustomField>
    <fullName>Long_Description__c</fullName>
    <label>Long Description</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>ADD</fullName>
            </value>
            <value>
                <fullName>ADHD</fullName>
            </value>
            <value>
                <fullName>Allergic - All Nuts</fullName>
            </value>
            <value>
                <fullName>Allergic - Buckwheat</fullName>
            </value>
            <value>
                <fullName>Allergic - Eggs</fullName>
            </value>
            <value>
                <fullName>Allergic - Fish</fullName>
            </value>
            <value>
                <fullName>Allergic - Garlic</fullName>
            </value>
            <value>
                <fullName>Allergic - Kiwi Fruit</fullName>
            </value>
            <value>
                <fullName>Allergic - Mushrooms</fullName>
            </value>
            <value>
                <fullName>Allergic - Oranges</fullName>
            </value>
            <value>
                <fullName>Allergic - Other</fullName>
            </value>
            <value>
                <fullName>Allergic - Parmesan Cheese</fullName>
            </value>
            <value>
                <fullName>Allergic - Peanuts</fullName>
            </value>
            <value>
                <fullName>Allergic - Pork</fullName>
            </value>
            <value>
                <fullName>Allergic - Prawns</fullName>
            </value>
            <value>
                <fullName>Allergic - Seafood</fullName>
            </value>
            <value>
                <fullName>Allergic - Sesame</fullName>
            </value>
            <value>
                <fullName>Allergic - Shellfish</fullName>
            </value>
            <value>
                <fullName>Allergic - Tomatoes</fullName>
            </value>
            <value>
                <fullName>Allergic - Yeast</fullName>
            </value>
            <value>
                <fullName>Allergic to dust mites</fullName>
            </value>
            <value>
                <fullName>Allergy - Angel Cream</fullName>
            </value>
            <value>
                <fullName>Allergy - Antibiotic Erythromycin</fullName>
            </value>
            <value>
                <fullName>Allergy - Asparaginase</fullName>
            </value>
            <value>
                <fullName>Allergy - Asprin</fullName>
            </value>
            <value>
                <fullName>Allergy - Bactrim</fullName>
            </value>
            <value>
                <fullName>Allergy - Band Aids</fullName>
            </value>
            <value>
                <fullName>Allergy - Bee Stings</fullName>
            </value>
            <value>
                <fullName>Allergy - Bleomycin</fullName>
            </value>
            <value>
                <fullName>Allergy - Brietal</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Special_Needs__c/recordTypes/Dietary_Requirement.recordType-meta.xml
<RecordType>
    <fullName>Dietary_Requirement</fullName>
    <active>true</active>
    <label>Dietary Requirement</label>
</RecordType>

force-app/main/default/objects/Special_Needs__c/recordTypes/Special_Need.recordType-meta.xml
<RecordType>
    <fullName>Special_Need</fullName>
    <active>true</active>
    <description>Non-food related allergies</description>
    <label>Special Need</label>
</RecordType>

force-app/main/default/objects/Volunteer_Attendance__c/Volunteer_Attendance__c.object-meta.xml
<CustomObject>
    <description>Used for tracking volunteer attendance on programs. Linked to campaign member for communication, campaign for program, contact for volunteer</description>
    <label>Volunteer Attendance</label>
    <nameField>
        <displayFormat>VA{00000}</displayFormat>
        <label>Volunteer Attendance</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Volunteer Attendances</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Volunteer_Attendance__c/fields/Attendance__c.field-meta.xml
<CustomField>
    <fullName>Attendance__c</fullName>
    <label>Attendance</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Invited</fullName>
            </value>
            <value>
                <fullName>Request to Attend</fullName>
            </value>
            <value>
                <fullName>Accepted</fullName>
            </value>
            <value>
                <fullName>Attended</fullName>
            </value>
            <value>
                <fullName>Declined</fullName>
            </value>
            <value>
                <fullName>Unsuccessful</fullName>
            </value>
            <value>
                <fullName>No Show</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Medical Withdrawal</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Volunteer_Attendance__c/fields/Event__c.field-meta.xml
<CustomField>
    <fullName>Event__c</fullName>
    <label>Event</label>
    <referenceTo>Campaign</referenceTo>
    <relationshipLabel>Volunteer Attendances</relationshipLabel>
    <relationshipName>Volunteer_Attendances</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Volunteer_Attendance__c/fields/Volunteer__c.field-meta.xml
<CustomField>
    <fullName>Volunteer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Volunteer</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Volunteer Attendances</relationshipLabel>
    <relationshipName>Volunteer_Attendances</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/PrintSpecialNeedController.cls
public with sharing class PrintSpecialNeedController{
public Campaign cam{get;set;}

    public List< Special_Needs__c> VolSn{get; set;}
    public List< Special_Needs__c> FamSn{get; set;}
        public List< Special_Needs__c> VolDiet{get; set;}
    public List< Special_Needs__c> FamDiet{get; set;}

    public PrintSpecialNeedController(ApexPages.StandardController sc){
		if(!Test.isRunningTest())
            sc.addFields(new List<String>{'Name','RecordTypeId','RecordType.DeveloperName'});
            
        cam = (Campaign)sc.getRecord();
   		
        famSn = [SELECT Long_Description__c, Comments__c,Legacy_Comments_To_Be_Purged_June_2017__c, Date__c  ,contact__r.name, contact__r.Age__c, contact__r.family_member_type__C
from Special_Needs__c where  RecordType.DeveloperName='Special_Need'  and  contact__c in (SELECT contact__c from FAMILY_MEMBER_ATTENDANCE__C where (attendance__C='Accepted' or attendance__C='Attended') 
and event__c= :cam.id ) ORDER BY contact__r.lastname, contact__r.firstname];
            
        VolSn = [SELECT Long_Description__c, Comments__c, Legacy_Comments_To_Be_Purged_June_2017__c, Date__c  ,contact__r.name from Special_Needs__c where  RecordType.DeveloperName='Special_Need' 
and contact__C in (SELECT volunteer__c from VOLUNTEER_ATTENDANCE__C where (attendance__C='Accepted' or attendance__C='Attended') and event__c= :cam.id )
ORDER BY contact__r.lastname, contact__r.firstname];
        
        famDiet = [SELECT Long_Description__c, Comments__c,Legacy_Comments_To_Be_Purged_June_2017__c, Date__c  ,contact__r.name, contact__r.Age__c, contact__r.family_member_type__C
from Special_Needs__c where  RecordType.DeveloperName='Dietary_Requirement'  and  contact__c in (SELECT contact__c from FAMILY_MEMBER_ATTENDANCE__C where (attendance__C='Accepted' or attendance__C='Attended') 
and event__c= :cam.id ) ORDER BY contact__r.lastname, contact__r.firstname];       
            
        VolDiet = [SELECT Long_Description__c, Comments__c, Legacy_Comments_To_Be_Purged_June_2017__c, Date__c  ,contact__r.name from Special_Needs__c where  RecordType.DeveloperName='Dietary_Requirement' 
and contact__C in (SELECT volunteer__c from VOLUNTEER_ATTENDANCE__C where (attendance__C='Accepted' or attendance__C='Attended') and event__c= :cam.id )
ORDER BY contact__r.lastname, contact__r.firstname];

}
}