force-app/main/default/objects/Campaign/fields/Family_Member_Attendance__c.field-meta.xml
<CustomField>
    <fullName>Family_Member_Attendance__c</fullName>
    <label>Family Member Attendance</label>
    <summarizedField>Family_Attendance__c.Attended_Members__c</summarizedField>
    <summaryForeignKey>Family_Attendance__c.Event__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Campaign/fields/Volunteer_Attendance__c.field-meta.xml
<CustomField>
    <fullName>Volunteer_Attendance__c</fullName>
    <label>Volunteer Attendance</label>
    <summaryFilterItems>
        <field>Volunteer_Attendance__c.Attendance__c</field>
        <operation>equals</operation>
        <value>Attended</value>
    </summaryFilterItems>
    <summaryForeignKey>Volunteer_Attendance__c.Event__c</summaryForeignKey>
    <summaryOperation>count</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Campaign/recordTypes/Volunteer.recordType-meta.xml
<RecordType>
    <fullName>Volunteer</fullName>
    <active>true</active>
    <label>Volunteer</label>
</RecordType>

force-app/main/default/objects/CampaignMember/fields/Attendance__c.field-meta.xml
<CustomField>
    <fullName>Attendance__c</fullName>
    <label>Attendance</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Invited</fullName>
            </value>
            <value>
                <fullName>Request to Attend</fullName>
            </value>
            <value>
                <fullName>Accepted</fullName>
            </value>
            <value>
                <fullName>Attended</fullName>
            </value>
            <value>
                <fullName>Declined</fullName>
            </value>
            <value>
                <fullName>Unsuccessful</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/CampaignMember/fields/ContactX__c.field-meta.xml
<CustomField>
    <fullName>ContactX__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Campaign Members</relationshipLabel>
    <relationshipName>Campaign_Members</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/CampaignMember/fields/Family_Attendance__c.field-meta.xml
<CustomField>
    <fullName>Family_Attendance__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Family Attendance</label>
    <referenceTo>Family_Attendance__c</referenceTo>
    <relationshipLabel>Campaign Members</relationshipLabel>
    <relationshipName>Campaign_Members</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/CampaignMember/fields/Match_Up_Sent__c.field-meta.xml
<CustomField>
    <fullName>Match_Up_Sent__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Match Up Sent</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/CampaignMember/fields/Volunteer_Attendance__c.field-meta.xml
<CustomField>
    <fullName>Volunteer_Attendance__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Volunteer Attendance</label>
    <referenceTo>Volunteer_Attendance__c</referenceTo>
    <relationshipLabel>Campaign Members</relationshipLabel>
    <relationshipName>Campaign_Members</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Volunteer_Attendance__c.field-meta.xml
<CustomField>
    <fullName>Volunteer_Attendance__c</fullName>
    <label>Last Volunteer Attendance</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Contact/recordTypes/Volunteer.recordType-meta.xml
<RecordType>
    <fullName>Volunteer</fullName>
    <active>true</active>
    <label>Volunteer</label>
</RecordType>

force-app/main/default/objects/Family_Attendance__c/Family_Attendance__c.object-meta.xml
<CustomObject>
    <description>Used for recording details of families attendance on programs, linked to familiy member attendance, family guest attendance campaign member and campaign</description>
    <label>Family Attendance</label>
    <nameField>
        <displayFormat>FA{00000}</displayFormat>
        <label>Family Attendance</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Family Attendances</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Family_Attendance__c/fields/Event__c.field-meta.xml
<CustomField>
    <fullName>Event__c</fullName>
    <label>Event</label>
    <referenceTo>Campaign</referenceTo>
    <relationshipLabel>Family Attendances</relationshipLabel>
    <relationshipName>Family_Attendances</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Family_Member_Attendance__c/Family_Member_Attendance__c.object-meta.xml
<CustomObject>
    <description>Used for recording individual family member attendances on programs linked to family attendance</description>
    <label>Family Member Attendance</label>
    <nameField>
        <displayFormat>FMA{00000}</displayFormat>
        <label>Family Member Attendance</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Family Member Attendance</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Family_Member_Attendance__c/fields/Attendance__c.field-meta.xml
<CustomField>
    <fullName>Attendance__c</fullName>
    <label>Attendance</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Invited</fullName>
            </value>
            <value>
                <fullName>Request to Attend</fullName>
            </value>
            <value>
                <fullName>Accepted</fullName>
            </value>
            <value>
                <fullName>Attended</fullName>
            </value>
            <value>
                <fullName>Declined</fullName>
            </value>
            <value>
                <fullName>Unsuccessful</fullName>
            </value>
            <value>
                <fullName>No Show</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Cancelled &lt; 24 hours</fullName>
            </value>
            <value>
                <fullName>Medical Withdrawal</fullName>
            </value>
            <value>
                <fullName>Unsuccessful – Waitlist</fullName>
            </value>
            <value>
                <fullName>Unsuccessful – Declined</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Family_Member_Attendance__c/fields/Companion__c.field-meta.xml
<CustomField>
    <fullName>Companion__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Companion</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>$Source.Event__c</field>
            <operation>equals</operation>
            <valueField>Volunteer_Attendance__c.Event__c</valueField>
        </filterItems>
        <infoMessage>The volunteer attendance record must be for the same event.</infoMessage>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Volunteer_Attendance__c</referenceTo>
    <relationshipLabel>Companion Children</relationshipLabel>
    <relationshipName>Companion_Children</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Family_Member_Attendance__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Family Member Attendance</relationshipLabel>
    <relationshipName>Family_Member_Attendance</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Family_Member_Attendance__c/fields/Event__c.field-meta.xml
<CustomField>
    <fullName>Event__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Event</label>
    <referenceTo>Campaign</referenceTo>
    <relationshipLabel>Family Member Attendance</relationshipLabel>
    <relationshipName>Family_Member_Attendance</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Family_Member_Attendance__c/fields/Family_Attendance__c.field-meta.xml
<CustomField>
    <fullName>Family_Attendance__c</fullName>
    <label>Family Attendance</label>
    <referenceTo>Family_Attendance__c</referenceTo>
    <relationshipLabel>Family Member Attendance</relationshipLabel>
    <relationshipName>Family_Member_Attendance</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Volunteer_Attendance__c/Volunteer_Attendance__c.object-meta.xml
<CustomObject>
    <description>Used for tracking volunteer attendance on programs. Linked to campaign member for communication, campaign for program, contact for volunteer</description>
    <label>Volunteer Attendance</label>
    <nameField>
        <displayFormat>VA{00000}</displayFormat>
        <label>Volunteer Attendance</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Volunteer Attendances</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Volunteer_Attendance__c/fields/Attendance__c.field-meta.xml
<CustomField>
    <fullName>Attendance__c</fullName>
    <label>Attendance</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Invited</fullName>
            </value>
            <value>
                <fullName>Request to Attend</fullName>
            </value>
            <value>
                <fullName>Accepted</fullName>
            </value>
            <value>
                <fullName>Attended</fullName>
            </value>
            <value>
                <fullName>Declined</fullName>
            </value>
            <value>
                <fullName>Unsuccessful</fullName>
            </value>
            <value>
                <fullName>No Show</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Medical Withdrawal</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Volunteer_Attendance__c/fields/Event__c.field-meta.xml
<CustomField>
    <fullName>Event__c</fullName>
    <label>Event</label>
    <referenceTo>Campaign</referenceTo>
    <relationshipLabel>Volunteer Attendances</relationshipLabel>
    <relationshipName>Volunteer_Attendances</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Volunteer_Attendance__c/fields/Participation_Role__c.field-meta.xml
<CustomField>
    <fullName>Participation_Role__c</fullName>
    <label>Participation Role</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Activity Provider</fullName>
            </value>
            <value>
                <fullName>Camp Leader</fullName>
            </value>
            <value>
                <fullName>Chaperone</fullName>
            </value>
            <value>
                <fullName>Co-Driver</fullName>
            </value>
            <value>
                <fullName>Committee</fullName>
            </value>
            <value>
                <fullName>Companion</fullName>
            </value>
            <value>
                <fullName>Companion Support</fullName>
            </value>
            <value>
                <fullName>Coordinator</fullName>
            </value>
            <value>
                <fullName>Corporate Volunteer</fullName>
            </value>
            <value>
                <fullName>Doctor</fullName>
            </value>
            <value>
                <fullName>Driver</fullName>
            </value>
            <value>
                <fullName>Endorsed Enrolled Nurse</fullName>
            </value>
            <value>
                <fullName>Entrant</fullName>
            </value>
            <value>
                <fullName>Event Official</fullName>
            </value>
            <value>
                <fullName>Events/Fundraising</fullName>
            </value>
            <value>
                <fullName>First Aider</fullName>
            </value>
            <value>
                <fullName>Guest</fullName>
            </value>
            <value>
                <fullName>Host</fullName>
            </value>
            <value>
                <fullName>Leadership Committee Member</fullName>
            </value>
            <value>
                <fullName>Official</fullName>
            </value>
            <value>
                <fullName>Paramedic</fullName>
            </value>
            <value>
                <fullName>Participant</fullName>
            </value>
            <value>
                <fullName>Photographer</fullName>
            </value>
            <value>
                <fullName>Puppets - Puppeteer</fullName>
            </value>
            <value>
                <fullName>Registered Nurse</fullName>
            </value>
            <value>
                <fullName>Restaurant/Caterer</fullName>
            </value>
            <value>
                <fullName>Rover</fullName>
            </value>
            <value>
                <fullName>Speaker</fullName>
            </value>
            <value>
                <fullName>Staff</fullName>
            </value>
            <value>
                <fullName>Support Crew</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Volunteer_Attendance__c/fields/Volunteer__c.field-meta.xml
<CustomField>
    <fullName>Volunteer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Volunteer</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Volunteer Attendances</relationshipLabel>
    <relationshipName>Volunteer_Attendances</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Volunteer_Attendance__c/fields/Volunteer_Rating__c.field-meta.xml
<CustomField>
    <fullName>Volunteer_Rating__c</fullName>
    <label>Volunteer Rating</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Standout Volunteer</fullName>
            </value>
            <value>
                <fullName>Good Fit</fullName>
            </value>
            <value>
                <fullName>Still Settling In</fullName>
            </value>
            <value>
                <fullName>Needs Further Support/Training</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/SendSelectedEmailController.cls
public class SendSelectedEmailController {
    public Id camId {get;set;}
    public Map<Id, Family_Attendance__c> fas{get;set;}
    //public Map<Id, Family_Member_Attendance__c> fmas{get;set;}
    public Map<Id, Volunteer_Attendance__c> vas{get;set;}
    public integer numberOfContacts { get; set; }

    public Map<Id, Boolean> faEmail{get;set;}
    public Map<Id, Boolean> vaEmail{get;set;}

    public set<ID> emailAccounts{get;set;}

    public String markBy{get;set;}
    public Id attendId{get;set;}

    public ID templateId { get; set; }
    public ID fromEmailId { get; set; }


    public SendSelectedEmailController(ApexPages.StandardController sc) {

        camId = sc.getId();

        setAttendeds();
        markBy = 'Family';

    }
    public void setAttendeds() {

        loadAttendees();
        faEmail = new Map<Id, Boolean>();
        vaEmail = new Map<Id, Boolean>();
        emailAccounts = new set<id>();
        NumberOfContacts =0;
        if(fas != null) {
            for (Id fasId : fas.keySet()){
                if(fas.get(fasId).Campaign_Members__r.size() == 0){
                    fas.remove(fasId);
                }
            }

            for(Id key : fas.keySet()) {
                faEmail.put(key,False);
            }
        }

        if(vas != null) {
            for (Id vasId : vas.keySet()){
                if(vas.get(vasId).Campaign_Members__r.size() == 0){
                    vas.remove(vasId);
                }
            }

            for(Id key : vas.keySet()) {
                vaEmail.put(key, False);

            }
        }

    }
    private void loadAttendees() {

        if(markBy == 'Volunteer' ) {
            vas = new Map<Id, Volunteer_Attendance__c>([SELECT Id, Attendance__c, Volunteer__r.FirstName, Volunteer__r.LastName, Volunteer__r.MailingStreet, Volunteer__r.MailingCity, Volunteer__r.MailingState, Volunteer__r.MailingPostalCode, Volunteer_Rating__c, Participation_role__C , (select contact__r.firstname from Companion_Children__r),  (SELECT Match_Up_Sent__c from campaign_members__R limit 1)
            FROM Volunteer_Attendance__c
            WHERE Event__c = :camId
            AND (Attendance__c = 'Accepted' OR Attendance__c = 'Attended')]);
        } else {
            fas = new Map<Id, Family_Attendance__c>([SELECT Id,  FA_00000__c, (SELECT Match_Up_Sent__c from Campaign_Members__R limit 1) , Family__r.Name, Family__r.BillingStreet, Family__r.BillingCity, Family__r.BillingState, Family__r.BillingPostalCode, Family__r.npe01__One2OneContact__c , (SELECT Id, Contact__r.FirstName, Family_Member_Attendance__c.Companion__c, Family_Member_Attendance__c.Companion__r.Volunteer__r.FirstName FROM Family_Member_Attendance__r WHERE (Attendance__c = 'Accepted' OR Attendance__c = 'Attended') ) FROM Family_Attendance__c WHERE Event__c = :camId AND (FA_00000__c = 'Accepted' OR FA_00000__c = 'Attended')]);
        }


    }
    // the list of Org Wide Email Addresses
    public list<SelectOption> getlistSOFromEmails() {
        list<SelectOption> listSO = new list<SelectOption>();
        User thisUser = [Select Name, Email from User where id = :UserInfo.getUserId()];
        listSO.add(new SelectOption('', thisUser.Name + ' <' + thisUser.Email + '>'));
        for (OrgWideEmailAddress owa : [select id, Address, DisplayName from OrgWideEmailAddress]) {
            listSO.add(new SelectOption(owa.id, owa.DisplayName + ' <' + owa.Address + '>'));
        }
        return listSO;
    }
    public void updateEmailList() {

        System.debug('markBy: ' + markBy);


        if(markBy == 'Family' && fas != null && fas.containsKey(attendId)) {
            Family_Attendance__c fa = fas.get(attendId);

            if (faemail.get(attendId)) {

                emailAccounts.add(fa.Family__r.npe01__One2OneContact__c);

            }
            else
            {
                emailAccounts.remove(fa.Family__r.npe01__One2OneContact__c);
            }

        }
        else if(vas != null && vas.containsKey(attendId)) {
            Volunteer_Attendance__c va = vas.get(attendId);

            if (vaemail.get(attendId)) {
                emailAccounts.add(va.Volunteer__c);
            }
            else
            {
                emailAccounts.remove(va.Volunteer__c);
            }
        }

        NumberOfContacts = (emailAccounts != null ? emailAccounts.size() : 0);

    }
    public PageReference SendMail() {

        // do our validation
        if (numberOfContacts == 0) {
            ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.ERROR, 'No valid Contacts selected.'));
            return null;
        }
        if (markby == 'Family') {
            EmailTemplate etemp  =  [SELECT Id from EmailTemplate where developername ='Child_Match_Up_Letter' LIMIT 1];
            templateid = etemp.id;
        }
        else  {
            EmailTemplate etemp  =  [SELECT Id from EmailTemplate where developername ='Vol_Matchup_Letter' LIMIT 1];

            templateid = etemp.id;
        }

        if (templateId == null) {
            ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.ERROR, 'No valid Email Template selected.'));
            return null;
        }

        try {
            list<Messaging.SingleEmailMessage> listEmail = new list<Messaging.SingleEmailMessage>();

            string strSoql = 'select Id, ContactId,  Match_Up_Sent__c, Contact.Email, CampaignId, Status,Volunteer_Attendance__c, Family_Attendance__c from CampaignMember where  Contact.Email != null ';
            //DJA 29/11/2016 Added Campaign Member Type Filter
            //strSoql += 'and (status = \'Acceptance to be Sent\' or status = \'Acceptance Sent\' or status = \'Vol - Acceptance to be Sent\' or status = \'Vol - Acceptance Sent\' )';
            if(markBy == 'Family') {
                strSoql += ' AND Family_Attendance__c <> NULL ';
            }
            else {
                strSoql += ' AND Volunteer_Attendance__c <> NULL ';
            }

            if (camId != null) {
                strSoql += ' and CampaignId = :camId'; // don't use formula field which is text!
            }

            //Create local emailid set as private set was causing issues
            set<ID> emailID = new set<ID>();

            for (ID i : emailAccounts) {

                emailID.add(i);
            }

            emailAccounts.clear();
            NumberOfContacts =0;
            strSoql += ' and contactId IN :emailID';

            strSoql += ' order by CreatedDate LIMIT 200';
            // ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.ERROR,'Email Accounts' + emailAccounts));

            // to keep track of unique contacts
            set<ID> setContactId = new set<ID>();
            List<CampaignMember> updateCMs = new List<CampaignMember>();


            for (CampaignMember hr : database.query(strSoql)) {
                //send only once
                //if (setContactId.add(hr.ContactId) == true) {

                if (setContactId.add(hr.ContactId)) {

                    Messaging.SingleEmailMessage mail = new Messaging.SingleEmailMessage();

                    mail.setTargetObjectId(hr.ContactId);

                    string whatId;
                    //DJA 4/7/2017 Change to using volunteer or family attendance as the what object for email
/*                     if (templateObject == 'Campaign') {
                        whatId = hr.CampaignId;
                    }*/
                    whatId = hr.Id;

                    //string whatid;
                    if (hr.Volunteer_Attendance__c <> NULL) {
                        whatId =  hr.Volunteer_Attendance__c;
                    }
                    if (hr.Family_Attendance__c <> NULL) {
                        whatId = hr.Family_Attendance__c;
                    }

                    mail.setwhatid(whatId);

                    mail.setSaveAsActivity(true);

                    if (fromEmailId != null) {
                        mail.setOrgWideEmailAddressId(fromEmailId);
                    }

                    mail.setTemplateID(templateId);
                    System.debug('mail: '+ mail);

                    listEmail.add(mail);

                    hr.Match_Up_Sent__c = True;
                    updateCMs.add(hr);

                }


            }

            Map<Id, Contact> conMap = new Map<Id, Contact>([SELECT Id, Name, Email FROM Contact WHERE Id  IN :setContactId]);

            // send the email and return
            if (listEmail.size() > 0) {
                list<Messaging.SendEmailResult> listSER;
                listSER = Messaging.sendEmail(listEmail, false);

                // report problems
                integer cSuccess = 0;
                for (Messaging.SendEmailResult ser : listSER) {
                    if (ser.isSuccess()) {
                        cSuccess++;
                    } else {
                        list<Messaging.SendEmailError> listSEE = ser.getErrors();
                        System.debug(listSee);
                        for (Messaging.SendEmailError see : listSEE) {
                            ID objId = see.getTargetObjectId();
                            if (objId == null) {
                                // see if we can parse it out of the error string.
                                string strErr = see.getMessage();
                                integer ich = strErr.lastIndexOf(' for id : ');
                                if (ich > = 0) {
                                    objId = strErr.substring(ich + 10);
                                }
                            }

                            string strDetails = '';
                            if (conMap.containsKey(objId))
                                strDetails = ' ' + conMap.get(objId).Name + ' (' + conMap.get(objId).Email + ') ';
                            // special case logging Activity failing
                            if (see.getStatusCode() == System.StatusCode.FIELD_INTEGRITY_EXCEPTION && true)
                                strDetails += ' ' + 'Failed to log activity to Contact.';

                            ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.ERROR, see.getStatusCode() + ': ' + see.getMessage() + strDetails));
                        }
                    }
                }

                if(updateCMs.size() > 0) {
                    try {
                        update updateCMs;
                    } catch(DmlException ex) {
                        ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.ERROR, 'Failed to update Campaign Members: ' + ex.getMessage()));
                    }
                }

                if (cSuccess > 0) {
                    ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.INFO, 'Successfully Mass emailed Attendees.  Please click refresh on your browser to see updated records with Email Match Up Sent.' + ' ' + cSuccess));
                    System.debug('Successes: '+cSuccess);
                }

                if (listSER.size() > 0)
                    return null;  // stay on the page
            }
            ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.ERROR, 'No one selected: '));
            return null;
            //return Cancel(); // this will take us back to our calling page.

        } catch (exception ex) {
            ApexPages.addMessages(ex);
            return null;
        }
    }



    // action method that user wants to close this page
    public PageReference Cancel() {
        string strURL = ApexPages.currentPage().getParameters().get('retURL');
        if (strURL == null || strURL == '') strURL = '/';
        PageReference p = new PageReference(strURL);
        p.setRedirect(true);
        return p;
    }
}