force-app/main/default/objects/Property__c/Property__c.object-meta.xml
<CustomObject>
    <description>Used for family retreat - record of properties available for families to book from.  See documentation on Retreat booking under clouding around files for full details.</description>
    <label>Property</label>
    <nameField>
        <label>Property Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Properties</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Property__c/fields/Address__c.field-meta.xml
<CustomField>
    <fullName>Address__c</fullName>
    <description>Complete address shown on the portal</description>
    <inlineHelpText>Complete address shown on the portal</inlineHelpText>
    <label>Address</label>
    <length>2000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Property__c/fields/Available_for_booking_portal__c.field-meta.xml
<CustomField>
    <fullName>Available_for_booking_portal__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Shows property on the booking portal</description>
    <inlineHelpText>Shows property on the booking portal</inlineHelpText>
    <label>Available for booking portal</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Property__c/fields/Guests__c.field-meta.xml
<CustomField>
    <fullName>Guests__c</fullName>
    <description>Number of guests e.g. ( 7 = Sleeps 7 people)</description>
    <inlineHelpText>Number of guests e.g. ( 7 = Sleeps 7 people)</inlineHelpText>
    <label>Guests</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Property__c/fields/Length_of_stay__c.field-meta.xml
<CustomField>
    <fullName>Length_of_stay__c</fullName>
    <label>Length of stay</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>8 days (7 nights)</fullName>
            </value>
            <value>
                <fullName>7 days (6 nights)</fullName>
            </value>
            <value>
                <fullName>6 days (5 nights)</fullName>
            </value>
            <value>
                <fullName>5 days (4 nights)</fullName>
            </value>
            <value>
                <fullName>4 days (3 nights)</fullName>
            </value>
            <value>
                <fullName>3 days (2 nights)</fullName>
            </value>
            <value>
                <fullName>2 days (1 night)</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Property__c/fields/Portal_Description__c.field-meta.xml
<CustomField>
    <fullName>Portal_Description__c</fullName>
    <label>Portal Description</label>
    <length>32768</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/Property__c/fields/State__c.field-meta.xml
<CustomField>
    <fullName>State__c</fullName>
    <label>State</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>NSW</fullName>
            </value>
            <value>
                <fullName>QLD</fullName>
            </value>
            <value>
                <fullName>SA</fullName>
            </value>
            <value>
                <fullName>TAS</fullName>
            </value>
            <value>
                <fullName>VIC</fullName>
            </value>
            <value>
                <fullName>WA</fullName>
            </value>
            <value>
                <fullName>NT</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Retreat_Booking__c/Retreat_Booking__c.object-meta.xml
<CustomObject>
    <description>Used for retreat bookings through family portal.  See Property__C.</description>
    <label>Retreat Booking</label>
    <nameField>
        <displayFormat>RB-{000000}</displayFormat>
        <label>Booking Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Retreat Bookings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Retreat_Booking__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Retreat Bookings</relationshipLabel>
    <relationshipName>Retreat_Bookings</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Retreat_Booking__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Retreat Bookings</relationshipLabel>
    <relationshipName>Retreat_Bookings</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Retreat_Booking__c/fields/Guests__c.field-meta.xml
<CustomField>
    <fullName>Guests__c</fullName>
    <label>Guests</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Retreat_Booking__c/fields/Length_Of_Stay__c.field-meta.xml
<CustomField>
    <fullName>Length_Of_Stay__c</fullName>
    <formula>Check_Out_Date__c -  Check_In_Date__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Length Of Stay</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Retreat_Booking__c/fields/Property__c.field-meta.xml
<CustomField>
    <fullName>Property__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Property</label>
    <referenceTo>Property__c</referenceTo>
    <relationshipLabel>Retreat Bookings</relationshipLabel>
    <relationshipName>Retreat_Bookings</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Retreat_Booking__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Confirmed</fullName>
            </value>
            <value>
                <fullName>Declined</fullName>
            </value>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Rebooked</fullName>
            </value>
            <value>
                <fullName>Waitlisted Q1</fullName>
            </value>
            <value>
                <fullName>Waitlisted Q2</fullName>
            </value>
            <value>
                <fullName>Waitlisted Q3</fullName>
            </value>
            <value>
                <fullName>Waitlisted Q4</fullName>
            </value>
            <value>
                <fullName>Waitlisted</fullName>
                <isActive>false</isActive>
                <label>Waitlisted</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/FamilyRetreatsPageController.cls
/*****************************************************************************************************************************************************************************
* @Name         FamilyRetreatsPageController
* @Author       Amit Yadav
* @Date         10/22/2023
* @Description  This apex class manages the functionalities related to family retreats page. It provides methods to fetch and handle data related to family retreat properties.
*******************************************************************************************************************************************************************************  
MODIFICATION LOG
* Version          Developer          Date               Description
*
*  1.0             Amit Yadav         11/22/2023        Initial Creation                                                      
****************************************************************************************************************************************************************************/
//This apex class manages the functionalities related to family retreats page. It provides methods to fetch and handle data related to family retreat properties.
public without sharing class FamilyRetreatsPageController {
    //Retrieves property data for family retreats based on the user ID and returning list of FetchRetreatDataWrap containing property information and associated blob data.
    @AuraEnabled
    public static List<FetchRetreatDataWrap> getPropData(String recUserId){
        
        String decryptedString = FamilyPortalLoginController.decryptedData(recUserId);
        List<FetchRetreatDataWrap> camWrapperList = new List<FetchRetreatDataWrap>();       
        List<User> us = [SELECT Id, ContactId from User where Id=:decryptedString];      
        Contact con  = [Select Id, AccountId from Contact WHERE Id =:us[0].ContactId];
        List<Property__c> propList = [SELECT Id, Length_of_stay__c, Guests__c, Address__c, State__c, Available_for_booking_portal__c, Portal_Description__c,Name, 
                                      (SELECT Id, Account__c, Contact__c, Check_In_Date__c, Check_Out_Date__c, Status__c FROM Retreat_Bookings__r) FROM Property__c 
                                      WHERE Available_for_booking_portal__c = true];
        
        Set<Id> setContentDoc = new Set<Id>();  
        Set<Id> setOfpropId = new Set<Id>();
        // Collecting IDs of properties eligible for booking
        for(Property__c pr : propList){
            setOfpropId.add(pr.Id);
        }
        List<FetchRetreatDataWrap> retreatList = new List<FetchRetreatDataWrap>();
         // Fetching content document links related to eligible properties
        List<ContentDocumentLink> conLink = [SELECT Id, ContentDocumentId, LinkedEntityId FROM ContentDocumentLink WHERE LinkedEntityId IN:setOfpropId];
          // Gathering content document IDs
        for(ContentDocumentLink cdl : conLink){
            setContentDoc.add(cdl.ContentDocumentId);
        }
        
        List<ContentVersion> conVer = [SELECT ID, VersionData, Title, FirstPublishLocationId from ContentVersion WHERE ContentDocumentId IN:setContentDoc];
        Map<Id,Set<String>> propIdToBlob = new Map<Id,Set<String>>();
         // Creating a mapping between property IDs and associated blob data
        for(ContentVersion coVer : conVer){
            if(coVer.Title.contains('cq_portal_')){
                if(!propIdToBlob.containsKey(coVer.FirstPublishLocationId)){
                    propIdToBlob.put(coVer.FirstPublishLocationId, new Set<String>());  
                }
                propIdToBlob.get(coVer.FirstPublishLocationId).add(coVer.Id);
            }
        }
        for(Property__c prop : propList){
            FetchRetreatDataWrap fetctRetreat = new FetchRetreatDataWrap();
            fetctRetreat.propList = prop;
            fetctRetreat.blobData = propIdToBlob.get(prop.Id);
            retreatList.add(fetctRetreat);
            
        }          
        return retreatList;            
    }
    
    //Retrieves content version data for a given content version ID and it return hte base64 encoded version data of the content.
    @AuraEnabled
    public static String contentVersion(String contentVerId){
        List<ContentVersion> conVer = [SELECT ID, VersionData, FirstPublishLocationId from ContentVersion WHERE Id =:contentVerId];        
        return EncodingUtil.base64Encode(conVer[0].versionData);
    }
    
    // Wrapper class to hold property information and associated blob data.
    public class FetchRetreatDataWrap{
        @AuraEnabled public Property__c propList {get;set;}    
        @AuraEnabled public Set<String> blobData {get;set;}
    }      
}