force-app/main/default/objects/Property__c/Property__c.object-meta.xml
<CustomObject>
    <description>Used for family retreat - record of properties available for families to book from.  See documentation on Retreat booking under clouding around files for full details.</description>
    <label>Property</label>
    <nameField>
        <label>Property Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Properties</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Property__c/fields/Address__c.field-meta.xml
<CustomField>
    <fullName>Address__c</fullName>
    <description>Complete address shown on the portal</description>
    <inlineHelpText>Complete address shown on the portal</inlineHelpText>
    <label>Address</label>
    <length>2000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Property__c/fields/Available_for_booking_portal__c.field-meta.xml
<CustomField>
    <fullName>Available_for_booking_portal__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Shows property on the booking portal</description>
    <inlineHelpText>Shows property on the booking portal</inlineHelpText>
    <label>Available for booking portal</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Property__c/fields/Guests__c.field-meta.xml
<CustomField>
    <fullName>Guests__c</fullName>
    <description>Number of guests e.g. ( 7 = Sleeps 7 people)</description>
    <inlineHelpText>Number of guests e.g. ( 7 = Sleeps 7 people)</inlineHelpText>
    <label>Guests</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Property__c/fields/Length_of_stay__c.field-meta.xml
<CustomField>
    <fullName>Length_of_stay__c</fullName>
    <label>Length of stay</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>8 days (7 nights)</fullName>
            </value>
            <value>
                <fullName>7 days (6 nights)</fullName>
            </value>
            <value>
                <fullName>6 days (5 nights)</fullName>
            </value>
            <value>
                <fullName>5 days (4 nights)</fullName>
            </value>
            <value>
                <fullName>4 days (3 nights)</fullName>
            </value>
            <value>
                <fullName>3 days (2 nights)</fullName>
            </value>
            <value>
                <fullName>2 days (1 night)</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Property__c/fields/Portal_Description__c.field-meta.xml
<CustomField>
    <fullName>Portal_Description__c</fullName>
    <label>Portal Description</label>
    <length>32768</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/Property__c/fields/State__c.field-meta.xml
<CustomField>
    <fullName>State__c</fullName>
    <label>State</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>NSW</fullName>
            </value>
            <value>
                <fullName>QLD</fullName>
            </value>
            <value>
                <fullName>SA</fullName>
            </value>
            <value>
                <fullName>TAS</fullName>
            </value>
            <value>
                <fullName>VIC</fullName>
            </value>
            <value>
                <fullName>WA</fullName>
            </value>
            <value>
                <fullName>NT</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Retreat_Booking__c/Retreat_Booking__c.object-meta.xml
<CustomObject>
    <description>Used for retreat bookings through family portal.  See Property__C.</description>
    <label>Retreat Booking</label>
    <nameField>
        <displayFormat>RB-{000000}</displayFormat>
        <label>Booking Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Retreat Bookings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Retreat_Booking__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Retreat Bookings</relationshipLabel>
    <relationshipName>Retreat_Bookings</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Retreat_Booking__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Retreat Bookings</relationshipLabel>
    <relationshipName>Retreat_Bookings</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Retreat_Booking__c/fields/Guests__c.field-meta.xml
<CustomField>
    <fullName>Guests__c</fullName>
    <label>Guests</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Retreat_Booking__c/fields/Length_Of_Stay__c.field-meta.xml
<CustomField>
    <fullName>Length_Of_Stay__c</fullName>
    <formula>Check_Out_Date__c -  Check_In_Date__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Length Of Stay</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Retreat_Booking__c/fields/Property__c.field-meta.xml
<CustomField>
    <fullName>Property__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Property</label>
    <referenceTo>Property__c</referenceTo>
    <relationshipLabel>Retreat Bookings</relationshipLabel>
    <relationshipName>Retreat_Bookings</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Retreat_Booking__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Confirmed</fullName>
            </value>
            <value>
                <fullName>Declined</fullName>
            </value>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Rebooked</fullName>
            </value>
            <value>
                <fullName>Waitlisted Q1</fullName>
            </value>
            <value>
                <fullName>Waitlisted Q2</fullName>
            </value>
            <value>
                <fullName>Waitlisted Q3</fullName>
            </value>
            <value>
                <fullName>Waitlisted Q4</fullName>
            </value>
            <value>
                <fullName>Waitlisted</fullName>
                <isActive>false</isActive>
                <label>Waitlisted</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/FamilyRetreatsPageControllerTest.cls
@isTest
public class FamilyRetreatsPageControllerTest {
    
    @testSetup
    static void setupTestData() {
        // Create test data
        Account testAccount = new Account(Name = 'Test Account');
        insert testAccount;
        
        Contact testContact = new Contact(LastName = 'TestContact', AccountId = testAccount.Id, Email = 'test@gmail.com');
        insert testContact;
        
        Property__c prop = new Property__c();
        prop.Name = 'Test Prop';
        prop.Portal_Description__c = 'Test Description';
        prop.Available_for_booking_portal__c = true;
        prop.Guests__c = 4;
        prop.Address__c = 'Test Address here';
        prop.State__c = 'NSW';
        prop.Length_of_stay__c = '8 days (7 nights)';
        insert prop;
        
        ContentVersion cvlist = new Contentversion();        
        cvlist.Title = 'CZDSTOU';         
        cvlist.PathOnClient = 'test';         
        cvlist.VersionData = EncodingUtil.base64Decode('Unit Test Attachment Body');         
        List<ContentVersion> cvl = new List<ContentVersion>();         
        cvl.add(cvlist);         
        insert cvl;
        
        Retreat_Booking__c testBooking = new Retreat_Booking__c(
            Account__c = testAccount.Id,
            Contact__c = testContact.Id,
            Check_In_Date__c = Date.today(),
            Check_Out_Date__c = Date.today().addDays(7),
            Status__c = 'Waitlisted Q1',
            Property__c = prop.Id
        );
        insert testBooking;
    }
    
    @isTest
    static void testGetPropData() {
        // Call the method to be tested
        Test.startTest();
        //List<Retreat_Booking__c> result = FamilyRetreatsPageController.getPropData();
              ContentVersion conVer = [SELECT ID, VersionData, FirstPublishLocationId, Title from ContentVersion WHERE Title like '%CZ%'];        

        Contact con = [Select Id,FirstName,LastName,Email FROM Contact WHERE LastName LIKE '%Test%' LIMIT 1];
        System.debug('con --------------' + con);
        Profile CommunityProfile = [SELECT Id FROM Profile WHERE Name = 'My Camp Quality Members' LIMIT 1];
        System.debug('con --------------' + CommunityProfile);

        User us = new User(
            //IsActive=userActive,
            ContactId=con.Id,
            ProfileId=CommunityProfile.Id,
            EmailEncodingKey='UTF-8',
            LocaleSidKey='en_AU',
            LanguageLocaleKey='en_US',
            TimeZoneSidKey='Australia/Sydney',
            Email=con.Email,
            UserName=con.Email,
            Alias=con.Email.subString(0, 7),
            FirstName=con.FirstName,
            LastName=con.LastName
        );
        
        System.runAs(us){
            String userIdToEncrypt = us.Id;
            Blob key = EncodingUtil.base64Decode('gt7Mw8+jA++LgE8+U4+oCg==');
            Blob cipherText = Crypto.encryptWithManagedIV('AES128', key, Blob.valueOf(userIdToEncrypt));
            String encryptedString = EncodingUtil.base64Encode(cipherText);
            FamilyRetreatsPageController.getPropData(encryptedString);
            List<FamilyRetreatsPageController.FetchRetreatDataWrap> wrapList = FamilyRetreatsPageController.getPropData(encryptedString);  
            Assert.isNotNull(wrapList);
        }    
        
        String base64Data = FamilyRetreatsPageController.contentVersion(conVer.Id);
        // Assert that the method returns the expected base64 encoded data
        System.assertEquals(EncodingUtil.base64Encode(conVer.VersionData), base64Data);
        
        Test.stopTest();
    }
    
     @isTest
    static void testDecryptedData() {
        // Test data

		String userIdToEncrypt = UserInfo.getUserId() ;
        Blob key = EncodingUtil.base64Decode('gt7Mw8+jA++LgE8+U4+oCg==');
        Blob cipherText = Crypto.encryptWithManagedIV('AES128', key, Blob.valueOf(userIdToEncrypt));
        String encryptedString = EncodingUtil.base64Encode(cipherText);
        
        //String userIdToEncrypt = UserInfo.getUserId() ;
        Blob keyde = EncodingUtil.base64Decode('gt7Mw8+jA++LgE8+U4+oCg==');
        Blob cipherTextde = Crypto.decryptWithManagedIV('AES128', keyde, cipherText);
        String encryptedString2 = EncodingUtil.base64Encode(cipherText);

        // Call the method to test
        String decryptedString = FamilyPortalLoginController.decryptedData(encryptedString2);
        system.debug(decryptedString);

        // Verify the result
        System.assertEquals(userIdToEncrypt, decryptedString, 'Decryption failed');
    }
    
}