force-app/main/default/objects/Request_To_Fundraise__c/Request_To_Fundraise__c.object-meta.xml
<CustomObject>
    <description>Used for tracking the process of becoming a camp quality fundraiser. Has approval workflow</description>
    <label>Request To Fundraise</label>
    <nameField>
        <displayFormat>FRN-{0000}</displayFormat>
        <label>Fundraising Request Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Requests To Fundraise</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Request_To_Fundraise__c/fields/Approver__c.field-meta.xml
<CustomField>
    <fullName>Approver__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Approver</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>User.UserType</field>
            <operation>equals</operation>
            <value>Standard</value>
        </filterItems>
        <filterItems>
            <field>User.IsActive</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>User</referenceTo>
    <relationshipName>Requests_To_Fundraise1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Request_To_Fundraise__c/fields/ATF_Status__c.field-meta.xml
<CustomField>
    <fullName>ATF_Status__c</fullName>
    <defaultValue>&quot;New Request/Registration&quot;</defaultValue>
    <label>ATF Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>New Request/Registration</fullName>
            </value>
            <value>
                <fullName>Contacted</fullName>
            </value>
            <value>
                <fullName>Request Approval</fullName>
            </value>
            <value>
                <fullName>Authorised</fullName>
            </value>
            <value>
                <fullName>ATF created and sent</fullName>
            </value>
            <value>
                <fullName>Funds Received</fullName>
            </value>
            <value>
                <fullName>Thanked</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
            <value>
                <fullName>Authority To Fundraise Declined</fullName>
                <label>RTF Declined</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Request_To_Fundraise__c/fields/Campaign__c.field-meta.xml
<CustomField>
    <fullName>Campaign__c</fullName>
    <inlineHelpText>Online: auto populated
Manual: until the RTF has been through the approval process link this application to your Branch’s Master Campaign:
Eg; ILLA Community Fundraising non gst</inlineHelpText>
    <label>Campaign</label>
    <referenceTo>Campaign</referenceTo>
    <relationshipLabel>Requests To Fundraise</relationshipLabel>
    <relationshipName>Fundraising_Registrations</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Request_To_Fundraise__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Requests To Fundraise</relationshipLabel>
    <relationshipName>Fundraising_Registrations</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/GetProcessInstanceLocalDataTest.cls
/**
 * @Author  :   Minal Zaa 
 * @Date    :   Apr 7 2023
 * @Desc    :   Test class for GetProcessInstanceData - Coverage 97%
 */
@IsTest
public with sharing class GetProcessInstanceLocalDataTest {
    public GetProcessInstanceLocalDataTest() { }

    @isTest
    static void testGetProcessInstanceData() { 
        User approver = [SELECT Id FROM User WHERE IsActive = true AND UserRole.Name = 'System Administrator' LIMIT 1]; 

        // Create test data
        List<SObject> lstCamp = TestDataFactory.createTestData('Campaign', 1); 
        insert lstCamp; 
        List<SObject> lstAcc = TestDataFactory.createTestData('Account', 1); 
        insert lstAcc; 
        List<Account> lstAccount = [SELECT Id FROM Account];
        System.assertEquals(1, lstAccount.size(), 'Expected 1 Account records to be created'); 
        List<SObject> lstCon = TestDataFactory.createTestData('Contact', 1);
        for(SObject o : lstCon){
            o.put('AccountId', lstAccount[0].Id) ; 
        }
        insert lstCon;
        List<Contact> lstContact = [SELECT Id FROM Contact];
        System.assertEquals(1, lstContact.size(), 'Expected 1 Contact records to be created'); 

        List<SObject> lstReqToFundRaise = TestDataFactory.createTestData('Request_To_Fundraise__c', 1);
        for(SObject o : lstReqToFundRaise){
            o.put('ATF_Status__c', 'Request Approval') ;
            o.put('Contact__c', lstContact[0].Id); 
            o.put('Campaign__c', lstCamp[0].Id); 
            o.put('Approver__c', approver.id);
        }
        insert lstReqToFundRaise;
        
        

        // Create an approval process for Account
        Approval.ProcessSubmitRequest submitRequest = new Approval.ProcessSubmitRequest();
        submitRequest.setObjectId(lstReqToFundRaise[0].Id);
        submitRequest.setNextApproverIds(new List<Id>{approver.Id}); 

        // Test getProcessItemData
        String fieldNames = 'Name';
        String objectName = 'Request_To_Fundraise__c';
        String mode = 'View';
        String processItemData = GetProcessInstanceData.getProcessItemData(approver.Id, fieldNames, objectName, mode);
        System.assertNotEquals(null, processItemData, 'Process Item Data should not be null.');

        // Test process method
        List<String> workItemIds = new List<String>();
        for(ProcessInstanceWorkitem workitem : [SELECT Id FROM ProcessInstanceWorkitem WHERE ActorId = :approver.Id]) {
            workItemIds.add(workitem.Id);
        }

        Test.startTest();
        GetProcessInstanceData.process(null, 'Approve', workItemIds, 'Approved');
        Test.stopTest();

    }

    @isTest
    static void testProcessReassign() {
        List<User> users = [SELECT Id FROM User WHERE IsActive = true AND UserRole.Name = 'System Administrator' LIMIT 2]; 

        User approver = users[0];
        User reassignActor = users[1];

        // Create test data
        List<SObject> lstCamp = TestDataFactory.createTestData('Campaign', 1); 
        insert lstCamp; 
        List<SObject> lstAcc = TestDataFactory.createTestData('Account', 1); 
        insert lstAcc; 
        List<Account> lstAccount = [SELECT Id FROM Account];
        System.assertEquals(1, lstAccount.size(), 'Expected 1 Account records to be created'); 
        List<SObject> lstCon = TestDataFactory.createTestData('Contact', 1);
        for(SObject o : lstCon){
            o.put('AccountId', lstAccount[0].Id) ; 
        }
        insert lstCon;
        List<Contact> lstContact = [SELECT Id FROM Contact];
        System.assertEquals(1, lstContact.size(), 'Expected 1 Contact records to be created'); 

        List<SObject> lstReqToFundRaise = TestDataFactory.createTestData('Request_To_Fundraise__c', 1);
        for(SObject o : lstReqToFundRaise){
            o.put('ATF_Status__c', 'Request Approval') ;
            o.put('Contact__c', lstContact[0].Id); 
            o.put('Campaign__c', lstCamp[0].Id); 
            o.put('Approver__c', approver.id);
        }
        insert lstReqToFundRaise;

        

        // Create an approval process for Account
        Approval.ProcessSubmitRequest submitRequest = new Approval.ProcessSubmitRequest();
        submitRequest.setObjectId(lstReqToFundRaise[0].Id);
        submitRequest.setNextApproverIds(new List<Id>{approver.Id}); 

        // Test process method with 'Reassign' action
        List<String> workItemIds = new List<String>();
        for(ProcessInstanceWorkitem workitem : [SELECT Id FROM ProcessInstanceWorkitem WHERE ActorId = :approver.Id]) {
            workItemIds.add(workitem.Id);
        }

        Test.startTest();
        GetProcessInstanceData.process(reassignActor.Id, 'Reassign', workItemIds, 'Reassigning');
        Test.stopTest();

        ProcessInstanceWorkitem reassignedWorkitem = [SELECT Id, ActorId FROM ProcessInstanceWorkitem WHERE Id IN :workItemIds];
        System.assertEquals(reassignActor.Id, reassignedWorkitem.ActorId, 'The approval process should have been reassigned to the new actor.');
    }
}