force-app/main/default/objects/Page__c/Page__c.object-meta.xml
<CustomObject>
    <description>Used to create portal pages in the programs Salesforce community</description>
    <label>Page</label>
    <nameField>
        <label>Page Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Pages</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Page__c/fields/Content__c.field-meta.xml
<CustomField>
    <fullName>Content__c</fullName>
    <label>Content</label>
    <length>32768</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/Page__c/fields/Site__c.field-meta.xml
<CustomField>
    <fullName>Site__c</fullName>
    <label>Site</label>
    <referenceTo>Site__c</referenceTo>
    <relationshipLabel>Pages</relationshipLabel>
    <relationshipName>Pages</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Site__c/Site__c.object-meta.xml
<CustomObject>
    <description>Portal custom object for the different views/subsites on portal i.e. Family Volunteer Corporate Volunteer</description>
    <label>Site</label>
    <nameField>
        <label>Site Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sites</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Site__c/fields/Contact_Access_Field__c.field-meta.xml
<CustomField>
    <fullName>Contact_Access_Field__c</fullName>
    <label>Contact Access Field</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Site__c/fields/Required_Permission_Set__c.field-meta.xml
<CustomField>
    <fullName>Required_Permission_Set__c</fullName>
    <label>Required Permission Set</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Site__c/fields/Site_URL__c.field-meta.xml
<CustomField>
    <fullName>Site_URL__c</fullName>
    <label>Site URL</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/classes/VolunteerResourcesControllerTest.cls
/********************************************************************************************
* @Name         VolunteerResourcesControllerTest
* @Author       Amit Yadav
* @Date         12/01/2023
* @Description  VolunteerResourcesControllerTest class contains test methods to validate 
				the behavior of methods in the VolunteerResourcesController class. 
				It focuses on testing various functionalities and cover positive negative senario.
******************************************************************************************* 
MODIFICATION LOG
* Version          Developer          Date               Description
*
*  1.0             Amit Yadav         12/01/2023        Initial Creation                                                      
******************************************************************************************* */
@isTest
public class VolunteerResourcesControllerTest {
    
    @testSetup
    public static void testData(){
        // Creating a test Site data  
        Site__c si = new Site__c();
        si.Name = 'testSite';
        si.Required_Permission_Set__c = 'Volunteer_Portal_Permissions';
        si.Contact_Access_Field__c = 'testContactAccess';
        si.Site_URL__c = 'siteUrl';
        insert si;
        // Creating a test Page data  
        Page__c pg = new Page__c();
        pg.Content__c = 'text contenct on a page';
        pg.Title__c = 'Online Resources';
        pg.Site__c = si.Id;
        insert pg;
    }
    
    @isTest
    public static void testcheckResource(){
        
        Test.startTest();
        // Calling the getResources method.
        String resources = VolunteerResourcesController.getResources();       
        // Assuming getResources should return a non-null list
        System.assertNotEquals(null, resources, 'Resource list should not be null');
        Test.stopTest();
            
    }

}