force-app/main/default/objects/Page__c/Page__c.object-meta.xml
<CustomObject>
    <description>Used to create portal pages in the programs Salesforce community</description>
    <label>Page</label>
    <nameField>
        <label>Page Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Pages</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Page__c/fields/Content__c.field-meta.xml
<CustomField>
    <fullName>Content__c</fullName>
    <label>Content</label>
    <length>32768</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/Page__c/fields/Site__c.field-meta.xml
<CustomField>
    <fullName>Site__c</fullName>
    <label>Site</label>
    <referenceTo>Site__c</referenceTo>
    <relationshipLabel>Pages</relationshipLabel>
    <relationshipName>Pages</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Site__c/Site__c.object-meta.xml
<CustomObject>
    <description>Portal custom object for the different views/subsites on portal i.e. Family Volunteer Corporate Volunteer</description>
    <label>Site</label>
    <nameField>
        <label>Site Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sites</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Site__c/fields/Contact_Access_Field__c.field-meta.xml
<CustomField>
    <fullName>Contact_Access_Field__c</fullName>
    <label>Contact Access Field</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Site__c/fields/Default_Page__c.field-meta.xml
<CustomField>
    <fullName>Default_Page__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Default Page</label>
    <referenceTo>Page__c</referenceTo>
    <relationshipLabel>Sites</relationshipLabel>
    <relationshipName>Sites</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Site__c/fields/Required_Permission_Set__c.field-meta.xml
<CustomField>
    <fullName>Required_Permission_Set__c</fullName>
    <label>Required Permission Set</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Site__c/fields/Site_URL__c.field-meta.xml
<CustomField>
    <fullName>Site_URL__c</fullName>
    <label>Site URL</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/classes/FamilyResourcePageControllerTest.cls
@istest
public class FamilyResourcePageControllerTest {
    
    @testSetup
    public static void testSetUpData(){
        
        
        Site__c si = new Site__c();
        si.Name = 'TestSite';
        si.Required_Permission_Set__c = 'Family_Portal_Permissions';
        si.Contact_Access_Field__c = 'testContact';
        si.Site_URL__c = 'TestSiteURL';
        //si.Default_Page__c = pg.Id;
        insert si;
        
        Page__c pg = new Page__c();
        pg.Content__c = 'text contect on a page';
        pg.Title__c = 'Resources';
        pg.Site__c = si.Id;
        insert pg;
                    
    }
    
    @istest
    public static void testPotalData(){
        Test.startTest();
        List<Site__c> si = [Select id,Name From site__c Where Name like 'Test%' Limit 1];
        String resourceResult  = FamilyResourcePageController.getFamilyResources();
	
		Page__c expectedPage = [SELECT Id, Content__c, Title__c, Site__c FROM Page__c
                                WHERE Site__c = :si[0].Id AND Title__c = 'Resources' LIMIT 1];
        String expectedData = JSON.serialize(expectedPage);

        System.assertEquals(expectedData, expectedData, 'Returned data should match expected data');
        Test.stopTest();
            
    }

}