force-app/main/default/objects/Page__c/Page__c.object-meta.xml
<CustomObject>
    <description>Used to create portal pages in the programs Salesforce community</description>
    <label>Page</label>
    <nameField>
        <label>Page Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Pages</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Page__c/fields/Content__c.field-meta.xml
<CustomField>
    <fullName>Content__c</fullName>
    <label>Content</label>
    <length>32768</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/Page__c/fields/Site__c.field-meta.xml
<CustomField>
    <fullName>Site__c</fullName>
    <label>Site</label>
    <referenceTo>Site__c</referenceTo>
    <relationshipLabel>Pages</relationshipLabel>
    <relationshipName>Pages</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Site__c/Site__c.object-meta.xml
<CustomObject>
    <description>Portal custom object for the different views/subsites on portal i.e. Family Volunteer Corporate Volunteer</description>
    <label>Site</label>
    <nameField>
        <label>Site Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sites</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Site__c/fields/Contact_Access_Field__c.field-meta.xml
<CustomField>
    <fullName>Contact_Access_Field__c</fullName>
    <label>Contact Access Field</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Site__c/fields/Required_Permission_Set__c.field-meta.xml
<CustomField>
    <fullName>Required_Permission_Set__c</fullName>
    <label>Required Permission Set</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Site__c/fields/Site_URL__c.field-meta.xml
<CustomField>
    <fullName>Site_URL__c</fullName>
    <label>Site URL</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/classes/FamilyResourcePageController.cls
/********************************************************************************************
* @Name         FamilyResourcePageController
* @Author       Amit Yadav
* @Date         10/22/2023
* @Description  This apex class is responsible for handling family resource page-related functionalities. 
				It provides methods to retrieve family resources based on certain criteria.
******************************************************************************************* 
MODIFICATION LOG
* Version          Developer          Date               Description
*
*  1.0             Amit Yadav         11/22/2023        Initial Creation                                                      
******************************************************************************************* */
//This apex class is responsible for handling family resource page-related functionalities. It provides methods to retrieve family resources based on certain criteria.
public without sharing class FamilyResourcePageController {
	
    @AuraEnabled
    public static String getFamilyResources(){
        // Query the Site__c object to retrieve site information
		List<Site__c> siteList = [Select Name , Required_Permission_Set__c , Contact_Access_Field__c , Site_URL__c From Site__c Where Required_Permission_Set__c = 'Family_Portal_Permissions' Limit 1];
        String data = '';
		if(siteList.size() > 0){
            List<Page__c> pageList = [Select Content__c , Title__c , Site__c From Page__c Where Site__c = : siteList[0].Id AND Title__c = 'Resources'];
             data = JSON.serialize(PageList[0]);
        }
        //Return the JSON string containing family resource data
        return data;
	}
}