force-app/main/default/objects/Page__c/Page__c.object-meta.xml
<CustomObject>
    <description>Used to create portal pages in the programs Salesforce community</description>
    <label>Page</label>
    <nameField>
        <label>Page Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Pages</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Page__c/fields/Content__c.field-meta.xml
<CustomField>
    <fullName>Content__c</fullName>
    <label>Content</label>
    <length>32768</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/Page__c/fields/Site__c.field-meta.xml
<CustomField>
    <fullName>Site__c</fullName>
    <label>Site</label>
    <referenceTo>Site__c</referenceTo>
    <relationshipLabel>Pages</relationshipLabel>
    <relationshipName>Pages</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Site__c/Site__c.object-meta.xml
<CustomObject>
    <description>Portal custom object for the different views/subsites on portal i.e. Family Volunteer Corporate Volunteer</description>
    <label>Site</label>
    <nameField>
        <label>Site Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sites</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Site__c/fields/Contact_Access_Field__c.field-meta.xml
<CustomField>
    <fullName>Contact_Access_Field__c</fullName>
    <label>Contact Access Field</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Site__c/fields/Required_Permission_Set__c.field-meta.xml
<CustomField>
    <fullName>Required_Permission_Set__c</fullName>
    <label>Required Permission Set</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Site__c/fields/Site_URL__c.field-meta.xml
<CustomField>
    <fullName>Site_URL__c</fullName>
    <label>Site URL</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/classes/VolunteerResourcesController.cls
/********************************************************************************************
* @Name         VolunteerResourcesController
* @Author       Amit Yadav
* @Date         10/22/2023
* @Description  Apex class responsible for handling requests related to volunteer resources
******************************************************************************************* 
MODIFICATION LOG
* Version          Developer          Date               Description
*
*  1.0             Amit Yadav         10/22/2023        Initial Creation                                                      
******************************************************************************************* */
//Apex class responsible for handling requests related to volunteer resources.
public without sharing class VolunteerResourcesController {
    
    //Retrieves volunteer resources data for the volunteer portal and return the Serialized JSON data containing information about online resources.
    @AuraEnabled
    public static String getResources(){
        // Fetching the site details associated with the required permission set.
        List<Site__c> siteList = [SELECT Name , Required_Permission_Set__c , Contact_Access_Field__c , Site_URL__c FROM Site__c WHERE Required_Permission_Set__c = 'Volunteer_Portal_Permissions' LIMIT 1];
        String data = '';
        if(siteList.size() > 0){
            // Fetching the page details for online resources based on the site.
            List<Page__c> pageList = [SELECT Content__c , Title__c , Site__c FROM Page__c WHERE Site__c = : siteList[0].Id AND Title__c = 'Online Resources'];
            // Serializing the first page's details to JSON.
            data = JSON.serialize(PageList[0]);
        }
        return data;
    }
}