force-app/main/default/objects/Page__c/Page__c.object-meta.xml
<CustomObject>
    <description>Used to create portal pages in the programs Salesforce community</description>
    <label>Page</label>
    <nameField>
        <label>Page Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Pages</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Page__c/fields/Page_Template__c.field-meta.xml
<CustomField>
    <fullName>Page_Template__c</fullName>
    <label>Page Template</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>portalPage</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Page__c/fields/Page_URL_Name__c.field-meta.xml
<CustomField>
    <fullName>Page_URL_Name__c</fullName>
    <label>Page URL Name</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Page__c/fields/Site__c.field-meta.xml
<CustomField>
    <fullName>Site__c</fullName>
    <label>Site</label>
    <referenceTo>Site__c</referenceTo>
    <relationshipLabel>Pages</relationshipLabel>
    <relationshipName>Pages</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Site__c/Site__c.object-meta.xml
<CustomObject>
    <description>Portal custom object for the different views/subsites on portal i.e. Family Volunteer Corporate Volunteer</description>
    <label>Site</label>
    <nameField>
        <label>Site Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sites</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Site__c/fields/Default_Page__c.field-meta.xml
<CustomField>
    <fullName>Default_Page__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Default Page</label>
    <referenceTo>Page__c</referenceTo>
    <relationshipLabel>Sites</relationshipLabel>
    <relationshipName>Sites</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Site__c/fields/Required_Permission_Set__c.field-meta.xml
<CustomField>
    <fullName>Required_Permission_Set__c</fullName>
    <label>Required Permission Set</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Site__c/fields/Site_URL__c.field-meta.xml
<CustomField>
    <fullName>Site_URL__c</fullName>
    <label>Site URL</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Site__c/fields/Site_URL_Name__c.field-meta.xml
<CustomField>
    <fullName>Site_URL_Name__c</fullName>
    <label>Community URL Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/portalLandingController.cls
public class portalLandingController {

    private List<PermissionSetAssignment> assignments{get;set;}

	public PageReference goToHomePage() {
		String sitePathPrefix = Site.getPathPrefix().removeStart('/');
        if (Test.isRunningTest())
            sitePathPrefix = 'members';
        System.debug(sitePathPrefix);

        List<Site__c> sList = new List<Site__c>([SELECT Id, Name, Default_Page__c, Required_Permission_Set__c, Default_Page__r.Page_Template__c, Default_Page__r.Page_URL_Name__c, Site_URL__c FROM Site__c WHERE Site_URL_Name__c = :sitePathPrefix AND Default_Page__c != null]);

        Set<String> siteRequiredPSAs = new Set<String>();

        for(Site__c s : sList) {
            if(String.isNotEmpty(s.Required_Permission_Set__c)) {
                System.debug(s.Required_Permission_Set__c);
                siteRequiredPSAs.add(s.Required_Permission_Set__c);
            }
        }

        assignments = [SELECT Id, AssigneeId, PermissionSet.Id, PermissionSet.Name, PermissionSet.Label FROM PermissionSetAssignment WHERE AssigneeId =:UserInfo.getUserId() AND PermissionSet.Name IN :SiteRequiredPSAs];

        for(Site__c s : sList) {
            System.debug('Is available:' + isAvailableSite(s));
            if (isAvailableSite(s)) {

                String sitePath = String.isNotEmpty(s.Site_URL__c) ? s.Site_URL__c : s.Id;
                String pagePath = s.Default_Page__c;

                if(String.isNotEmpty(s.Default_Page__c) && String.isNotEmpty(s.Default_Page__r.Page_URL_Name__c)) {
                    pagePath = s.Default_Page__r.Page_URL_Name__c;
                } 

                return new PageReference('/' + sitePathPrefix + '/' + s.Default_Page__r.Page_Template__c + '?s=' + sitePath + '&p=' + pagePath);
            }
        }

        return Page.portalLogin;
	}

    private Boolean isAvailableSite(Site__c site) {

        for(PermissionSetAssignment psa : assignments) {
            if(String.isEmpty(site.Required_Permission_Set__c) || site.Required_Permission_Set__c == psa.PermissionSet.Name)
                return true;
        }

        return false;

    }
}