force-app/main/default/objects/Article__c/Article__c.object-meta.xml
<CustomObject>
    <description>Used for creating portal news items</description>
    <label>Article</label>
    <nameField>
        <label>Article Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Articles</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Article__c/fields/Article_Date__c.field-meta.xml
<CustomField>
    <fullName>Article_Date__c</fullName>
    <defaultValue>NOW()</defaultValue>
    <label>Article Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Article__c/fields/Article_Link_URL__c.field-meta.xml
<CustomField>
    <fullName>Article_Link_URL__c</fullName>
    <label>Article Link URL</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/Article__c/fields/Body_Text__c.field-meta.xml
<CustomField>
    <fullName>Body_Text__c</fullName>
    <label>Body Text</label>
    <length>32768</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/Article__c/fields/Close_Date__c.field-meta.xml
<CustomField>
    <fullName>Close_Date__c</fullName>
    <description>The date that the article should cease to display in the portal (leave blank to display in perpetuity).</description>
    <inlineHelpText>The date that the article should cease to display in the portal (leave blank to display in perpetuity).</inlineHelpText>
    <label>Close Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Article__c/fields/Order__c.field-meta.xml
<CustomField>
    <fullName>Order__c</fullName>
    <description>Articles order by date by default, but the Order field can be used to place articles at the top.</description>
    <inlineHelpText>Articles order by date by default, but the Order field can be used to place articles at the top.</inlineHelpText>
    <label>Order</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Article__c/fields/Show_in_Portal__c.field-meta.xml
<CustomField>
    <fullName>Show_in_Portal__c</fullName>
    <label>Show in Portal</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Family</fullName>
            </value>
            <value>
                <fullName>Volunteer</fullName>
            </value>
            <value>
                <fullName>Both</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/NewsArticleController.cls
public class NewsArticleController {

    public String pType {
        get;
        set {
            pType = value;
            
            if(String.isNotEmpty(pType)) {
                load();
            }
        }
    }
    
    public List<Article__c> articles{get;set;}
    
    public NewsArticleController() {
    	load();
    }
    
    public void load() {
        
        articles = [SELECT Id, Name, Title__c, Body_Text__c, Article_Date__c, Close_Date__c, Show_in_Portal__c, Image_URL__c, Article_Link_URL__c
                    FROM Article__c WHERE (Show_in_Portal__c = 'Both' OR Show_in_Portal__c = :pType) AND (Close_Date__c = NULL OR Close_Date__c >= :Datetime.Now())
                   	ORDER BY Order__c ASC NULLS LAST,Article_Date__c DESC];
        
    }
    
}