force-app/main/default/objects/Peak_Period__c/Peak_Period__c.object-meta.xml
<CustomObject>
    <description>Used for family retreat peak period settings.  See Property__C</description>
    <label>Peak Period</label>
    <nameField>
        <label>Peak period restrictions Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Peak Periods</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Peak_Period__c/fields/End_Date__c.field-meta.xml
<CustomField>
    <fullName>End_Date__c</fullName>
    <description>Peak period end date</description>
    <inlineHelpText>Peak period end date</inlineHelpText>
    <label>End Date</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Peak_Period__c/fields/Property__c.field-meta.xml
<CustomField>
    <fullName>Property__c</fullName>
    <label>Property</label>
    <referenceTo>Property__c</referenceTo>
    <relationshipLabel>Peak Periods</relationshipLabel>
    <relationshipName>Peak_Periods</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Peak_Period__c/fields/Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Start_Date__c</fullName>
    <description>Peak period start date</description>
    <inlineHelpText>Peak period start date</inlineHelpText>
    <label>Start Date</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Property__c/Property__c.object-meta.xml
<CustomObject>
    <description>Used for family retreat - record of properties available for families to book from.  See documentation on Retreat booking under clouding around files for full details.</description>
    <label>Property</label>
    <nameField>
        <label>Property Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Properties</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Retreat_Booking__c/Retreat_Booking__c.object-meta.xml
<CustomObject>
    <description>Used for retreat bookings through family portal.  See Property__C.</description>
    <label>Retreat Booking</label>
    <nameField>
        <displayFormat>RB-{000000}</displayFormat>
        <label>Booking Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Retreat Bookings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Retreat_Booking__c/fields/Property__c.field-meta.xml
<CustomField>
    <fullName>Property__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Property</label>
    <referenceTo>Property__c</referenceTo>
    <relationshipLabel>Retreat Bookings</relationshipLabel>
    <relationshipName>Retreat_Bookings</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Retreat_Booking__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Confirmed</fullName>
            </value>
            <value>
                <fullName>Declined</fullName>
            </value>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Rebooked</fullName>
            </value>
            <value>
                <fullName>Waitlisted Q1</fullName>
            </value>
            <value>
                <fullName>Waitlisted Q2</fullName>
            </value>
            <value>
                <fullName>Waitlisted Q3</fullName>
            </value>
            <value>
                <fullName>Waitlisted Q4</fullName>
            </value>
            <value>
                <fullName>Waitlisted</fullName>
                <isActive>false</isActive>
                <label>Waitlisted</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/RetreatValidation.cls
public class RetreatValidation {

    public static void checkForExistingPeriod(List<Peak_Period__c> triggerNew) {
        Set<Id> propertyIds = new Set<Id>();
        Set<Date> startDates = new Set<Date>();
        Set<Date> endDates = new Set<Date>();

        for (Peak_Period__c period : triggerNew) {
            propertyIds.add(period.Property__c);
            startDates.add(period.Start_Date__c);
            endDates.add(period.End_Date__c);
        }

        List<Peak_Period__c> existingPeriods = new List<Peak_Period__c>([
                SELECT Id, Start_Date__c, End_Date__c, Property__c
                FROM Peak_Period__c
                WHERE Property__c = :propertyIds
                AND ((Start_Date__c >= :startDates AND Start_Date__c <= :endDates)
                OR (End_Date__c >= :startDates AND End_Date__c <= :endDates)
                OR (Start_Date__c <= :startDates AND End_Date__c >= :endDates))
        ]);

        for (Peak_Period__c period : triggerNew) {
            for (Peak_Period__c existing : existingPeriods) {
                if (period.Property__c.equals(existing.Property__c) && ((Trigger.isUpdate && !(period.Id.equals(existing.Id))) || Trigger.isInsert)) {
                    if (foundOverlap(existing.Start_Date__c, existing.End_Date__c, period.Start_Date__c, period.End_Date__c)) {
                        period.addError('Found existing period, Id: ' + existing.Id);
                    }
                }
            }
        }
    }

    public static void checkForExistingBooking(List<Retreat_Booking__c> triggerNew) {
        Set<Id> propertyIds = new Set<Id>();
        Set<Date> checkInDates = new Set<Date>();
        Set<Date> checkOutDates = new Set<Date>();
        
        for (Retreat_Booking__c booking : triggerNew) {
            if (booking.Check_In_Date__c != null && booking.Check_Out_Date__c != null) {
                propertyIds.add(booking.Property__c);
                checkInDates.add(booking.Check_In_Date__c);
                checkOutDates.add(booking.Check_Out_Date__c);
            }
        }

        System.debug('checkInDates-->'+ checkInDates);
        System.debug('checkOutDates-->'+ checkOutDates);
		
        if (!checkInDates.isEmpty() && !checkOutDates.isEmpty()) {
            List<Retreat_Booking__c> existingBookings = new List<Retreat_Booking__c>([
                    SELECT Id, Check_In_Date__c, Check_Out_Date__c, Property__c, Status__c
                    FROM Retreat_Booking__c
                    WHERE Property__c = :propertyIds
                    AND ((Status__c != 'Cancelled')
                    AND((Check_In_Date__c >= :checkInDates AND Check_In_Date__c <= :checkOutDates)
                    OR (Check_Out_Date__c >= :checkInDates AND Check_Out_Date__c <= :checkOutDates)
                    OR (Check_In_Date__c <= :checkInDates AND Check_Out_Date__c >= :checkOutDates)))
            ]);
    
            for (Retreat_Booking__c booking : triggerNew) {
                if (booking.Check_In_Date__c != null && booking.Check_Out_Date__c != null) {
                    for (Retreat_Booking__c existing : existingBookings) {
                        if (booking.Property__c.equals(existing.Property__c) && ((Trigger.isUpdate && !(booking.Id.equals(existing.Id))) || Trigger.isInsert)) {
                            if (foundOverlap(existing.Check_In_Date__c, existing.Check_Out_Date__c, booking.Check_In_Date__c, booking.Check_Out_Date__c)) {
                                booking.addError('Found existing booking, Id: ' + existing.Id);
                            }
                        }
                    }
                }
            }
        }
    }

    public static Boolean foundOverlap(Date startDate, Date endDate, Date searchStartDate, Date searchEndDate) {
        if ((startDate >= searchStartDate && startDate <= searchEndDate) ||
                (endDate >= searchStartDate && endDate <= searchEndDate) ||
                (startDate <= searchStartDate && endDate >= searchEndDate)) {
            return true;
        }
        return false;
    }
}