force-app/main/default/objects/Volunteer_Compliance__c/Volunteer_Compliance__c.object-meta.xml
<CustomObject>
    <description>Used for tracking all volunteer eligibility requirements including WWC, ACF, courses and certifications.</description>
    <label>Volunteer Compliance</label>
    <nameField>
        <displayFormat>VC-{00000}</displayFormat>
        <label>Volunteer Compliance ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Volunteer Compliance</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Volunteer_Compliance__c/fields/Criteria_Type__c.field-meta.xml
<CustomField>
    <fullName>Criteria_Type__c</fullName>
    <inlineHelpText>Matches to Volunteer Criteria on volunteers portal</inlineHelpText>
    <label>Criteria Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Online Learning</fullName>
            </value>
            <value>
                <fullName>Onboarding</fullName>
            </value>
            <value>
                <fullName>Certifications</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Volunteer_Compliance__c/fields/Litmos_Course_ID__c.field-meta.xml
<CustomField>
    <fullName>Litmos_Course_ID__c</fullName>
    <inlineHelpText>The course ID in Litmos, used for the Volunteer Portal assignment.</inlineHelpText>
    <label>Litmos Course ID</label>
    <length>24</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Volunteer_Compliance__c/fields/Litmos_Course_Overdue__c.field-meta.xml
<CustomField>
    <fullName>Litmos_Course_Overdue__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>Checks against Litmos Due Date</inlineHelpText>
    <label>Litmos Course Overdue</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Volunteer_Compliance__c/fields/PercentageComplete__c.field-meta.xml
<CustomField>
    <fullName>PercentageComplete__c</fullName>
    <inlineHelpText>Pulled from Litmos</inlineHelpText>
    <label>PercentageComplete</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Volunteer_Compliance__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <inlineHelpText>Status of volunteer&apos;s compliance requirements.</inlineHelpText>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Assigned</fullName>
                <label>Not Started</label>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Active</fullName>
                <label>Completed</label>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Volunteer_Compliance__c/fields/Volunteer_Criteria__c.field-meta.xml
<CustomField>
    <fullName>Volunteer_Criteria__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Volunteer Criteria</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Volunteer_Criteria__c.Criteria_Status__c</field>
            <operation>equals</operation>
            <value>Active</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Volunteer_Criteria__c</referenceTo>
    <relationshipLabel>Volunteer Compliance</relationshipLabel>
    <relationshipName>Volunteer_Compliance</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Volunteer_Compliance__c/fields/Volunteer_Name__c.field-meta.xml
<CustomField>
    <fullName>Volunteer_Name__c</fullName>
    <label>Volunteer Name</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Volunteer Compliance</relationshipLabel>
    <relationshipName>Volunteer_Compliance</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Volunteer_Compliance__c/recordTypes/Compliance.recordType-meta.xml
<RecordType>
    <fullName>Compliance</fullName>
    <active>true</active>
    <description>For tracking volunteer compliance such as online learning, licenses, certifications and policies.</description>
    <label>Compliance</label>
</RecordType>

force-app/main/default/objects/Volunteer_Criteria__c/Volunteer_Criteria__c.object-meta.xml
<CustomObject>
    <description>Recording of all eligibility criteria for volunteers in the organisation.</description>
    <label>Volunteer Criteria</label>
    <nameField>
        <label>Volunteer Criteria Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Volunteer Criteria</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Volunteer_Criteria__c/fields/Criteria_Type__c.field-meta.xml
<CustomField>
    <fullName>Criteria_Type__c</fullName>
    <inlineHelpText>Defines where it sits on Volunteer Portal home page.</inlineHelpText>
    <label>Criteria Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Certifications</fullName>
            </value>
            <value>
                <fullName>Online Learning</fullName>
            </value>
            <value>
                <fullName>Onboarding</fullName>
            </value>
            <value>
                <fullName>License</fullName>
                <isActive>false</isActive>
                <label>License</label>
            </value>
            <value>
                <fullName>Policy</fullName>
                <isActive>false</isActive>
                <label>Policy</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Volunteer_Criteria__c/fields/Display_Order__c.field-meta.xml
<CustomField>
    <fullName>Display_Order__c</fullName>
    <inlineHelpText>Order in which it will be displayed on volunteer portal</inlineHelpText>
    <label>Display Order</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Volunteer_Criteria__c/fields/Volunteer_Criteria__c.field-meta.xml
<CustomField>
    <fullName>Volunteer_Criteria__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Criteria it was replaced by for version history.</inlineHelpText>
    <label>Replaced by:</label>
    <referenceTo>Volunteer_Criteria__c</referenceTo>
    <relationshipLabel>Volunteer Criteria</relationshipLabel>
    <relationshipName>Volunteer_Criteria</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/VolunteerComplianceProcessor.cls
/*********************************************************************************************************************************************
* @Name         VolunteerComplianceProcessor
* @Author       Amit Yadav
* @Date         21/05/2024
* @Description  The VolunteerComplianceProcessor class is a batch Apex job that processes volunteer compliance records. It queries records
                from the Volunteer_Compliance__c object, makes an HTTP callout to retrieve course completion data from an external API, 
                and updates the records with the latest completion status and details. Additionally, it implements the Schedulable interface 
                to allow scheduling the batch job

********************************************************************************************************************************************** 
MODIFICATION LOG
* Version          Developer          Date               Description
*
*  1.0             Amit Yadav         21/05/2024       Initial Creation                                                      
*********************************************************************************************************************************************/


/*The VolunteerComplianceProcessor class is a batch Apex job that processes volunteer compliance records. It queries records
from the Volunteer_Compliance__c object, makes an HTTP callout to retrieve course completion data from an external API, 
and updates the records with the latest completion status and details. Additionally, it implements the Schedulable interface 
to allow scheduling the batch job*/


public class VolunteerComplianceProcessor implements Database.Batchable<sObject>, Database.AllowsCallouts, Schedulable {
    
    public Database.QueryLocator start(Database.BatchableContext BC) {
        // collect the batches of records or objects to be passed to execute        
        String query = 'SELECT Id, Volunteer_Criteria__r.Name, Status__c, Volunteer_Criteria__r.Display_Order__c, Litmos_Course_ID__c, Criteria_Type__c, Volunteer_Name__c FROM Volunteer_Compliance__c WHERE Litmos_Course_ID__c != null AND CreatedDate > LAST_N_MONTHS:6 AND (Status__c = \'Assigned\' OR Status__c = \'In Progress\') ORDER BY Volunteer_Criteria__r.Display_Order__c ASC';
        return Database.getQueryLocator(query);
    }
    
    public void execute(Database.BatchableContext BC, List<Volunteer_Compliance__c> volList) {
        
        String baseUrl = 'callout:LitmusApiCre/users/8GNedawgiwU1/courses?source=cqportal&format=json&limit=20&start=3';
        HttpRequest req = new HttpRequest();                 
        req.setMethod('GET');
        req.setEndpoint(baseUrl);
        req.setHeader('Accept', 'application/json');
        req.setHeader('Content-Type', 'application/json');
        Http http = new Http();
        HTTPResponse res = http.send(req);
        set<String> setOfOrginalId = new set<String>();
        List<RefreshResponse> ref = (List<RefreshResponse>) System.JSON.deserialize(res.getBody(), list<RefreshResponse>.class);
        Map<String,RefreshResponse> refMap = new Map<String,RefreshResponse>();
        
        for(RefreshResponse r:ref){
            refMap.put(r.OriginalId, r);
        }
        

        for(RefreshResponse refRes : ref){
            setOfOrginalId.add(refRes.OriginalId);
        }
        // process each batch of records
        for(Volunteer_Compliance__c volCom : volList){
            if(setOfOrginalId.contains(volCom.Litmos_Course_ID__c) && refMap.get(volCom.Litmos_Course_ID__c).Complete != false ){
                volCom.PercentageComplete__c  = refMap.get(volCom.Litmos_Course_ID__c).PercentageComplete; 
                if(refMap.get(volCom.Litmos_Course_ID__c).PercentageComplete  > 0  && refMap.get(volCom.Litmos_Course_ID__c).PercentageComplete < 100){
                    volCom.Status__c  ='In Progress';
                }
                Boolean istrueComplete = refMap.get(volCom.Litmos_Course_ID__c).Complete;
                if(istrueComplete){
                    volCom.Status__c  ='Active';
                }
                volCom.Litmos_Course_Overdue__C    = refMap.get(volCom.Litmos_Course_ID__c).Overdue;
                
                // Ensure volCom.Litmos_Course_ID__c is not null and refMap contains the corresponding value
                if (volCom.Litmos_Course_ID__c != null && refMap.containsKey(volCom.Litmos_Course_ID__c)) {
                    // Get the DateCompleted value from refMap
                    String dateCompletedValue = refMap.get(volCom.Litmos_Course_ID__c).DateCompleted;
                    
                    // Check if DateCompleted is not null
                    if (dateCompletedValue != null) {
                        // Find the index of '+' in the DateCompleted value
                        Integer plusIndex = dateCompletedValue.indexOf('+');
                        
                        // Check if '+' is found
                        if (plusIndex != -1) {
                            // Extract the substring containing the timestamp
                            String timestampStr = dateCompletedValue.substring(6, plusIndex);
                            
                            // Convert the timestamp string to milliseconds
                            Long timestampMillis = Long.valueOf(timestampStr);
                            
                            // Create DateTime instance from milliseconds
                            DateTime dateTimes = DateTime.newInstance(timestampMillis);
                            
                            // Extract year, month, and day from the DateTime object
                            Integer year = dateTimes.year();
                            Integer month = dateTimes.month();
                            Integer day = dateTimes.day();
                            
                            // Create Date instance from year, month, and day
                            Date dateCompleted = Date.newInstance(year, month, day);
                            
                            // Assign the date to the Date_Completed__c field
                            volCom.Date_Completed__c = dateCompleted;
                            
                        } 
                    }
                } 
            }
        }
        try{
            update volList;
            System.debug('Data updated');
        }
        catch(Exception e){
            System.debug('Error--'+ e.getMessage());
        }        
    }   
    
    public void finish(Database.BatchableContext BC) {
        // execute any post-processing operations
    }
    
    
    //Sechdule the batch class
    public void execute(SchedulableContext sc)
    {
        VolunteerComplianceProcessor batchToExe = new VolunteerComplianceProcessor(); // Your batch class
        database.executeBatch(batchToExe , 50);
    }
    
    //Wrapper Class to to store the responce in variables
    public class RefreshResponse {
        public String Id;
        public Boolean Active;
        public Boolean Complete;
        public Double PercentageComplete;
        public String DateCompleted;
        public Boolean Overdue;
        public String OriginalId;
    }
}