force-app/main/default/objects/Account/recordTypes/Family.recordType-meta.xml
<RecordType>
    <fullName>Family</fullName>
    <active>true</active>
    <label>Family</label>
</RecordType>

force-app/main/default/objects/Contact/fields/Volunteer_Attendance__c.field-meta.xml
<CustomField>
    <fullName>Volunteer_Attendance__c</fullName>
    <label>Last Volunteer Attendance</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Contact/recordTypes/Volunteer.recordType-meta.xml
<RecordType>
    <fullName>Volunteer</fullName>
    <active>true</active>
    <label>Volunteer</label>
</RecordType>

force-app/main/default/objects/Family_Attendance__c/Family_Attendance__c.object-meta.xml
<CustomObject>
    <description>Used for recording details of families attendance on programs, linked to familiy member attendance, family guest attendance campaign member and campaign</description>
    <label>Family Attendance</label>
    <nameField>
        <displayFormat>FA{00000}</displayFormat>
        <label>Family Attendance</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Family Attendances</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Family_Attendance__c/fields/Event__c.field-meta.xml
<CustomField>
    <fullName>Event__c</fullName>
    <label>Event</label>
    <referenceTo>Campaign</referenceTo>
    <relationshipLabel>Family Attendances</relationshipLabel>
    <relationshipName>Family_Attendances</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Family_Attendance__c/fields/FA_00000__c.field-meta.xml
<CustomField>
    <fullName>FA_00000__c</fullName>
    <label>Attendance</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Invited</fullName>
            </value>
            <value>
                <fullName>Request to Attend</fullName>
            </value>
            <value>
                <fullName>Accepted</fullName>
            </value>
            <value>
                <fullName>Attended</fullName>
            </value>
            <value>
                <fullName>Declined</fullName>
            </value>
            <value>
                <fullName>Unsuccessful</fullName>
            </value>
            <value>
                <fullName>-1</fullName>
            </value>
            <value>
                <fullName>No Show</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Cancelled &lt; 24 hours</fullName>
            </value>
            <value>
                <fullName>Medical Withdrawal</fullName>
            </value>
            <value>
                <fullName>Unsuccessful – Waitlist</fullName>
            </value>
            <value>
                <fullName>Unsuccessful – Declined</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Family_Attendance__c/fields/Family__c.field-meta.xml
<CustomField>
    <fullName>Family__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Family</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Family Attendances</relationshipLabel>
    <relationshipName>Family_Attendances</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Family_Member_Attendance__c/Family_Member_Attendance__c.object-meta.xml
<CustomObject>
    <description>Used for recording individual family member attendances on programs linked to family attendance</description>
    <label>Family Member Attendance</label>
    <nameField>
        <displayFormat>FMA{00000}</displayFormat>
        <label>Family Member Attendance</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Family Member Attendance</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Family_Member_Attendance__c/fields/Attendance__c.field-meta.xml
<CustomField>
    <fullName>Attendance__c</fullName>
    <label>Attendance</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Invited</fullName>
            </value>
            <value>
                <fullName>Request to Attend</fullName>
            </value>
            <value>
                <fullName>Accepted</fullName>
            </value>
            <value>
                <fullName>Attended</fullName>
            </value>
            <value>
                <fullName>Declined</fullName>
            </value>
            <value>
                <fullName>Unsuccessful</fullName>
            </value>
            <value>
                <fullName>No Show</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Cancelled &lt; 24 hours</fullName>
            </value>
            <value>
                <fullName>Medical Withdrawal</fullName>
            </value>
            <value>
                <fullName>Unsuccessful – Waitlist</fullName>
            </value>
            <value>
                <fullName>Unsuccessful – Declined</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Family_Member_Attendance__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Family Member Attendance</relationshipLabel>
    <relationshipName>Family_Member_Attendance</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Family_Member_Attendance__c/fields/Event__c.field-meta.xml
<CustomField>
    <fullName>Event__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Event</label>
    <referenceTo>Campaign</referenceTo>
    <relationshipLabel>Family Member Attendance</relationshipLabel>
    <relationshipName>Family_Member_Attendance</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Family_Member_Attendance__c/fields/Family_Attendance__c.field-meta.xml
<CustomField>
    <fullName>Family_Attendance__c</fullName>
    <label>Family Attendance</label>
    <referenceTo>Family_Attendance__c</referenceTo>
    <relationshipLabel>Family Member Attendance</relationshipLabel>
    <relationshipName>Family_Member_Attendance</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Transport__c/Transport__c.object-meta.xml
<CustomObject>
    <description>Transport Object - Deprecated</description>
    <label>Transport</label>
    <nameField>
        <label>Transport Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Transports</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Transport__c/fields/Event__c.field-meta.xml
<CustomField>
    <fullName>Event__c</fullName>
    <label>Event</label>
    <referenceTo>Campaign</referenceTo>
    <relationshipLabel>Transports</relationshipLabel>
    <relationshipName>Transports</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Transport_Participant__c/Transport_Participant__c.object-meta.xml
<CustomObject>
    <description>Transport Object - Deprecated</description>
    <label>Transport Participant</label>
    <nameField>
        <displayFormat>TP{00000}</displayFormat>
        <label>Transport Participant Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Transport Participants</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Transport_Participant__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Transport Participants</relationshipLabel>
    <relationshipName>Transport_Participants</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Transport_Participant__c/fields/Dropped_Off__c.field-meta.xml
<CustomField>
    <fullName>Dropped_Off__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Dropped Off</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Transport_Participant__c/fields/Family_Member_Attendance__c.field-meta.xml
<CustomField>
    <fullName>Family_Member_Attendance__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Family Member Attendance</label>
    <referenceTo>Family_Member_Attendance__c</referenceTo>
    <relationshipLabel>Transport Participants</relationshipLabel>
    <relationshipName>Transport_Participants</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Transport_Participant__c/fields/Participant_Type__c.field-meta.xml
<CustomField>
    <fullName>Participant_Type__c</fullName>
    <label>Participant Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Family Member</fullName>
            </value>
            <value>
                <fullName>Volunteer</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Transport_Participant__c/fields/Picked_Up__c.field-meta.xml
<CustomField>
    <fullName>Picked_Up__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Picked Up</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Transport_Participant__c/fields/Transport__c.field-meta.xml
<CustomField>
    <fullName>Transport__c</fullName>
    <label>Transport</label>
    <referenceTo>Transport__c</referenceTo>
    <relationshipLabel>Transport Participants</relationshipLabel>
    <relationshipName>Transport_Participants</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Transport_Participant__c/fields/Volunteer_Attendance__c.field-meta.xml
<CustomField>
    <fullName>Volunteer_Attendance__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Volunteer Attendance</label>
    <referenceTo>Volunteer_Attendance__c</referenceTo>
    <relationshipLabel>Transport Participants</relationshipLabel>
    <relationshipName>Transport_Participants</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Volunteer_Attendance__c/Volunteer_Attendance__c.object-meta.xml
<CustomObject>
    <description>Used for tracking volunteer attendance on programs. Linked to campaign member for communication, campaign for program, contact for volunteer</description>
    <label>Volunteer Attendance</label>
    <nameField>
        <displayFormat>VA{00000}</displayFormat>
        <label>Volunteer Attendance</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Volunteer Attendances</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Volunteer_Attendance__c/fields/Attendance__c.field-meta.xml
<CustomField>
    <fullName>Attendance__c</fullName>
    <label>Attendance</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Invited</fullName>
            </value>
            <value>
                <fullName>Request to Attend</fullName>
            </value>
            <value>
                <fullName>Accepted</fullName>
            </value>
            <value>
                <fullName>Attended</fullName>
            </value>
            <value>
                <fullName>Declined</fullName>
            </value>
            <value>
                <fullName>Unsuccessful</fullName>
            </value>
            <value>
                <fullName>No Show</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Medical Withdrawal</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Volunteer_Attendance__c/fields/Event__c.field-meta.xml
<CustomField>
    <fullName>Event__c</fullName>
    <label>Event</label>
    <referenceTo>Campaign</referenceTo>
    <relationshipLabel>Volunteer Attendances</relationshipLabel>
    <relationshipName>Volunteer_Attendances</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Volunteer_Attendance__c/fields/Volunteer__c.field-meta.xml
<CustomField>
    <fullName>Volunteer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Volunteer</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Volunteer Attendances</relationshipLabel>
    <relationshipName>Volunteer_Attendances</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Volunteer_Attendance__c/fields/Volunteer_Rating__c.field-meta.xml
<CustomField>
    <fullName>Volunteer_Rating__c</fullName>
    <label>Volunteer Rating</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Standout Volunteer</fullName>
            </value>
            <value>
                <fullName>Good Fit</fullName>
            </value>
            <value>
                <fullName>Still Settling In</fullName>
            </value>
            <value>
                <fullName>Needs Further Support/Training</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/MarkAttendanceController.cls
public class MarkAttendanceController {
    
    public Id camId {get;set;}
    public Map<Id, Family_Attendance__c> fas{get;set;}
    public Map<Id, Volunteer_Attendance__c> vas{get;set;}
    public Map<Id, Family_Member_Attendance__c> fmas{get;set;}
  //  public Map<Id, Transport_Participant__c> tps{get;set;}
	    
    public Map<Id, Boolean> faAttendeds{get;set;}
    public Map<Id, Boolean> fmaAttendeds{get;set;}
    //public Map<Id, Boolean> tpAttendeds{get;set;}
    public Map<Id, Boolean> vaAttendeds{get;set;}
    public Map<Id, String> vaRating{get;set;}

    public String attendanceType{get;set;}
    
    public String markBy{get;set;}
    
    public MarkAttendanceController(ApexPages.StandardController sc) {
        
        camId = sc.getId();
        
        setAttendeds();
        markBy = 'Family';
        attendanceType = 'Attendance';
        
    }

    public Id attendId{get;set;}
    
    public List<SelectOption> getListOfRatings() {
		Schema.DescribeFieldResult RatingsFieldDesc = Volunteer_Attendance__c.Volunteer_Rating__c.getDescribe();
        List<SelectOption> RatingsList = new List<SelectOption>();

		for (Schema.Picklistentry picklistEntry : RatingsFieldDesc.getPicklistValues())
		{
			RatingsList.add(new SelectOption(pickListEntry.getValue(),pickListEntry.getLabel()));
		}
        return RatingsList;
    }
    
        public void markVolunteerRating() {
			
            if(attendanceType == 'Attendance' && vas != null && vas.containsKey(attendId)) {

            	Volunteer_Attendance__c va = vas.get(attendId);
            	System.debug('attendanceType: ' + attendanceType);
            
                va.Volunteer_Rating__c = vaRating.get(attendId);
                //va.Volunteer_Rating__c = 'Still Settling In';
                System.debug('va: ' + va);
                
                try {
                    update va;
                } catch(DmlException ex) {
                    System.debug(ex);
                    ApexPages.addMessages(ex);
                }
        
            
        	}
        }
        public void markAttended() {
        
        System.debug('markBy: ' + markBy);
        System.debug('attendId: ' + attendId);
        
        
        if(markBy == 'Family' && fas != null && fas.containsKey(attendId)) {
            
			Family_Attendance__c fa = fas.get(attendId);
            fa.FA_00000__c = faAttendeds.get(attendId) ? 'Attended' : 'Accepted';
            
            try {
                update fa;
            } catch(DmlException ex) {
                System.debug(ex);
                ApexPages.addMessages(ex);
            }
            
        } else if(attendanceType == 'Attendance' && fmas != null && fmas.containsKey(attendId)) {
            
            Family_Member_Attendance__c fma = fmas.get(attendId);
            
            System.debug('attendanceType: ' + attendanceType);
            
            if(attendanceType == 'Attendance') {
                fma.Attendance__c = fmaAttendeds.get(attendId) ? 'Attended' : 'Accepted';
            }
            
            System.debug('fma: ' + fma);
            
            try {
                update fma;
            } catch(DmlException ex) {
                System.debug(ex);
                ApexPages.addMessages(ex);
            }
            
        } else if(attendanceType == 'Attendance' && vas != null && vas.containsKey(attendId)) {

            Volunteer_Attendance__c va = vas.get(attendId);
            
            System.debug('attendanceType: ' + attendanceType);
            
            if(attendanceType == 'Attendance') {
                va.Attendance__c = vaAttendeds.get(attendId) ? 'Attended' : 'Accepted';
            }
            
            System.debug('va: ' + va);
            
            try {
                update va;
            } catch(DmlException ex) {
                System.debug(ex);
                ApexPages.addMessages(ex);
            }

        } 
            /*else if(tps != null && tps.containsKey(attendId)) {
            
            Transport_Participant__c tp = tps.get(attendId);
            
            System.debug('attendanceType: ' + attendanceType);
            
            if(attendanceType == 'Transport Pick Up') {
                tp.Picked_Up__c = tpAttendeds.get(attendId);
            } else if(attendanceType == 'Transport Drop Off') {
                tp.Dropped_Off__c = tpAttendeds.get(attendId);
            }
            
            try {
                update tp;
            } catch(DmlException ex) {
                System.debug(ex);
                ApexPages.addMessages(ex);
            }
            
        }*/
        
    }
    
    public void setAttendeds() {
        
		loadFamilies();
        faAttendeds = new Map<Id, Boolean>();
        fmaAttendeds = new Map<Id, Boolean>();
        //tpAttendeds = new Map<Id, Boolean>();
        vaAttendeds = new Map<Id, Boolean>();
        vaRating = new Map<Id, String>();
        
        if(fas != null) {
            for(Id key : fas.keySet()) {
                faAttendeds.put(key, fas.get(key).FA_00000__c == 'Attended');
            }
        }
        
        if(fmas != null) {
            for(Id key : fmas.keySet()) {
                fmaAttendeds.put(key, fmas.get(key).Attendance__c == 'Attended');            
            }
        }
        
        /*if(tps != null) {
            for(Id key : tps.keySet()) {
                if(attendanceType == 'Transport Pick Up') {
                    tpAttendeds.put(key, tps.get(key).Picked_Up__c);
                } else if(attendanceType == 'Transport Drop Off') {
                    tpAttendeds.put(key, tps.get(key).Dropped_Off__c);
                }
            }
        }*/

        if(vas != null) {
            for(Id key : vas.keySet()) {
                vaAttendeds.put(key, vas.get(key).Attendance__c == 'Attended');
                if (vas.get(key).Volunteer_Rating__c != null) {
                	vaRating.put(key, vas.get(key).Volunteer_Rating__c);    
                }
                else{
                    vaRating.put(key, 'Good Fit');
                }
            }
        }
        
    }
    
    private void loadFamilies() {

        if(markBy == 'Family Member' && attendanceType == 'Attendance') {
            fmas = new Map<Id, Family_Member_Attendance__c>([SELECT Id, Attendance__c, Contact__r.FirstName, Contact__r.LastName, Contact__r.MailingStreet, Contact__r.MailingCity, Contact__r.MailingState, Contact__r.MailingPostalCode FROM Family_Member_Attendance__c WHERE Family_Attendance__r.Event__c = :camId AND (Attendance__c = 'Accepted' OR Attendance__c = 'Attended')]);
        } 
        //else if(attendanceType == 'Transport Pick Up' || attendanceType == 'Transport Drop Off') {
          //  tps = new Map<Id, Transport_Participant__c>([SELECT Id, Picked_Up__c, Dropped_Off__c, Contact__c, Contact__r.FirstName, Contact__r.LastName, Contact__r.MailingStreet, Contact__r.MailingCity, Contact__r.MailingState, Contact__r.MailingPostalCode, Participant_Type__c FROM Transport_Participant__c WHERE Transport__r.Event__c = :camId]);
    //    }
    else if(markBy == 'Volunteer' && attendanceType == 'Attendance') {
            vas = new Map<Id, Volunteer_Attendance__c>([SELECT Id, Attendance__c, Volunteer__r.FirstName, Volunteer__r.LastName, Volunteer__r.MailingStreet, Volunteer__r.MailingCity, Volunteer__r.MailingState, Volunteer__r.MailingPostalCode, Volunteer_Rating__c FROM Volunteer_Attendance__c WHERE Event__c = :camId AND (Attendance__c = 'Accepted' OR Attendance__c = 'Attended')]);
        } else {
            fas = new Map<Id, Family_Attendance__c>([SELECT Id, FA_00000__c, Family__r.Name, Family__r.BillingStreet, Family__r.BillingCity, Family__r.BillingState, Family__r.BillingPostalCode, (SELECT Id, Contact__r.FirstName FROM Family_Member_Attendance__r) FROM Family_Attendance__c WHERE Event__c = :camId AND (FA_00000__c = 'Accepted' OR FA_00000__c = 'Attended')]);
        }

    }
        
}