force-app/main/default/objects/Account/recordTypes/Family.recordType-meta.xml
<RecordType>
    <fullName>Family</fullName>
    <active>true</active>
    <label>Family</label>
</RecordType>

force-app/main/default/objects/Family_Attendance__c/Family_Attendance__c.object-meta.xml
<CustomObject>
    <description>Used for recording details of families attendance on programs, linked to familiy member attendance, family guest attendance campaign member and campaign</description>
    <label>Family Attendance</label>
    <nameField>
        <displayFormat>FA{00000}</displayFormat>
        <label>Family Attendance</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Family Attendances</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Family_Attendance__c/fields/Consent__c.field-meta.xml
<CustomField>
    <fullName>Consent__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Consent</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Family_Attendance__c/fields/Event__c.field-meta.xml
<CustomField>
    <fullName>Event__c</fullName>
    <label>Event</label>
    <referenceTo>Campaign</referenceTo>
    <relationshipLabel>Family Attendances</relationshipLabel>
    <relationshipName>Family_Attendances</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Family_Attendance__c/fields/FA_00000__c.field-meta.xml
<CustomField>
    <fullName>FA_00000__c</fullName>
    <label>Attendance</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Invited</fullName>
            </value>
            <value>
                <fullName>Request to Attend</fullName>
            </value>
            <value>
                <fullName>Accepted</fullName>
            </value>
            <value>
                <fullName>Attended</fullName>
            </value>
            <value>
                <fullName>Declined</fullName>
            </value>
            <value>
                <fullName>Unsuccessful</fullName>
            </value>
            <value>
                <fullName>-1</fullName>
            </value>
            <value>
                <fullName>No Show</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Cancelled &lt; 24 hours</fullName>
            </value>
            <value>
                <fullName>Medical Withdrawal</fullName>
            </value>
            <value>
                <fullName>Unsuccessful – Waitlist</fullName>
            </value>
            <value>
                <fullName>Unsuccessful – Declined</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Family_Attendance__c/fields/Family__c.field-meta.xml
<CustomField>
    <fullName>Family__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Family</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Family Attendances</relationshipLabel>
    <relationshipName>Family_Attendances</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/FamilyAttendanceTest.cls
@isTest
public with sharing class FamilyAttendanceTest {

    
    @TestSetup
    static void makeData(){
        // Create a test family
        Account testFamily = new Account(Name='Test Family');
        insert testFamily;

        // Create a test student
        Contact testStudent = new Contact(LastName='Test Student', AccountId=testFamily.Id);
        insert testStudent;
 
        //create a campaign record for the event
        Campaign testCampaign = new Campaign(Name='Test Campaign', StartDate=Date.today(), EndDate=Date.today(), Type='Event');
        insert testCampaign;

        // Create a test family attendance record
        Family_Attendance__c testFamilyAttendance = new Family_Attendance__c(Family__c=testFamily.Id, Event__c=testCampaign.Id, Consent__c=true);
        testFamilyAttendance.FA_00000__c = 'Declined';
        insert testFamilyAttendance;
        
    }

    @isTest
    static void testFamilyAttendanceDelete() { 

        Family_Attendance__c testFamilyAttendance = [SELECT Consent__c, FA_00000__c FROM Family_Attendance__c ];

        // Test that the family attendance record was deleted
        delete testFamilyAttendance;
        System.assertEquals(0, [SELECT Id FROM Family_Attendance__c ].size());
    }

    @isTest
    static void testFamilyAttendanceUpdate() {  
        // Test that the family attendance record was updated
        Family_Attendance__c testFamilyAttendance = [SELECT Consent__c, FA_00000__c FROM Family_Attendance__c ];
        testFamilyAttendance.Consent__c = false;
        testFamilyAttendance.FA_00000__c = 'Attended';
        update testFamilyAttendance;

        System.assertEquals('Attended', [SELECT Consent__c, FA_00000__c FROM Family_Attendance__c ].FA_00000__c);

        
    }
}