force-app/main/default/objects/Account/recordTypes/Family.recordType-meta.xml
<RecordType>
    <fullName>Family</fullName>
    <active>true</active>
    <label>Family</label>
</RecordType>

force-app/main/default/objects/Campaign/fields/Family_Member_Attendance__c.field-meta.xml
<CustomField>
    <fullName>Family_Member_Attendance__c</fullName>
    <label>Family Member Attendance</label>
    <summarizedField>Family_Attendance__c.Attended_Members__c</summarizedField>
    <summaryForeignKey>Family_Attendance__c.Event__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Campaign/recordTypes/Volunteer.recordType-meta.xml
<RecordType>
    <fullName>Volunteer</fullName>
    <active>true</active>
    <label>Volunteer</label>
</RecordType>

force-app/main/default/objects/Contact/recordTypes/Volunteer.recordType-meta.xml
<RecordType>
    <fullName>Volunteer</fullName>
    <active>true</active>
    <label>Volunteer</label>
</RecordType>

force-app/main/default/objects/Family_Attendance__c/Family_Attendance__c.object-meta.xml
<CustomObject>
    <description>Used for recording details of families attendance on programs, linked to familiy member attendance, family guest attendance campaign member and campaign</description>
    <label>Family Attendance</label>
    <nameField>
        <displayFormat>FA{00000}</displayFormat>
        <label>Family Attendance</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Family Attendances</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Family_Attendance__c/fields/Event__c.field-meta.xml
<CustomField>
    <fullName>Event__c</fullName>
    <label>Event</label>
    <referenceTo>Campaign</referenceTo>
    <relationshipLabel>Family Attendances</relationshipLabel>
    <relationshipName>Family_Attendances</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Family_Attendance__c/fields/FA_00000__c.field-meta.xml
<CustomField>
    <fullName>FA_00000__c</fullName>
    <label>Attendance</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Invited</fullName>
            </value>
            <value>
                <fullName>Request to Attend</fullName>
            </value>
            <value>
                <fullName>Accepted</fullName>
            </value>
            <value>
                <fullName>Attended</fullName>
            </value>
            <value>
                <fullName>Declined</fullName>
            </value>
            <value>
                <fullName>Unsuccessful</fullName>
            </value>
            <value>
                <fullName>-1</fullName>
            </value>
            <value>
                <fullName>No Show</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Cancelled &lt; 24 hours</fullName>
            </value>
            <value>
                <fullName>Medical Withdrawal</fullName>
            </value>
            <value>
                <fullName>Unsuccessful – Waitlist</fullName>
            </value>
            <value>
                <fullName>Unsuccessful – Declined</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Family_Attendance__c/fields/Family__c.field-meta.xml
<CustomField>
    <fullName>Family__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Family</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Family Attendances</relationshipLabel>
    <relationshipName>Family_Attendances</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Family_Member_Attendance__c/Family_Member_Attendance__c.object-meta.xml
<CustomObject>
    <description>Used for recording individual family member attendances on programs linked to family attendance</description>
    <label>Family Member Attendance</label>
    <nameField>
        <displayFormat>FMA{00000}</displayFormat>
        <label>Family Member Attendance</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Family Member Attendance</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Family_Member_Attendance__c/fields/Attendance__c.field-meta.xml
<CustomField>
    <fullName>Attendance__c</fullName>
    <label>Attendance</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Invited</fullName>
            </value>
            <value>
                <fullName>Request to Attend</fullName>
            </value>
            <value>
                <fullName>Accepted</fullName>
            </value>
            <value>
                <fullName>Attended</fullName>
            </value>
            <value>
                <fullName>Declined</fullName>
            </value>
            <value>
                <fullName>Unsuccessful</fullName>
            </value>
            <value>
                <fullName>No Show</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Cancelled &lt; 24 hours</fullName>
            </value>
            <value>
                <fullName>Medical Withdrawal</fullName>
            </value>
            <value>
                <fullName>Unsuccessful – Waitlist</fullName>
            </value>
            <value>
                <fullName>Unsuccessful – Declined</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Family_Member_Attendance__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Family Member Attendance</relationshipLabel>
    <relationshipName>Family_Member_Attendance</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Family_Member_Attendance__c/fields/Event__c.field-meta.xml
<CustomField>
    <fullName>Event__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Event</label>
    <referenceTo>Campaign</referenceTo>
    <relationshipLabel>Family Member Attendance</relationshipLabel>
    <relationshipName>Family_Member_Attendance</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Family_Member_Attendance__c/fields/Family_Attendance__c.field-meta.xml
<CustomField>
    <fullName>Family_Attendance__c</fullName>
    <label>Family Attendance</label>
    <referenceTo>Family_Attendance__c</referenceTo>
    <relationshipLabel>Family Member Attendance</relationshipLabel>
    <relationshipName>Family_Member_Attendance</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Page__c/Page__c.object-meta.xml
<CustomObject>
    <description>Used to create portal pages in the programs Salesforce community</description>
    <label>Page</label>
    <nameField>
        <label>Page Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Pages</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Page__c/fields/Site__c.field-meta.xml
<CustomField>
    <fullName>Site__c</fullName>
    <label>Site</label>
    <referenceTo>Site__c</referenceTo>
    <relationshipLabel>Pages</relationshipLabel>
    <relationshipName>Pages</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Site__c/Site__c.object-meta.xml
<CustomObject>
    <description>Portal custom object for the different views/subsites on portal i.e. Family Volunteer Corporate Volunteer</description>
    <label>Site</label>
    <nameField>
        <label>Site Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sites</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Special_Needs__c/Special_Needs__c.object-meta.xml
<CustomObject>
    <label>Dietary &amp; Special Needs</label>
    <nameField>
        <displayFormat>SN - {0000}</displayFormat>
        <label>Special Needs Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Dietary &amp; Special Needs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Special_Needs__c/fields/AttributeType__c.field-meta.xml
<CustomField>
    <fullName>AttributeType__c</fullName>
    <label>Attribute Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>DietryNeeds</fullName>
                <label>Dietary Needs</label>
            </value>
            <value>
                <fullName>SpecialNeeds</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Special_Needs__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipName>Special_Needs</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Special_Needs__c/fields/Long_Description__c.field-meta.xml
<CustomField>
    <fullName>Long_Description__c</fullName>
    <label>Long Description</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>ADD</fullName>
            </value>
            <value>
                <fullName>ADHD</fullName>
            </value>
            <value>
                <fullName>Allergic - All Nuts</fullName>
            </value>
            <value>
                <fullName>Allergic - Buckwheat</fullName>
            </value>
            <value>
                <fullName>Allergic - Eggs</fullName>
            </value>
            <value>
                <fullName>Allergic - Fish</fullName>
            </value>
            <value>
                <fullName>Allergic - Garlic</fullName>
            </value>
            <value>
                <fullName>Allergic - Kiwi Fruit</fullName>
            </value>
            <value>
                <fullName>Allergic - Mushrooms</fullName>
            </value>
            <value>
                <fullName>Allergic - Oranges</fullName>
            </value>
            <value>
                <fullName>Allergic - Other</fullName>
            </value>
            <value>
                <fullName>Allergic - Parmesan Cheese</fullName>
            </value>
            <value>
                <fullName>Allergic - Peanuts</fullName>
            </value>
            <value>
                <fullName>Allergic - Pork</fullName>
            </value>
            <value>
                <fullName>Allergic - Prawns</fullName>
            </value>
            <value>
                <fullName>Allergic - Seafood</fullName>
            </value>
            <value>
                <fullName>Allergic - Sesame</fullName>
            </value>
            <value>
                <fullName>Allergic - Shellfish</fullName>
            </value>
            <value>
                <fullName>Allergic - Tomatoes</fullName>
            </value>
            <value>
                <fullName>Allergic - Yeast</fullName>
            </value>
            <value>
                <fullName>Allergic to dust mites</fullName>
            </value>
            <value>
                <fullName>Allergy - Angel Cream</fullName>
            </value>
            <value>
                <fullName>Allergy - Antibiotic Erythromycin</fullName>
            </value>
            <value>
                <fullName>Allergy - Asparaginase</fullName>
            </value>
            <value>
                <fullName>Allergy - Asprin</fullName>
            </value>
            <value>
                <fullName>Allergy - Bactrim</fullName>
            </value>
            <value>
                <fullName>Allergy - Band Aids</fullName>
            </value>
            <value>
                <fullName>Allergy - Bee Stings</fullName>
            </value>
            <value>
                <fullName>Allergy - Bleomycin</fullName>
            </value>
            <value>
                <fullName>Allergy - Brietal</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Volunteer_Type__c/Volunteer_Type__c.object-meta.xml
<CustomObject>
    <description>Used for recording types of volunteer a volunteer can do.  I.e. Rover, Companion, Camp Leader, Medical</description>
    <label>Volunteer Type</label>
    <nameField>
        <displayFormat>VT-{0000}</displayFormat>
        <label>Volunteer Type Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Volunteers Type</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Volunteer_Type__c/fields/Volunteer_Type__c.field-meta.xml
<CustomField>
    <fullName>Volunteer_Type__c</fullName>
    <label>Volunteer Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Volunteer_Types</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/classes/portalEditProfileControllerTest.cls
@isTest
private class portalEditProfileControllerTest {
     
    @isTest static void familyProfile() {
        User u = [SELECT ID FROM User Where alias = 'test123'];

        List<Special_Needs__c> lstSpecialNeeds = [SELECT ID FROM Special_Needs__c]; 
        System.assertEquals(2, lstSpecialNeeds.size());

        system.runAs(u) {

            portalEditProfileController pepc = new portalEditProfileController(); 

            pepc.editFamily();
            pepc.saveFamily();
            pepc.cancelFamily();

            Contact c = portalCore.userContact;

            pepc.editContactId = c.Id;

            pepc.editContact();

            pepc.addType = 'DietryNeeds';
            pepc.addSpecialNeed();

            pepc.saveContact();
            pepc.editContact();

            for(String key : pepc.currentNeeds.keySet()) {
                pepc.removeNeedId = key;
                pepc.removeSpecialNeed();
            }

            pepc.saveContact();
            pepc.cancelContact();

            pepc.editContact();

        }
        lstSpecialNeeds = [SELECT ID FROM Special_Needs__c]; 
        System.assertEquals(2, lstSpecialNeeds.size()); 

    }
    
    @isTest static void volunteerProfile() { 

        User u = [SELECT ID FROM User Where alias = 'test123']; 
        List<Special_Needs__c> lstSpecialNeeds = [SELECT ID FROM Special_Needs__c]; 
        System.assertEquals(2, lstSpecialNeeds.size());

        system.runAs(u) {

            portalEditVolunteerProfileController pepc = new portalEditVolunteerProfileController();

            pepc.editContact();

            pepc.addType = 'DietryNeeds';
            pepc.addSpecialNeed();

            pepc.wwc.Skill_Description__c = 'Description';

            pepc.saveContact();
            pepc.cancelContact();

            for(String key : pepc.currentNeeds.keySet()) {
                pepc.removeNeedId = key;
                pepc.removeSpecialNeed();
            }
            
            System.assertEquals(null, pepc.profileImage);

            pepc.newVType.Volunteer_Type__c = 'Volunteer Type';

            pepc.addVolunteerType();

            for(String key : pepc.vTypes.keySet()) {
                pepc.removeVTypeId = key;
                pepc.removeVolunteerType();
            } 
        }

        lstSpecialNeeds = [SELECT ID FROM Special_Needs__c]; 
        System.assertEquals(2, lstSpecialNeeds.size());

    }
    
    @testSetup static void SetupTests() {

        User uContext = TestClassUtil.createStdPortalTestUser();  
        Account a = [SELECT ID FROM Account];
        
        Campaign cmp = new Campaign(Name = 'Campaign Name', Status = 'Planned', isActive = true);

        insert cmp;

        Family_Attendance__c fa = new Family_Attendance__c(Family__c = a.Id, Event__c = cmp.Id, FA_00000__c = 'Request to Attend');

        insert fa;

        Family_Member_Attendance__c fma = new Family_Member_Attendance__c(Event__c = cmp.Id, Attendance__c = 'Request to Attend', 
        Family_Attendance__c = fa.Id, Contact__c = uContext.ContactId);

        insert fma;

        Special_Needs__c sn = new Special_Needs__c(AttributeType__c = 'DietryNeeds', Contact__c = uContext.ContactId, Long_Description__c = 'Allergic - Garlic');

        insert sn;

        Special_Needs__c sn2 = new Special_Needs__c(AttributeType__c = 'SpecialNeeds', Contact__c = uContext.ContactId, Long_Description__c = 'Allergic - Garlic');

        insert sn2;

        Site__c site = new Site__c(Name = 'Family Portal');

        insert site;

        Page__c page = new Page__c(Name = 'My Events', Site__c = site.Id);

        insert page; 
    }

}