force-app/main/default/objects/Account/recordTypes/HH_Account.recordType-meta.xml
<RecordType>
    <fullName>HH_Account</fullName>
    <active>false</active>
    <description>An Account representing a Household containing one or more individuals</description>
    <label>Household Account</label>
</RecordType>

force-app/main/default/objects/CampaignMember/fields/Campaign_Member_External_ID__c.field-meta.xml
<CustomField>
    <fullName>Campaign_Member_External_ID__c</fullName>
    <description>Contact External id + Event External Id</description>
    <externalId>true</externalId>
    <label>Campaign Member External ID</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/CampaignMember/fields/Participation__c.field-meta.xml
<CustomField>
    <fullName>Participation__c</fullName>
    <label>Participation</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Mapping_Definition_Name__c.field-meta.xml
<CustomField>
    <fullName>Mapping_Definition_Name__c</fullName>
    <defaultValue>if ( $RecordType.DeveloperName  = &quot;Family_Application&quot;,&quot;FamilyApplication&quot;,&quot;VolunteerApplication&quot;)</defaultValue>
    <label>Mapping Definition Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Mapping_Field__c/Mapping_Field__c.object-meta.xml
<CustomObject>
    <label>Mapping Field</label>
    <nameField>
        <displayFormat>MFID-{00000}</displayFormat>
        <label>Mapping Field Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Mapping Fields</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Mapping_Field__c/fields/Mapping_Object__c.field-meta.xml
<CustomField>
    <fullName>Mapping_Object__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Mapping Object</label>
    <referenceTo>Mapping_Object__c</referenceTo>
    <relationshipLabel>Mapping Fields</relationshipLabel>
    <relationshipName>Mapping_Fields</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Mapping_Field__c/fields/Mapping_Reference__c.field-meta.xml
<CustomField>
    <fullName>Mapping_Reference__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Mapping Reference</label>
    <referenceTo>Mapping_Reference__c</referenceTo>
    <relationshipLabel>Mapping Fields</relationshipLabel>
    <relationshipName>Mapping_Fields</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Mapping_Field__c/fields/Source_Fields__c.field-meta.xml
<CustomField>
    <fullName>Source_Fields__c</fullName>
    <label>Source Fields</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Mapping_Object__c/Mapping_Object__c.object-meta.xml
<CustomObject>
    <label>Mapping Object</label>
    <nameField>
        <label>Mapping Object Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Mapping Objects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Mapping_Object__c/fields/Definition__c.field-meta.xml
<CustomField>
    <fullName>Definition__c</fullName>
    <label>Definition</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Mapping_Reference__c/Mapping_Reference__c.object-meta.xml
<CustomObject>
    <label>Mapping Reference</label>
    <nameField>
        <label>Mapping Reference Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Mapping References</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Mapping_Reference__c/fields/Defined_Object__c.field-meta.xml
<CustomField>
    <fullName>Defined_Object__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Defined Object</label>
    <referenceTo>Mapping_Object__c</referenceTo>
    <relationshipLabel>Mapping References (Defined Object)</relationshipLabel>
    <relationshipName>Mapping_References1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Mapping_Reference__c/fields/Id_ExtId_Value__c.field-meta.xml
<CustomField>
    <fullName>Id_ExtId_Value__c</fullName>
    <label>Id / ExtId Value</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Mapping_Reference__c/fields/Mapping_Object__c.field-meta.xml
<CustomField>
    <fullName>Mapping_Object__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Mapping Object</label>
    <referenceTo>Mapping_Object__c</referenceTo>
    <relationshipLabel>Mapping References</relationshipLabel>
    <relationshipName>Mapping_References</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Mapping_Reference__c/fields/Reference_Field_API_Name__c.field-meta.xml
<CustomField>
    <fullName>Reference_Field_API_Name__c</fullName>
    <label>Reference Field API Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Mapping_Reference__c/fields/Reference_Type__c.field-meta.xml
<CustomField>
    <fullName>Reference_Type__c</fullName>
    <label>Reference Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>SObject Definition</fullName>
            </value>
            <value>
                <fullName>External Id Value</fullName>
            </value>
            <value>
                <fullName>Id Value</fullName>
            </value>
            <value>
                <fullName>Join Object</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Mapping_Reference__c/fields/Referenced_Object_API_Name__c.field-meta.xml
<CustomField>
    <fullName>Referenced_Object_API_Name__c</fullName>
    <label>Referenced Object API Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Mapping_Reference__c/fields/Referenced_Object_ExtId_API_Name__c.field-meta.xml
<CustomField>
    <fullName>Referenced_Object_ExtId_API_Name__c</fullName>
    <label>Referenced Object ExtId API Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Mapping_Reference__c/fields/Upsert_Field_API_Name__c.field-meta.xml
<CustomField>
    <fullName>Upsert_Field_API_Name__c</fullName>
    <label>Upsert Field API Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/ProcessLeadMappingTest.cls
@isTest
private class ProcessLeadMappingTest {
    public static testMethod void testProcess() {
        Lead l = createTestData();

        Test.startTest();
        
        String ret = ProcessLeadMapping.ProcessLead(l.Id);
        
        System.debug(LoggingLevel.DEBUG, ret);

        Test.stopTest();
    }

    public static testMethod void testReferenceBatchContext() {
        Lead l = createTestData();

        Test.startTest();

        LeadMappingDataBatch lmdb = new LeadMappingDataBatch(l.Id);
        lmdb.processRecords(Database.query(lmdb.query));

        Database.executeBatch(new LeadMappingRefBatch(lmdb.theLead, lmdb.theLead.Mapping_Definition_Name__c, lmdb.objMap), 200);

        Test.stopTest();
    }
    
    public static testMethod void testButtonController() {
        
        Lead l = new Lead(FirstName='John', LastName='Doe', Email='john@doe.org', Company='Test Account', LeadSource='Advertisement', Status='New', Mapping_Definition_Name__c='Test Def');
        insert l;
        
        Mapping_Object__c conMap = new Mapping_Object__c(
            Definition__c=l.Mapping_Definition_Name__c,
            Object_API_Name__c='Contact'
        );
        
        Mapping_Object__c accMap = new Mapping_Object__c(
        	Definition__c=l.Mapping_Definition_Name__c,
            Object_API_Name__c='Account'
        );

        Mapping_Object__c campMap = new Mapping_Object__c(
        	Definition__c=l.Mapping_Definition_Name__c,
        	Object_API_Name__c = 'Campaign'
        );
        
        insert new List<Mapping_Object__c>{conMap, accMap, campMap};
        
        Mapping_Field__c conFirstName = new Mapping_Field__c(
        	Mapping_Object__c = conMap.Id,
            Field_API_Name__c = 'FirstName',
            Source_Fields__c = 'FirstName'
        );
        
        Mapping_Field__c conLastName = new Mapping_Field__c(
        	Mapping_Object__c = conMap.Id,
            Field_API_Name__c = 'LastName',
            Source_Fields__c = 'LastName'
        );
        
        Mapping_Field__c conEmail = new Mapping_Field__c(
        	Mapping_Object__c = conMap.Id,
            Field_API_Name__c = 'Email',
            Source_Fields__c = 'Email'
        );

        Mapping_Field__c accName = new Mapping_Field__c(
        	Mapping_Object__c = accMap.Id,
            Field_API_Name__c = 'Name',
            Source_Fields__c = 'Company'
        );
        
        Mapping_Field__c accCompoundFld = new Mapping_Field__c(
        	Mapping_Object__c = accMap.Id,
            Field_API_Name__c = 'Description',
            Source_Fields__c = 'Status+ +LeadSource'
        );

        Mapping_Field__c campName = new Mapping_Field__c(
        	Mapping_Object__c = campMap.Id,
        	Field_API_Name__c = 'Name',
        	Source_Fields__c = 'Company+ + - Campaign'
        );
        
		Mapping_Field__c campStart = new Mapping_Field__c(
        	Mapping_Object__c = campMap.Id,
            Field_API_Name__c = 'StartDate',
            Default_Value__c = '01/01/2016 15:55'
        );

        Mapping_Field__c campEnd = new Mapping_Field__c(
        	Mapping_Object__c = campMap.Id,
        	Field_API_Name__c = 'EndDate',
        	Default_Value__c = '12/12/2016 17:33'
        );
        
        Mapping_Field__c campActive = new Mapping_Field__c(
        	Mapping_Object__c = campMap.Id,
            Field_API_Name__c = 'IsActive',
            Default_Value__c = 'Yes'
        );

        Mapping_Field__c campActCost = new Mapping_Field__c(
        	Mapping_Object__c = campMap.Id,
            Field_API_Name__c = 'ActualCost',
            Default_Value__c = '20000.00'
        );
        
        insert new List<Mapping_Field__c>{conFirstName, conLastName, conEmail, accName, accCompoundFld, campName, campStart, campEnd, campActive, campActCost};
        
            
        Mapping_Reference__c accCon = new Mapping_Reference__c(
        	Mapping_Object__c = conMap.Id,
            Reference_Field_API_Name__c = 'AccountId',
            Reference_Type__c = 'SObject Definition',
            Defined_Object__c = accMap.Id
        );
        
        Mapping_Reference__c conOwn = new Mapping_Reference__c(
        	Mapping_Object__c = conMap.Id,
            Reference_Field_API_Name__c = 'OwnerId',
            Reference_Type__c = 'Id Value',
            Id_ExtId_Value__c = UserInfo.getUserId()
        );

        Mapping_Reference__c campMemb = new Mapping_Reference__c(
        	Mapping_Object__c = conMap.Id,
        	Reference_Type__c = 'Join Object',
        	Referenced_Object_API_Name__c = 'CampaignMember',
        	Reference_Field_API_Name__c = 'ContactId',
        	Defined_Object__c = campMap.Id,
        	Referenced_Object_ExtId_API_Name__c = 'CampaignId'
        );
        
        insert new List<Mapping_Reference__c>{accCon, conOwn, campMemb}; //, conReporter};
        
        Test.startTest();
        
        ApexPages.StandardController sc = new ApexPages.StandardController(l);
        ProcessLeadMappingController plmc = new ProcessLeadMappingController(sc);
        
        plmc.processLeadMapping();
        
        Test.stopTest();
        
    }

    private static Lead createTestData() {
        Lead l = new Lead(FirstName='John', LastName='Doe', Email='john@doe.org', Company='Test Account', LeadSource='Advertisement', Status='New', Mapping_Definition_Name__c='Test Def');
        insert l;

        Mapping_Object__c conMap = new Mapping_Object__c(
            Definition__c=l.Mapping_Definition_Name__c,
            Object_API_Name__c='Contact'
        );
        
        Mapping_Object__c accMap = new Mapping_Object__c(
            Definition__c=l.Mapping_Definition_Name__c,
            Object_API_Name__c='Account'
        );

        Mapping_Object__c campMap = new Mapping_Object__c(
            Definition__c=l.Mapping_Definition_Name__c,
            Object_API_Name__c = 'Campaign'
        );
        
        insert new List<Mapping_Object__c>{conMap, accMap, campMap};
        
        Mapping_Field__c conFirstName = new Mapping_Field__c(
            Mapping_Object__c = conMap.Id,
            Field_API_Name__c = 'FirstName',
            Source_Fields__c = 'FirstName'
        );
        
        Mapping_Field__c conLastName = new Mapping_Field__c(
            Mapping_Object__c = conMap.Id,
            Field_API_Name__c = 'LastName',
            Source_Fields__c = 'LastName'
        );
        
        Mapping_Field__c conEmail = new Mapping_Field__c(
            Mapping_Object__c = conMap.Id,
            Field_API_Name__c = 'Email',
            Source_Fields__c = 'Email'
        );

        Mapping_Field__c accName = new Mapping_Field__c(
            Mapping_Object__c = accMap.Id,
            Field_API_Name__c = 'Name',
            Source_Fields__c = 'Company'
        );

        List<RecordType> rTypes = [SELECT Id FROM RecordType WHERE sObjectType = 'Account' AND isActive = true AND DeveloperName != 'HH_Account'];
        
        if(rTypes != null && rTypes.size() > 0) {
            Mapping_Field__c accRecordType = new Mapping_Field__c(
                Mapping_Object__c = accMap.Id,
                Field_API_Name__c = 'RecordTypeId',
                Default_Value__c = rTypes[0].Id
            );
        }
        
        Mapping_Field__c accCompoundFld = new Mapping_Field__c(
            Mapping_Object__c = accMap.Id,
            Field_API_Name__c = 'Description',
            Source_Fields__c = 'Status+ +LeadSource'
        );

        Mapping_Field__c campName = new Mapping_Field__c(
            Mapping_Object__c = campMap.Id,
            Field_API_Name__c = 'Name',
            Source_Fields__c = 'Company+ + - Campaign'
        );
        
        Mapping_Field__c campStart = new Mapping_Field__c(
            Mapping_Object__c = campMap.Id,
            Field_API_Name__c = 'StartDate',
            Default_Value__c = '01/01/2016 15:55'
        );

        Mapping_Field__c campEnd = new Mapping_Field__c(
            Mapping_Object__c = campMap.Id,
            Field_API_Name__c = 'EndDate',
            Default_Value__c = '12/12/2016 17:33'
        );
        
        Mapping_Field__c campActive = new Mapping_Field__c(
            Mapping_Object__c = campMap.Id,
            Field_API_Name__c = 'IsActive',
            Default_Value__c = 'Yes'
        );

        Mapping_Field__c campActCost = new Mapping_Field__c(
            Mapping_Object__c = campMap.Id,
            Field_API_Name__c = 'ActualCost',
            Default_Value__c = '20000.00'
        );
        
        insert new List<Mapping_Field__c>{conFirstName, conLastName, conEmail, accName, accCompoundFld, campName, campStart, campEnd, campActive, campActCost};
        
            
        Mapping_Reference__c accCon = new Mapping_Reference__c(
            Mapping_Object__c = conMap.Id,
            Reference_Field_API_Name__c = 'AccountId',
            Reference_Type__c = 'SObject Definition',
            Defined_Object__c = accMap.Id
        );
        
        Mapping_Reference__c conOwn = new Mapping_Reference__c(
            Mapping_Object__c = conMap.Id,
            Reference_Field_API_Name__c = 'OwnerId',
            Reference_Type__c = 'Id Value',
            Id_ExtId_Value__c = UserInfo.getUserId()
        );

        Mapping_Reference__c campMemb = new Mapping_Reference__c(
            Mapping_Object__c = conMap.Id,
            Reference_Type__c = 'Join Object',
            Referenced_Object_API_Name__c = 'CampaignMember',
            Reference_Field_API_Name__c = 'ContactId',
            Defined_Object__c = campMap.Id,
            Referenced_Object_ExtId_API_Name__c = 'CampaignId',
            Upsert_Field_API_Name__c = 'Campaign_Member_External_ID__c'
        );
        
        insert new List<Mapping_Reference__c>{accCon, conOwn, campMemb}; //, conReporter};

        Mapping_Field__c campMembEmail = new Mapping_Field__c(
            Mapping_Reference__c = campMemb.Id,
            Source_Fields__c = 'Email',
            Field_API_Name__c = 'Email'
        );

        Mapping_Field__c campMembPart = new Mapping_Field__c(
            Mapping_Reference__c = campMemb.Id,
            Source_Fields__c = 'FirstName+LastName+Email+Static Text',
            Field_API_Name__c = 'Participation__c'
        );

        Mapping_Field__c campMembExtId = new Mapping_Field__c(
            Mapping_Reference__c = campMemb.Id,
            Default_Value__c = String.valueOf(accCon.Id) + String.valueOf(conOwn.Id),
            Field_API_Name__c = 'Campaign_Member_External_ID__c'
        );

        insert new List<Mapping_Field__c>{campMembEmail, campMembPart, campMembExtId};

        return l;
    }
    
}