force-app/main/default/objects/Account/fields/Community_Home_Page_Text__c.field-meta.xml
<CustomField>
    <fullName>Community_Home_Page_Text__c</fullName>
    <label>Community Home Page Text</label>
    <length>32768</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/Account/fields/Corporate_Contact_Us_Message__c.field-meta.xml
<CustomField>
    <fullName>Corporate_Contact_Us_Message__c</fullName>
    <label>Corporate Contact Us Message</label>
    <length>32768</length>
    <type>Html</type>
</CustomField>

force-app/main/default/classes/portalVolunteerHomeController.cls
public class portalVolunteerHomeController {

    public Account acc{get;set;}
    public Contact con{get;set;}
    
    public portalVolunteerHomeController() {
        
        for(User u : [SELECT Id, ContactId, Contact.Id, Contact.Name, Contact.AccountId, Contact.Account.Id, Contact.Account.Community_Home_Page_Text__c, Contact.Account.Corporate_Contact_Us_Message__c  FROM User WHERE Id = :UserInfo.getUserId()]) {
            
            if(String.isNotBlank(u.ContactId) && String.isNotBlank(u.Contact.AccountId)) {
                con = u.Contact;
                acc = u.Contact.Account;
            }
            
        }
        
    }
    
}