force-app/main/default/objects/Account/fields/Eligible_for_Respite_General__c.field-meta.xml
<CustomField>
    <fullName>Eligible_for_Respite_General__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Eligible for Respite General</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account/fields/Eligible_for_Respite_Salamander__c.field-meta.xml
<CustomField>
    <fullName>Eligible_for_Respite_Salamander__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Eligible for Respite Salamander</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Property__c/Property__c.object-meta.xml
<CustomObject>
    <description>Used for family retreat - record of properties available for families to book from.  See documentation on Retreat booking under clouding around files for full details.</description>
    <label>Property</label>
    <nameField>
        <label>Property Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Properties</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Property__c/fields/Address__c.field-meta.xml
<CustomField>
    <fullName>Address__c</fullName>
    <description>Complete address shown on the portal</description>
    <inlineHelpText>Complete address shown on the portal</inlineHelpText>
    <label>Address</label>
    <length>2000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Property__c/fields/Available_for_booking_portal__c.field-meta.xml
<CustomField>
    <fullName>Available_for_booking_portal__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Shows property on the booking portal</description>
    <inlineHelpText>Shows property on the booking portal</inlineHelpText>
    <label>Available for booking portal</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Property__c/fields/Can_extend_to_full_week_an_own_expense__c.field-meta.xml
<CustomField>
    <fullName>Can_extend_to_full_week_an_own_expense__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Option to extend to the full week at the
family’s own expense</description>
    <inlineHelpText>Option to extend to the full week at the
family’s own expense</inlineHelpText>
    <label>Can extend to full week an own expense</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Property__c/fields/Guests__c.field-meta.xml
<CustomField>
    <fullName>Guests__c</fullName>
    <description>Number of guests e.g. ( 7 = Sleeps 7 people)</description>
    <inlineHelpText>Number of guests e.g. ( 7 = Sleeps 7 people)</inlineHelpText>
    <label>Guests</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Property__c/fields/Length_of_stay__c.field-meta.xml
<CustomField>
    <fullName>Length_of_stay__c</fullName>
    <label>Length of stay</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>8 days (7 nights)</fullName>
            </value>
            <value>
                <fullName>7 days (6 nights)</fullName>
            </value>
            <value>
                <fullName>6 days (5 nights)</fullName>
            </value>
            <value>
                <fullName>5 days (4 nights)</fullName>
            </value>
            <value>
                <fullName>4 days (3 nights)</fullName>
            </value>
            <value>
                <fullName>3 days (2 nights)</fullName>
            </value>
            <value>
                <fullName>2 days (1 night)</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Property__c/fields/Peak_period_restrictions__c.field-meta.xml
<CustomField>
    <fullName>Peak_period_restrictions__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Restrictions for peak/off peak times</description>
    <inlineHelpText>Restrictions for peak/off peak times</inlineHelpText>
    <label>Peak period restrictions</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Property__c/fields/Portal_Description__c.field-meta.xml
<CustomField>
    <fullName>Portal_Description__c</fullName>
    <label>Portal Description</label>
    <length>32768</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/Property__c/fields/State__c.field-meta.xml
<CustomField>
    <fullName>State__c</fullName>
    <label>State</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>NSW</fullName>
            </value>
            <value>
                <fullName>QLD</fullName>
            </value>
            <value>
                <fullName>SA</fullName>
            </value>
            <value>
                <fullName>TAS</fullName>
            </value>
            <value>
                <fullName>VIC</fullName>
            </value>
            <value>
                <fullName>WA</fullName>
            </value>
            <value>
                <fullName>NT</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Property__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>General</fullName>
                <default>true</default>
                <label>General</label>
            </value>
            <value>
                <fullName>Salamander</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/portalRespiteController.cls
public class portalRespiteController {

    public List<Property__c> properties {get; set;}
    public Boolean eligible {get;set;}
    public Boolean sEligible {get;set;}
//    public String aId{get;set;}

    public portalRespiteController(){
        properties = new List<Property__c>([
                SELECT
                        Address__c,Available_for_booking_portal__c,
                        Can_extend_to_full_week_an_own_expense__c,
                        Guests__c,Id,Image_URL__c,Length_of_stay__c,
                        Name,Peak_period_restrictions__c,Portal_Description__c,
                        State__c,Type__c
                FROM
                        Property__c
                WHERE
                        Available_for_booking_portal__c = TRUE
            order by type__C
        ]);





        String aId = [Select AccountId from User where id =: Userinfo.getUserid() LIMIT 1].AccountId;

        System.debug(aId);

        for(Account a :[SELECT Id,Name,Eligible_for_Respite_General__c,Eligible_for_Respite_Salamander__c FROM Account WHERE Id =: aId]){
            eligible = a.Eligible_for_Respite_General__c;
            sEligible = a.Eligible_for_Respite_Salamander__c;
        }


//        String cId = [Select ContactId from User where id =: Userinfo.getUserid() LIMIT 1].ContactId;
//
//        for(Contact c :[SELECT Id,Name,eligible_for_Respite_Retreats__c,Respite_Salamander_Eligible__c FROM Contact WHERE Id =: cId]){
//            eligible = c.eligible_for_Respite_Retreats__c;
//            sEligible = c.Respite_Salamander_Eligible__c;
//        }
    }
}