force-app/main/default/objects/Account/fields/Emergency_Contact__c.field-meta.xml
<CustomField>
    <fullName>Emergency_Contact__c</fullName>
    <label>Emergency Contact</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Emergency_Contact_Phone__c.field-meta.xml
<CustomField>
    <fullName>Emergency_Contact_Phone__c</fullName>
    <label>Emergency Contact Phone</label>
    <type>Phone</type>
</CustomField>

force-app/main/default/objects/Account/fields/Media_Opt_in_Public_Sharing__c.field-meta.xml
<CustomField>
    <fullName>Media_Opt_in_Public_Sharing__c</fullName>
    <defaultValue>false</defaultValue>
    <description>I allow photo/video to be shared by Camp Quality on their social media pages and website - Legacy, not needed</description>
    <inlineHelpText>I allow photo/video to be shared by Camp Quality on their social media pages and website - Legacy, not needed</inlineHelpText>
    <label>Image Opt-in Public Sharing (LEGACY)</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account/fields/media_opt_in_share_participants__c.field-meta.xml
<CustomField>
    <fullName>media_opt_in_share_participants__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>I allow photos/video to be shared with participants from Camp Quality services and programs via a password protected photo gallery</inlineHelpText>
    <label>Image Opt-in Participant Sharing</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account/fields/media_opt_in_take_video_photos__c.field-meta.xml
<CustomField>
    <fullName>media_opt_in_take_video_photos__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>I approve of photos and video footage being taken of me and my children participating in Camp Quality services and programs</inlineHelpText>
    <label>Image Opt-In photos and video</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account/fields/Media_Permission_All_2019__c.field-meta.xml
<CustomField>
    <fullName>Media_Permission_All_2019__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>I allow photos/video to be shared by Camp Quality in all the below ways</inlineHelpText>
    <label>Image Opt In Permission All</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account/fields/Media_permission_corporate_2019__c.field-meta.xml
<CustomField>
    <fullName>Media_permission_corporate_2019__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>I allow Camp Quality to share the photo/video with its corporate partners and major donors, to be used to promote Camp Quality&apos;s charitable purposes and the partnership</inlineHelpText>
    <label>Image Opt-In Permission Corporate</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account/fields/Media_Permission_Denied__c.field-meta.xml
<CustomField>
    <fullName>Media_Permission_Denied__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Media Permission Denied</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account/fields/Media_Permission_Functions__c.field-meta.xml
<CustomField>
    <fullName>Media_Permission_Functions__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Media Permission Functions</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account/fields/Media_Permission_Interviews__c.field-meta.xml
<CustomField>
    <fullName>Media_Permission_Interviews__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Media Permission Interviews</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account/fields/Media_Permission_Photo_Share__c.field-meta.xml
<CustomField>
    <fullName>Media_Permission_Photo_Share__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Media Permission Photo Share</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account/fields/Media_Permission_Photos__c.field-meta.xml
<CustomField>
    <fullName>Media_Permission_Photos__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Media Permission Photos</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account/fields/Media_Permission_Pub__c.field-meta.xml
<CustomField>
    <fullName>Media_Permission_Pub__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Media Permission Publicity</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account/fields/Media_permission_Public_2019__c.field-meta.xml
<CustomField>
    <fullName>Media_permission_Public_2019__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>I allow Camp Quality to use photos/video to promote Camp Quality&apos;s charitable purposes</inlineHelpText>
    <label>Image Opt In Permission Public</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account/fields/Preferred_Event_Locations__c.field-meta.xml
<CustomField>
    <fullName>Preferred_Event_Locations__c</fullName>
    <label>Preferred Event Locations</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Illawarra</fullName>
            </value>
            <value>
                <fullName>Sydney</fullName>
            </value>
            <value>
                <fullName>Northern New South Wales</fullName>
            </value>
            <value>
                <fullName>South Queensland</fullName>
            </value>
            <value>
                <fullName>Victoria</fullName>
            </value>
            <value>
                <fullName>South Australia</fullName>
            </value>
            <value>
                <fullName>Australian Capital Territory</fullName>
            </value>
            <value>
                <fullName>Newcastle</fullName>
            </value>
            <value>
                <fullName>Western Australia</fullName>
            </value>
            <value>
                <fullName>Central Queensland</fullName>
            </value>
            <value>
                <fullName>Tasmania</fullName>
            </value>
            <value>
                <fullName>North Queensland</fullName>
            </value>
            <value>
                <fullName>Northern Territory</fullName>
            </value>
            <value>
                <fullName>Queensland</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/Emergency_Contact__c.field-meta.xml
<CustomField>
    <fullName>Emergency_Contact__c</fullName>
    <label>Emergency Contact</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Media_Opt_in_Public_Sharing__c.field-meta.xml
<CustomField>
    <fullName>Media_Opt_in_Public_Sharing__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>I allow photo/video to be shared by Camp Quality on their social media pages and website - Legacy, not needed</inlineHelpText>
    <label>Image Opt-in Public Sharing (LEGACY)</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Contact/fields/media_opt_in_share_participants__c.field-meta.xml
<CustomField>
    <fullName>media_opt_in_share_participants__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>I allow photos/video to be shared with participants from Camp Quality services and programs via a password protected photo gallery</inlineHelpText>
    <label>Image Opt-in Participant Sharing</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Contact/fields/media_opt_in_take_video_photos__c.field-meta.xml
<CustomField>
    <fullName>media_opt_in_take_video_photos__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>I approve of photos and video footage being taken of me whilst attending Camp Quality services and programs</inlineHelpText>
    <label>Image Opt-In photos and video</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Media_Permission_All_2019__c.field-meta.xml
<CustomField>
    <fullName>Media_Permission_All_2019__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>I allow photos/video to be shared by Camp Quality in all the below ways</inlineHelpText>
    <label>Image Opt In Permission All</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Media_permission_corporate_2019__c.field-meta.xml
<CustomField>
    <fullName>Media_permission_corporate_2019__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>I allow Camp Quality to share the photo/video with its corporate partners and major donors, to be used to promote Camp Quality&apos;s charitable purposes and the partnership</inlineHelpText>
    <label>Image Opt-In Permission Corporate</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Media_Permission_Denied__c.field-meta.xml
<CustomField>
    <fullName>Media_Permission_Denied__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Media Permission Denied</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Media_Permission_Functions__c.field-meta.xml
<CustomField>
    <fullName>Media_Permission_Functions__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Media Permission Functions</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Media_Permission_Interviews__c.field-meta.xml
<CustomField>
    <fullName>Media_Permission_Interviews__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Media Permission Interviews</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Media_Permission_Photo_Share__c.field-meta.xml
<CustomField>
    <fullName>Media_Permission_Photo_Share__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Media Permission Photo Share</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Media_Permission_Photos__c.field-meta.xml
<CustomField>
    <fullName>Media_Permission_Photos__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Media Permission Photos</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Media_permission_Public_2019__c.field-meta.xml
<CustomField>
    <fullName>Media_permission_Public_2019__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>I allow Camp Quality to use photos/video to promote Camp Quality&apos;s charitable purposes</inlineHelpText>
    <label>Image Opt In Permission Public</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Preferred_Event_Locations__c.field-meta.xml
<CustomField>
    <fullName>Preferred_Event_Locations__c</fullName>
    <label>Preferred Event Locations</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Event_Locations</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/Requests_no_Marketing_Materials__c.field-meta.xml
<CustomField>
    <fullName>Requests_no_Marketing_Materials__c</fullName>
    <defaultValue>false</defaultValue>
    <description>To be checked if the contact does not want to receive information about fundraising, services and programs, or newsletters</description>
    <inlineHelpText>To be checked if the contact does not want to receive information about fundraising, services and programs, or newsletters</inlineHelpText>
    <label>Requests no Marketing Materials</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Requests_No_Newsletter__c.field-meta.xml
<CustomField>
    <fullName>Requests_No_Newsletter__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Requests No Newsletter</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Shirt_Size__c.field-meta.xml
<CustomField>
    <fullName>Shirt_Size__c</fullName>
    <label>Shirt Size</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Kids 2</fullName>
            </value>
            <value>
                <fullName>Kids 4</fullName>
            </value>
            <value>
                <fullName>Kids 6</fullName>
            </value>
            <value>
                <fullName>Kids 8</fullName>
            </value>
            <value>
                <fullName>Kids 10</fullName>
            </value>
            <value>
                <fullName>Kids 12</fullName>
            </value>
            <value>
                <fullName>Kids 14</fullName>
            </value>
            <value>
                <fullName>Adult XS</fullName>
            </value>
            <value>
                <fullName>Adult S</fullName>
            </value>
            <value>
                <fullName>Adult M</fullName>
            </value>
            <value>
                <fullName>Adult L</fullName>
            </value>
            <value>
                <fullName>Adult XL</fullName>
            </value>
            <value>
                <fullName>Adult 2XL</fullName>
            </value>
            <value>
                <fullName>Adult 3XL</fullName>
            </value>
            <value>
                <fullName>Adult 4XL</fullName>
            </value>
            <value>
                <fullName>Adult 5XL</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/Swimming_Ability__c.field-meta.xml
<CustomField>
    <fullName>Swimming_Ability__c</fullName>
    <label>Swimming Ability</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>0-25m</fullName>
            </value>
            <value>
                <fullName>25-50m</fullName>
            </value>
            <value>
                <fullName>50m and above</fullName>
            </value>
            <value>
                <fullName>Cannot swim</fullName>
            </value>
            <value>
                <fullName>Cannot swim in public pools</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/Volunteer_Last_Training_Date__c.field-meta.xml
<CustomField>
    <fullName>Volunteer_Last_Training_Date__c</fullName>
    <label>Volunteer Last Training Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/globalValueSets/Event_Locations.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Australian Capital Territory</fullName>
    </customValue>
    <customValue>
        <fullName>Central Queensland</fullName>
    </customValue>
    <customValue>
        <fullName>Illawarra</fullName>
    </customValue>
    <customValue>
        <fullName>National</fullName>
    </customValue>
    <customValue>
        <fullName>National Office</fullName>
    </customValue>
    <customValue>
        <fullName>Newcastle</fullName>
    </customValue>
    <customValue>
        <fullName>Northern New South Wales</fullName>
    </customValue>
    <customValue>
        <fullName>Northern Territory</fullName>
    </customValue>
    <customValue>
        <fullName>North Queensland</fullName>
    </customValue>
    <customValue>
        <fullName>Queensland</fullName>
    </customValue>
    <customValue>
        <fullName>South Australia</fullName>
    </customValue>
    <customValue>
        <fullName>South Queensland</fullName>
    </customValue>
    <customValue>
        <fullName>Sydney</fullName>
    </customValue>
    <customValue>
        <fullName>Tasmania</fullName>
    </customValue>
    <customValue>
        <fullName>Victoria</fullName>
    </customValue>
    <customValue>
        <fullName>Western Australia</fullName>
    </customValue>
    <masterLabel>Event Locations</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/portalCore.cls
global class portalCore {

    public static Contact userContact {get {

        System.Debug('userContact: ' + userContact);

        if(userContact == null) {

            List<User> uList = new List<User>([SELECT Id, ContactId FROM User WHERE Id = :UserInfo.getUserId()]);

            if(!uList.isEmpty()) {

                List<Contact> cList = new List<Contact>([SELECT Id, Name, FirstName, LastName, Email, HomePhone, MailingStreet, MailingCity,
                                                         MailingState, MailingPostalCode, MailingCountry, Preferred_Event_Locations__c, RecordType.DeveloperName,
                                                         Swimming_Ability__c, Shirt_Size__c, Emergency_Contact__c, Emergency_Contact_Phone__c,
                                                         Emergency_Contact_Mobile__c, Emergency_Contact_Relationship__c, Account.Name, Birthdate,
                                                         MobilePhone, Media_Permission_Denied__c, Media_Permission_Functions__c, Requests_no_Marketing_Materials__c, Requests_No_Newsletter__c,
                                                         Media_Permission_Interviews__c, Media_Permission_Photos__c, Media_Permission_Photo_Share__c, media_opt_in_share_participants__c, media_opt_in_take_video_photos__c, Media_Opt_in_Public_Sharing__c,
                                                         Media_Permission_Pub__c, AccountId, Account.OwnerId, Account.Phone, Account.BillingStreet, Media_Permission_All_2019__c, Media_permission_Public_2019__c, Media_permission_corporate_2019__c,
                                                         Account.BillingCity, Account.BillingPostalCode, Account.BillingState, Contact.Volunteer_Last_Training_Date__c
                                                         FROM Contact WHERE Id = :uList[0].ContactId]);

                if(!cList.isEmpty()) {

                    userContact =  cList[0];
                } else {
                    //for testing
                    //userContact = [SELECT Id, Current_Deployment__c, Member_Status__c FROM Contact WHERE Id = '003S000000rlCbs'];
                }
            } else {
                //for testing
                //userContact = [SELECT Id, Current_Deployment__c, Member_Status__c FROM Contact WHERE Id = '003S000000rlCbs'];
            }

        }

        return userContact;

    }   set;}

    public static Map<ID, Map<String, Field>> eventsMap(List<ID> eventIds) {

        Map<ID, Map<String, Field>> eventList = new Map<ID, Map<String, Field>>();

        Integer numberOfEvents;

        Schema.DescribeSObjectResult objDescribe = Campaign.sObjectType.getDescribe();
        map<String, Schema.SObjectField> fieldMap = objDescribe.fields.getMap();

        String theQuery = 'SELECT ';

        for(Schema.SObjectField s : fieldMap.values())
            theQuery += s.getDescribe().getName() + ',';

        theQuery = theQuery.subString(0, theQuery.length() - 1);

        theQuery += ' FROM Campaign WHERE Id IN :eventIds';

        try {

            List<Campaign> objList = Database.query(theQuery);

            numberOfEvents = objList.size();

            System.debug('orderList: ' + objList);

            for(Campaign c : objList) {

                System.debug('obj: ' + c);

                System.debug('fieldmap: ' + fieldMap);

                eventList.put(c.Id, new Map<String, Field>());

                System.debug('fieldmap: ' + fieldMap);

                for(Schema.SObjectField s : fieldMap.values()) {

                    eventList.get(c.Id).put(
                        (String)s.getDescribe().getName(),
                        new Field((String)s.getDescribe().getLabel(), c.get(s.getDescribe().getName()))
                    );
                    System.debug('fieldmap values: ' + s);

                }
            }

        } catch(Exception e) {

        }

        return eventList;

    }

    public class Field {
        public String Label {get;set;}
        public Object Value {get;set;}

        public Field(String l, Object v) {
            this.Label = l;
            this.Value = v;
        }
    }

    public static PageReference pageLink(String pageName) {

        List<Page__c> ps = [SELECT Id, Page_URL_Name__c, Site__c, Site__r.Site_URL__c FROM Page__c WHERE Name = :pageName];

        if(ps != null && ps.size() > 0) {
            PageReference pRef = Page.portalPage;

            if(String.isNotEmpty(ps[0].Page_URL_Name__c)) {
                pRef.getParameters().put('p', ps[0].Page_URL_Name__c);
            } else {
                pRef.getParameters().put('p', ps[0].Id);
            }

            if(String.isNotEmpty(ps[0].Site__c) && String.isNotEmpty(ps[0].Site__r.Site_URL__c)) {
                pRef.getParameters().put('s', ps[0].Site__r.Site_URL__c);
            } else {
                pRef.getParameters().put('s', ps[0].Site__c);
            }

            pRef.setRedirect(true);

            return pRef;
        } else {
            return null;
        }

    }

}