force-app/main/default/objects/Account/fields/Emergency_Contact__c.field-meta.xml
<CustomField>
    <fullName>Emergency_Contact__c</fullName>
    <label>Emergency Contact</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Emergency_Contact_Phone__c.field-meta.xml
<CustomField>
    <fullName>Emergency_Contact_Phone__c</fullName>
    <label>Emergency Contact Phone</label>
    <type>Phone</type>
</CustomField>

force-app/main/default/objects/Account/fields/Preferred_Event_Locations__c.field-meta.xml
<CustomField>
    <fullName>Preferred_Event_Locations__c</fullName>
    <label>Preferred Event Locations</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Illawarra</fullName>
            </value>
            <value>
                <fullName>Sydney</fullName>
            </value>
            <value>
                <fullName>Northern New South Wales</fullName>
            </value>
            <value>
                <fullName>South Queensland</fullName>
            </value>
            <value>
                <fullName>Victoria</fullName>
            </value>
            <value>
                <fullName>South Australia</fullName>
            </value>
            <value>
                <fullName>Australian Capital Territory</fullName>
            </value>
            <value>
                <fullName>Newcastle</fullName>
            </value>
            <value>
                <fullName>Western Australia</fullName>
            </value>
            <value>
                <fullName>Central Queensland</fullName>
            </value>
            <value>
                <fullName>Tasmania</fullName>
            </value>
            <value>
                <fullName>North Queensland</fullName>
            </value>
            <value>
                <fullName>Northern Territory</fullName>
            </value>
            <value>
                <fullName>Queensland</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/Emergency_Contact__c.field-meta.xml
<CustomField>
    <fullName>Emergency_Contact__c</fullName>
    <label>Emergency Contact</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Preferred_Event_Locations__c.field-meta.xml
<CustomField>
    <fullName>Preferred_Event_Locations__c</fullName>
    <label>Preferred Event Locations</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Event_Locations</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/Shirt_Size__c.field-meta.xml
<CustomField>
    <fullName>Shirt_Size__c</fullName>
    <label>Shirt Size</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Kids 2</fullName>
            </value>
            <value>
                <fullName>Kids 4</fullName>
            </value>
            <value>
                <fullName>Kids 6</fullName>
            </value>
            <value>
                <fullName>Kids 8</fullName>
            </value>
            <value>
                <fullName>Kids 10</fullName>
            </value>
            <value>
                <fullName>Kids 12</fullName>
            </value>
            <value>
                <fullName>Kids 14</fullName>
            </value>
            <value>
                <fullName>Adult XS</fullName>
            </value>
            <value>
                <fullName>Adult S</fullName>
            </value>
            <value>
                <fullName>Adult M</fullName>
            </value>
            <value>
                <fullName>Adult L</fullName>
            </value>
            <value>
                <fullName>Adult XL</fullName>
            </value>
            <value>
                <fullName>Adult 2XL</fullName>
            </value>
            <value>
                <fullName>Adult 3XL</fullName>
            </value>
            <value>
                <fullName>Adult 4XL</fullName>
            </value>
            <value>
                <fullName>Adult 5XL</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/Swimming_Ability__c.field-meta.xml
<CustomField>
    <fullName>Swimming_Ability__c</fullName>
    <label>Swimming Ability</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>0-25m</fullName>
            </value>
            <value>
                <fullName>25-50m</fullName>
            </value>
            <value>
                <fullName>50m and above</fullName>
            </value>
            <value>
                <fullName>Cannot swim</fullName>
            </value>
            <value>
                <fullName>Cannot swim in public pools</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/recordTypes/Volunteer.recordType-meta.xml
<RecordType>
    <fullName>Volunteer</fullName>
    <active>true</active>
    <label>Volunteer</label>
</RecordType>

force-app/main/default/globalValueSets/Event_Locations.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Australian Capital Territory</fullName>
    </customValue>
    <customValue>
        <fullName>Central Queensland</fullName>
    </customValue>
    <customValue>
        <fullName>Illawarra</fullName>
    </customValue>
    <customValue>
        <fullName>National</fullName>
    </customValue>
    <customValue>
        <fullName>National Office</fullName>
    </customValue>
    <customValue>
        <fullName>Newcastle</fullName>
    </customValue>
    <customValue>
        <fullName>Northern New South Wales</fullName>
    </customValue>
    <customValue>
        <fullName>Northern Territory</fullName>
    </customValue>
    <customValue>
        <fullName>North Queensland</fullName>
    </customValue>
    <customValue>
        <fullName>Queensland</fullName>
    </customValue>
    <customValue>
        <fullName>South Australia</fullName>
    </customValue>
    <customValue>
        <fullName>South Queensland</fullName>
    </customValue>
    <customValue>
        <fullName>Sydney</fullName>
    </customValue>
    <customValue>
        <fullName>Tasmania</fullName>
    </customValue>
    <customValue>
        <fullName>Victoria</fullName>
    </customValue>
    <customValue>
        <fullName>Western Australia</fullName>
    </customValue>
    <masterLabel>Event Locations</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/PortalContactUsTest.cls
/********************************************************************************************
* @Name         PortalContactUsTest
* @Author       Amit Yadav
* @Date         10/01/2024
* @Description  This class cover code of PortalContactUs apex class.
******************************************************************************************* 
MODIFICATION LOG
* Version          Developer          Date               Description
*
*  1.0             Amit Yadav         10/01/2024         Initial Creation                                                      
******************************************************************************************* */
@isTest
private class PortalContactUsTest {
    @testSetup
    public static void createAllData(){
       // Creating test Account records.
       Account ac = new Account();
        ac.Name = 'test';
        ac.Phone = '1234567890';
        ac.BillingStreet = 'testStreet';
        ac.BillingCity = 'Sydney';
        ac.BillingPostalCode = '778855';
        ac.BillingState = 'test';     
        insert ac;
        // Creating test Contact records.
        Contact con = new Contact();
        con.AccountId = ac.Id;
        con.LastName = 'Test';
        con.RecordTypeId =  Schema.SObjectType.Contact.getRecordTypeInfosByDeveloperName().get('Volunteer').getRecordTypeId();
        con.Email = 'test@gmail.com';
        con.HomePhone = '12345678';
        con.Preferred_Event_Locations__c = 'Central Queensland';
        con.MailingCity = 'Delhi';
        con.MailingStreet = 'testConStreet';
        con.MailingState = 'UP';
        con.MailingPostalCode = '443322';
        con.MailingCountry = 'UK';
        con.Swimming_Ability__c = '25-50m';
        con.Shirt_Size__c = 'Adult XS';
        con.Emergency_Contact__c = '5554449991';
        con.Emergency_Contact_Phone__c = '1239870458';
        con.Emergency_Contact_Mobile__c = '9807654321';
        con.Emergency_Contact_Relationship__c = 'Test';
        con.Birthdate = System.today();
        con.MobilePhone = '7856412534';
        con.recordTypeId = Schema.SObjectType.Contact.getRecordTypeInfosByDeveloperName().get('Volunteer').getRecordTypeId();
        insert con;
    }
    @isTest
    static void testCreateCase(){
                // Retrieving a Contact created in the test data setup.
        Contact con = [Select Id,FirstName,LastName,Email FROM Contact WHERE LastName LIKE '%Test%' LIMIT 1];
                // Creating a test User associated with the retrieved Contact and CommunityProfile.
         	    // Retrieving the CommunityProfile profile.
        Profile CommunityProfile = [SELECT Id FROM Profile WHERE Name = 'My Camp Quality Members' LIMIT 1];
        User us = new User(
            ContactId=con.Id,
            ProfileId=CommunityProfile.Id,
            EmailEncodingKey='UTF-8',
            LocaleSidKey='en_AU',
            LanguageLocaleKey='en_US',
            TimeZoneSidKey='Australia/Sydney',
            Email=con.Email,
            Phone = '22463634',
            UserName=con.Email,
            Alias=con.Email.subString(0, 8),
            FirstName=con.FirstName,
            LastName=con.LastName,
            IsActive = true
        );
         // Running as the test User to execute the methods in CommunityLoginController. 
        System.runAs(us){
                   // Call the createCase method from the PortalContactUs class
        String result = PortalContactUs.createCase('testsubject', 'details', 'Complex functionality', us.Id);
        String result2 = PortalContactUs.createCaseforFamily('subject', 'details', 'reason', us.Id);


        // Add assertions to verify the expected behavior
        System.assertNotEquals(null, result);
        System.assertEquals('Your message has been received. Someone will contact you shortly.', result);

        }
    }
    @isTest
    static void testCreateLoginCase() {
        // Set up the test data for the login case creation
        String subject = 'Test Subject';
        String details = 'Test Details';
        String reason = 'Test Reason';
        
        Contact con = [Select Id,FirstName,LastName,Email FROM Contact WHERE LastName LIKE '%Test%' LIMIT 1];
                // Creating a test User associated with the retrieved Contact and CommunityProfile.
         	    // Retrieving the CommunityProfile profile.
        Profile CommunityProfile = [SELECT Id FROM Profile WHERE Name = 'My Camp Quality Members' LIMIT 1];
        User us = new User(
            ContactId=con.Id,
            ProfileId=CommunityProfile.Id,
            EmailEncodingKey='UTF-8',
            LocaleSidKey='en_AU',
            LanguageLocaleKey='en_US',
            TimeZoneSidKey='Australia/Sydney',
            Email=con.Email,
            Phone = '22463634',
            UserName=con.Email,
            Alias=con.Email.subString(0, 8),
            FirstName=con.FirstName,
            LastName=con.LastName,
            IsActive = true
        );

        // Call the createLoginCase method from the PortalContactUs class
        String result = PortalContactUs.createLoginCase(subject, details, reason);
        
        // Add assertions to verify the expected behavior
        System.assertNotEquals(null, result);
        System.assertEquals('Your message has been received. Someone will contact you shortly.', result);

        // Additional assertions if needed
        Case[] createdCases = [SELECT Id FROM Case];
        System.assertEquals(1, createdCases.size(), 'Expected one case to be created');
    }
}