force-app/main/default/objects/Account/fields/Family_Interests__c.field-meta.xml
<CustomField>
    <fullName>Family_Interests__c</fullName>
    <label>Family Interests</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Theme Parks</fullName>
            </value>
            <value>
                <fullName>Sports</fullName>
            </value>
            <value>
                <fullName>Arts &amp; Crafts</fullName>
            </value>
            <value>
                <fullName>Science &amp; Education</fullName>
            </value>
            <value>
                <fullName>Cooking</fullName>
            </value>
            <value>
                <fullName>Live Entertainment</fullName>
            </value>
            <value>
                <fullName>Animals</fullName>
            </value>
            <value>
                <fullName>Vehicles &amp; Remote Control</fullName>
            </value>
            <value>
                <fullName>Gaming &amp; Tech</fullName>
            </value>
            <value>
                <fullName>Toys &amp; Board Games</fullName>
            </value>
            <value>
                <fullName>Health &amp; Wellbeing</fullName>
            </value>
            <value>
                <fullName>Aquarium</fullName>
                <isActive>false</isActive>
                <label>Aquarium</label>
            </value>
            <value>
                <fullName>Bike</fullName>
                <isActive>false</isActive>
                <label>Bike</label>
            </value>
            <value>
                <fullName>Circus</fullName>
                <isActive>false</isActive>
                <label>Circus</label>
            </value>
            <value>
                <fullName>Dance</fullName>
                <isActive>false</isActive>
                <label>Dance</label>
            </value>
            <value>
                <fullName>Movies</fullName>
                <isActive>false</isActive>
                <label>Movies</label>
            </value>
            <value>
                <fullName>Music</fullName>
                <isActive>false</isActive>
                <label>Music</label>
            </value>
            <value>
                <fullName>Outdoors</fullName>
                <isActive>false</isActive>
                <label>Outdoors</label>
            </value>
            <value>
                <fullName>Sport - AFL</fullName>
                <isActive>false</isActive>
                <label>Sport - AFL</label>
            </value>
            <value>
                <fullName>Sport - Basketball</fullName>
                <isActive>false</isActive>
                <label>Sport - Basketball</label>
            </value>
            <value>
                <fullName>Sport - Cricket</fullName>
                <isActive>false</isActive>
                <label>Sport - Cricket</label>
            </value>
            <value>
                <fullName>Sport - Motor</fullName>
                <isActive>false</isActive>
                <label>Sport - Motor</label>
            </value>
            <value>
                <fullName>Sport - NRL</fullName>
                <isActive>false</isActive>
                <label>Sport - NRL</label>
            </value>
            <value>
                <fullName>Sport - Netball</fullName>
                <isActive>false</isActive>
                <label>Sport - Netball</label>
            </value>
            <value>
                <fullName>Sport - Other</fullName>
                <isActive>false</isActive>
                <label>Sport - Other</label>
            </value>
            <value>
                <fullName>Sport - Rugby Union</fullName>
                <isActive>false</isActive>
                <label>Sport - Rugby Union</label>
            </value>
            <value>
                <fullName>Sport - Soccer</fullName>
                <isActive>false</isActive>
                <label>Sport - Soccer</label>
            </value>
            <value>
                <fullName>Sport - Tennis</fullName>
                <isActive>false</isActive>
                <label>Sport - Tennis</label>
            </value>
            <value>
                <fullName>Theater</fullName>
                <isActive>false</isActive>
                <label>Theater</label>
            </value>
            <value>
                <fullName>Zoo</fullName>
                <isActive>false</isActive>
                <label>Zoo</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Home_Phone__c.field-meta.xml
<CustomField>
    <fullName>Home_Phone__c</fullName>
    <label>Home Phone</label>
    <type>Phone</type>
</CustomField>

force-app/main/default/objects/Account/fields/Image_Opt_In_Permission_Corporate_Child__c.field-meta.xml
<CustomField>
    <fullName>Image_Opt_In_Permission_Corporate_Child__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>For children in my household, I allow photos/videos to be shared with our corporate partners and major donors, to promote Camp Quality&apos;s charitable purposes and the partnership.</inlineHelpText>
    <label>Child Image Opt-In Permission Corporate</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account/fields/Media_Opt_in_Public_Sharing__c.field-meta.xml
<CustomField>
    <fullName>Media_Opt_in_Public_Sharing__c</fullName>
    <defaultValue>false</defaultValue>
    <description>I allow photo/video to be shared by Camp Quality on their social media pages and website - Legacy, not needed</description>
    <inlineHelpText>I allow photo/video to be shared by Camp Quality on their social media pages and website - Legacy, not needed</inlineHelpText>
    <label>Image Opt-in Public Sharing (LEGACY)</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account/fields/media_opt_in_share_participants__c.field-meta.xml
<CustomField>
    <fullName>media_opt_in_share_participants__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>I allow photos/video to be shared with participants from Camp Quality services and programs via a password protected photo gallery</inlineHelpText>
    <label>Image Opt-in Participant Sharing</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account/fields/media_opt_in_take_video_photos__c.field-meta.xml
<CustomField>
    <fullName>media_opt_in_take_video_photos__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>I approve of photos and video footage being taken of me and my children participating in Camp Quality services and programs</inlineHelpText>
    <label>Image Opt-In photos and video</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account/fields/Media_Permission_All_2019__c.field-meta.xml
<CustomField>
    <fullName>Media_Permission_All_2019__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>I allow photos/video to be shared by Camp Quality in all the below ways</inlineHelpText>
    <label>Image Opt In Permission All</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account/fields/Media_Permission_Denied__c.field-meta.xml
<CustomField>
    <fullName>Media_Permission_Denied__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Media Permission Denied</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account/fields/Media_Permission_Functions__c.field-meta.xml
<CustomField>
    <fullName>Media_Permission_Functions__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Media Permission Functions</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account/fields/Media_Permission_Interviews__c.field-meta.xml
<CustomField>
    <fullName>Media_Permission_Interviews__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Media Permission Interviews</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account/fields/Media_Permission_Photo_Share__c.field-meta.xml
<CustomField>
    <fullName>Media_Permission_Photo_Share__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Media Permission Photo Share</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account/fields/Media_Permission_Photos__c.field-meta.xml
<CustomField>
    <fullName>Media_Permission_Photos__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Media Permission Photos</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account/fields/Media_Permission_Pub__c.field-meta.xml
<CustomField>
    <fullName>Media_Permission_Pub__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Media Permission Publicity</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account/fields/Mobile_Phone__c.field-meta.xml
<CustomField>
    <fullName>Mobile_Phone__c</fullName>
    <label>Mobile Phone</label>
    <type>Phone</type>
</CustomField>

force-app/main/default/objects/Account/fields/Preferred_Event_Locations__c.field-meta.xml
<CustomField>
    <fullName>Preferred_Event_Locations__c</fullName>
    <label>Preferred Event Locations</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Illawarra</fullName>
            </value>
            <value>
                <fullName>Sydney</fullName>
            </value>
            <value>
                <fullName>Northern New South Wales</fullName>
            </value>
            <value>
                <fullName>South Queensland</fullName>
            </value>
            <value>
                <fullName>Victoria</fullName>
            </value>
            <value>
                <fullName>South Australia</fullName>
            </value>
            <value>
                <fullName>Australian Capital Territory</fullName>
            </value>
            <value>
                <fullName>Newcastle</fullName>
            </value>
            <value>
                <fullName>Western Australia</fullName>
            </value>
            <value>
                <fullName>Central Queensland</fullName>
            </value>
            <value>
                <fullName>Tasmania</fullName>
            </value>
            <value>
                <fullName>North Queensland</fullName>
            </value>
            <value>
                <fullName>Northern Territory</fullName>
            </value>
            <value>
                <fullName>Queensland</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/recordTypes/Family.recordType-meta.xml
<RecordType>
    <fullName>Family</fullName>
    <active>true</active>
    <label>Family</label>
</RecordType>

force-app/main/default/objects/Contact/fields/Media_Opt_in_Public_Sharing__c.field-meta.xml
<CustomField>
    <fullName>Media_Opt_in_Public_Sharing__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>I allow photo/video to be shared by Camp Quality on their social media pages and website - Legacy, not needed</inlineHelpText>
    <label>Image Opt-in Public Sharing (LEGACY)</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Contact/fields/media_opt_in_share_participants__c.field-meta.xml
<CustomField>
    <fullName>media_opt_in_share_participants__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>I allow photos/video to be shared with participants from Camp Quality services and programs via a password protected photo gallery</inlineHelpText>
    <label>Image Opt-in Participant Sharing</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Contact/fields/media_opt_in_take_video_photos__c.field-meta.xml
<CustomField>
    <fullName>media_opt_in_take_video_photos__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>I approve of photos and video footage being taken of me whilst attending Camp Quality services and programs</inlineHelpText>
    <label>Image Opt-In photos and video</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Media_Permission_Denied__c.field-meta.xml
<CustomField>
    <fullName>Media_Permission_Denied__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Media Permission Denied</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Media_Permission_Functions__c.field-meta.xml
<CustomField>
    <fullName>Media_Permission_Functions__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Media Permission Functions</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Media_Permission_Interviews__c.field-meta.xml
<CustomField>
    <fullName>Media_Permission_Interviews__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Media Permission Interviews</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Media_Permission_Photo_Share__c.field-meta.xml
<CustomField>
    <fullName>Media_Permission_Photo_Share__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Media Permission Photo Share</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Media_Permission_Photos__c.field-meta.xml
<CustomField>
    <fullName>Media_Permission_Photos__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Media Permission Photos</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Preferred_Event_Locations__c.field-meta.xml
<CustomField>
    <fullName>Preferred_Event_Locations__c</fullName>
    <label>Preferred Event Locations</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Event_Locations</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/Requests_no_Marketing_Materials__c.field-meta.xml
<CustomField>
    <fullName>Requests_no_Marketing_Materials__c</fullName>
    <defaultValue>false</defaultValue>
    <description>To be checked if the contact does not want to receive information about fundraising, services and programs, or newsletters</description>
    <inlineHelpText>To be checked if the contact does not want to receive information about fundraising, services and programs, or newsletters</inlineHelpText>
    <label>Requests no Marketing Materials</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Requests_No_Newsletter__c.field-meta.xml
<CustomField>
    <fullName>Requests_No_Newsletter__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Requests No Newsletter</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Special_Needs__c/Special_Needs__c.object-meta.xml
<CustomObject>
    <label>Dietary &amp; Special Needs</label>
    <nameField>
        <displayFormat>SN - {0000}</displayFormat>
        <label>Special Needs Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Dietary &amp; Special Needs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Special_Needs__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipName>Special_Needs</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Special_Needs__c/recordTypes/Dietary_Requirement.recordType-meta.xml
<RecordType>
    <fullName>Dietary_Requirement</fullName>
    <active>true</active>
    <label>Dietary Requirement</label>
</RecordType>

force-app/main/default/objects/Special_Needs__c/recordTypes/Special_Need.recordType-meta.xml
<RecordType>
    <fullName>Special_Need</fullName>
    <active>true</active>
    <description>Non-food related allergies</description>
    <label>Special Need</label>
</RecordType>

force-app/main/default/globalValueSets/Event_Locations.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Australian Capital Territory</fullName>
    </customValue>
    <customValue>
        <fullName>Central Queensland</fullName>
    </customValue>
    <customValue>
        <fullName>Illawarra</fullName>
    </customValue>
    <customValue>
        <fullName>National</fullName>
    </customValue>
    <customValue>
        <fullName>National Office</fullName>
    </customValue>
    <customValue>
        <fullName>Newcastle</fullName>
    </customValue>
    <customValue>
        <fullName>Northern New South Wales</fullName>
    </customValue>
    <customValue>
        <fullName>Northern Territory</fullName>
    </customValue>
    <customValue>
        <fullName>North Queensland</fullName>
    </customValue>
    <customValue>
        <fullName>Queensland</fullName>
    </customValue>
    <customValue>
        <fullName>South Australia</fullName>
    </customValue>
    <customValue>
        <fullName>South Queensland</fullName>
    </customValue>
    <customValue>
        <fullName>Sydney</fullName>
    </customValue>
    <customValue>
        <fullName>Tasmania</fullName>
    </customValue>
    <customValue>
        <fullName>Victoria</fullName>
    </customValue>
    <customValue>
        <fullName>Western Australia</fullName>
    </customValue>
    <masterLabel>Event Locations</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/portalEditProfileController.cls
public class portalEditProfileController {

    public Contact userContact { get; set; }
    public Account family { get; set; }
    public Account familyCopy {get; set;}
    public Map<Id, Contact> familyContactMap { get; set; }

    public Boolean isEditing { get; set; }

    public String successMsg { get; set; }
    public String errorMsg { get; set; }

    public Map<String, Id> specialNeedRTs { get; set; }

    public Boolean hasSuccess { get {return String.isNotEmpty(successMsg);} set; }
    public Boolean hasError { get {return ApexPages.hasMessages() || String.isNotEmpty(errorMsg);} set; }

    public portalEditProfileController() {

        userContact = portalCore.userContact;

        family = [
                SELECT Id, Name, BillingStreet, BillingCity, BillingState, BillingPostalCode, BillingCountry, Home_Phone__c, Mobile_Phone__c, Email__c, Media_Permission_Denied__c,
                        Media_Permission_Functions__c, Media_Permission_Interviews__c, Media_Permission_Photos__c, Media_Permission_Photo_Share__c, Media_Permission_Pub__c, media_opt_in_take_video_photos__c, media_opt_in_share_participants__c, Media_Opt_in_Public_Sharing__c, Preferred_Event_Locations__c, Family_Interests__c,
                        npe01__One2OneContact__r.Requests_No_Newsletter__c, npe01__One2OneContact__r.Requests_no_Marketing_Materials__c,Image_Opt_In_Permission_Corporate_Child__c,
                        Media_Permission_All_2019__c, Media_permission_Public_2019__c, Media_permission_corporate_2019__c,media_opt_in_share_participants_child__c,Media_permission_Public_2019_Child__c, (SELECT Id, FirstName, LastName, Family_Member_Type__c, Birthdate, Swimming_Ability__c, Shirt_Size__c FROM Contacts WHERE npsp__Deceased__c = false AND Exclude_From_Portal__c = false)
                FROM Account
                WHERE Id = :userContact.AccountId
        ];

        familyContactMap = new Map<Id, Contact>();

        for (Contact fc : family.Contacts) {
            familyContactMap.put(fc.Id, fc);
        }

        specialNeedRTs = new Map<String, Id>();

        for (RecordType rt : [SELECT Id, Name, DeveloperName FROM RecordType WHERE sObjectType = 'Special_Needs__c' AND (DeveloperName = 'Dietary_Requirement' OR DeveloperName = 'Special_Need')]) {
            if (rt.DeveloperName == 'Dietary_Requirement') {
                specialNeedRTs.put('DietryNeeds', rt.Id);
            } else if (rt.DeveloperName == 'Special_Need') {
                specialNeedRTs.put('SpecialNeeds', rt.Id);
            }
        }

    }

    public void editFamily() {
        successMsg = '';
        errorMsg = '';
        isEditing = true;
    }

    public void saveFamily() {
        successMsg = '';
        errorMsg = '';
        isEditing = false;


        try {

            if (!family.media_opt_in_take_video_photos__c) {
                family.media_opt_in_share_participants__c = false;
                family.Media_permission_Public_2019__c = false;
                family.Media_permission_corporate_2019__c = false;
                family.media_opt_in_share_participants_child__c = false;
                family.Media_permission_Public_2019_Child__c = false;
                family.Image_Opt_In_Permission_Corporate_Child__c = false;
            }
            update family;


            if (String.isNotBlank(family.npe01__One2OneContact__c))
                update family.npe01__One2OneContact__r;

        } catch (DmlException ex) {

            System.debug(ex);
            ApexPages.addMessages(ex);
            return;

        }

        successMsg = 'Family details updated.';


    }

    public void cancelFamily() {
        Account acc = [
                SELECT media_opt_in_take_video_photos__c,
                        media_opt_in_share_participants__c,
                        Media_permission_Public_2019__c,
                        Media_permission_corporate_2019__c,
                        media_opt_in_share_participants_child__c,
                        Media_permission_Public_2019_Child__c,
                        Image_Opt_In_Permission_Corporate_Child__c
                FROM Account
                WHERE Id = :userContact.AccountId
        ];
        if(family.media_opt_in_take_video_photos__c != acc.media_opt_in_take_video_photos__c){
            family.media_opt_in_take_video_photos__c = !family.media_opt_in_take_video_photos__c;
        }
        family.media_opt_in_share_participants__c = acc.media_opt_in_share_participants__c;
        family.Media_permission_Public_2019__c = acc.Media_permission_Public_2019__c;
        family.Media_permission_corporate_2019__c = acc.Media_permission_corporate_2019__c;
        family.media_opt_in_share_participants_child__c = acc.media_opt_in_share_participants_child__c;
        family.Media_permission_Public_2019_Child__c = acc.Media_permission_Public_2019_Child__c;
        family.Image_Opt_In_Permission_Corporate_Child__c = acc.Image_Opt_In_Permission_Corporate_Child__c;
        successMsg = '';
        errorMsg = '';
        isEditing = false;

    }
    public void onchangeOfOptIn() {
        if(userContact.AccountId !=null){
            familyCopy = [
                    SELECT media_opt_in_share_participants__c,
                            Media_permission_Public_2019__c,
                            Media_permission_corporate_2019__c,
                            media_opt_in_share_participants_child__c,
                            Media_permission_Public_2019_Child__c,
                            Image_Opt_In_Permission_Corporate_Child__c
                            FROM Account
                    WHERE Id = :userContact.AccountId
            ];
            family.media_opt_in_share_participants__c = familyCopy.media_opt_in_share_participants__c;
            family.Media_permission_Public_2019__c = familyCopy.Media_permission_Public_2019__c;
            family.Media_permission_corporate_2019__c = familyCopy.Media_permission_corporate_2019__c;
            family.media_opt_in_share_participants_child__c = familyCopy.media_opt_in_share_participants_child__c;
            family.Media_permission_Public_2019_Child__c = familyCopy.Media_permission_Public_2019_Child__c;
            family.Image_Opt_In_Permission_Corporate_Child__c = familyCopy.Image_Opt_In_Permission_Corporate_Child__c;
        }else {
            errorMsg = '';
            errorMsg = 'Could not find the User Contact Id';
        }


    }


    public Id editContactId { get; set; }
    public Contact currentContact { get; set; }
    public Map<String, Special_Needs__c> currentNeeds { get; set; }
    public Integer countNeeds { get; set; }

    public void editContact() {
        successMsg = '';
        errorMsg = '';

        if (String.isNotEmpty(editContactId) && familyContactMap.containsKey(editContactId)) {
            currentContact = familyContactMap.get(editContactId);
        }

        currentNeeds = new Map<String, Special_Needs__c>();
        countNeeds = 0;
        Boolean hasDiet = false;
        Boolean hasNeeds = false;

        for (Special_Needs__c sn : [SELECT Id, AttributeType__c, Comments__c, Contact__c, Date__c, Long_Description__c FROM Special_Needs__c WHERE Contact__c = :editContactId]) {
            if (sn.AttributeType__c == 'DietryNeeds') {
                hasDiet = true;
            } else if (sn.AttributeType__c == 'SpecialNeeds') {
                hasNeeds = true;
            }

            currentNeeds.put(sn.Id, sn);
        }

        if (!hasDiet) {

            Special_Needs__c sNeed = new Special_Needs__c(AttributeType__c = 'DietryNeeds', Contact__c = editContactId, Date__c = Date.today());

            if (specialNeedRTs.containsKey(sNeed.AttributeType__c))
                sNeed.RecordTypeId = specialNeedRTs.get(sNeed.AttributeType__c);

            currentNeeds.put(String.valueOf(countNeeds++), sNeed);
        }

        if (!hasNeeds) {

            Special_Needs__c sNeed = new Special_Needs__c(AttributeType__c = 'SpecialNeeds', Contact__c = editContactId, Date__c = Date.today());

            if (specialNeedRTs.containsKey(sNeed.AttributeType__c))
                sNeed.RecordTypeId = specialNeedRTs.get(sNeed.AttributeType__c);

            currentNeeds.put(String.valueOf(countNeeds++), sNeed);
        }

        System.debug('currentNeeds: ' + currentNeeds);

    }

    public void saveContact() {

        try {

            update currentContact;

        } catch (DmlException ex) {

            System.debug(ex);
            ApexPages.addMessages(ex);
            return;

        }

        List<Special_Needs__c> updateNeeds = new List<Special_Needs__c>();

        for (Special_Needs__c sn : currentNeeds.values()) {
            if (String.isNotEmpty(sn.Long_Description__c)) {
                updateNeeds.add(sn);
            }
        }

        if (updateNeeds.size() > 0) {
            try {

                upsert updateNeeds;

            } catch (DmlException ex) {

                System.debug(ex);
                ApexPages.addMessages(ex);
                return;

            }
        }

        currentContact = null;
        currentNeeds = null;

        successMsg = 'Family member updated successfully.';

    }

    public void cancelContact() {

        currentContact = null;
        currentNeeds = null;

    }

    public String addType { get; set; }

    public void addSpecialNeed() {
        if (currentNeeds != null && String.isNotEmpty(addType)) {

            Special_Needs__c sNeed = new Special_Needs__c(AttributeType__c = addType, Contact__c = editContactId, Date__c = Date.today());

            if (specialNeedRTs.containsKey(sNeed.AttributeType__c))
                sNeed.RecordTypeId = specialNeedRTs.get(sNeed.AttributeType__c);

            currentNeeds.put(String.valueOf(countNeeds++), sNeed);
        }
    }

    public String removeNeedId { get; set; }

    public void removeSpecialNeed() {
        if (currentNeeds.containsKey(removeNeedId)) {
            Special_Needs__c rNeed = currentNeeds.remove(removeNeedId);

            if (removeNeedId InstanceOf ID) {

                try {

                    delete rNeed;

                } catch (DmlException ex) {

                    System.debug(ex);
                    ApexPages.addMessages(ex);
                    return;

                }

            }

        }
    }

    public void changeAllMediaOpt() {
        family.media_opt_in_share_participants__c = family.Media_Permission_All_2019__c;
        family.Media_permission_Public_2019__c = family.Media_Permission_All_2019__c;
        family.Media_permission_corporate_2019__c = family.Media_Permission_All_2019__c;
    }
}