force-app/main/default/objects/Account/fields/Family_Interests__c.field-meta.xml
<CustomField>
    <fullName>Family_Interests__c</fullName>
    <label>Family Interests</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Theme Parks</fullName>
            </value>
            <value>
                <fullName>Sports</fullName>
            </value>
            <value>
                <fullName>Arts &amp; Crafts</fullName>
            </value>
            <value>
                <fullName>Science &amp; Education</fullName>
            </value>
            <value>
                <fullName>Cooking</fullName>
            </value>
            <value>
                <fullName>Live Entertainment</fullName>
            </value>
            <value>
                <fullName>Animals</fullName>
            </value>
            <value>
                <fullName>Vehicles &amp; Remote Control</fullName>
            </value>
            <value>
                <fullName>Gaming &amp; Tech</fullName>
            </value>
            <value>
                <fullName>Toys &amp; Board Games</fullName>
            </value>
            <value>
                <fullName>Health &amp; Wellbeing</fullName>
            </value>
            <value>
                <fullName>Aquarium</fullName>
                <isActive>false</isActive>
                <label>Aquarium</label>
            </value>
            <value>
                <fullName>Bike</fullName>
                <isActive>false</isActive>
                <label>Bike</label>
            </value>
            <value>
                <fullName>Circus</fullName>
                <isActive>false</isActive>
                <label>Circus</label>
            </value>
            <value>
                <fullName>Dance</fullName>
                <isActive>false</isActive>
                <label>Dance</label>
            </value>
            <value>
                <fullName>Movies</fullName>
                <isActive>false</isActive>
                <label>Movies</label>
            </value>
            <value>
                <fullName>Music</fullName>
                <isActive>false</isActive>
                <label>Music</label>
            </value>
            <value>
                <fullName>Outdoors</fullName>
                <isActive>false</isActive>
                <label>Outdoors</label>
            </value>
            <value>
                <fullName>Sport - AFL</fullName>
                <isActive>false</isActive>
                <label>Sport - AFL</label>
            </value>
            <value>
                <fullName>Sport - Basketball</fullName>
                <isActive>false</isActive>
                <label>Sport - Basketball</label>
            </value>
            <value>
                <fullName>Sport - Cricket</fullName>
                <isActive>false</isActive>
                <label>Sport - Cricket</label>
            </value>
            <value>
                <fullName>Sport - Motor</fullName>
                <isActive>false</isActive>
                <label>Sport - Motor</label>
            </value>
            <value>
                <fullName>Sport - NRL</fullName>
                <isActive>false</isActive>
                <label>Sport - NRL</label>
            </value>
            <value>
                <fullName>Sport - Netball</fullName>
                <isActive>false</isActive>
                <label>Sport - Netball</label>
            </value>
            <value>
                <fullName>Sport - Other</fullName>
                <isActive>false</isActive>
                <label>Sport - Other</label>
            </value>
            <value>
                <fullName>Sport - Rugby Union</fullName>
                <isActive>false</isActive>
                <label>Sport - Rugby Union</label>
            </value>
            <value>
                <fullName>Sport - Soccer</fullName>
                <isActive>false</isActive>
                <label>Sport - Soccer</label>
            </value>
            <value>
                <fullName>Sport - Tennis</fullName>
                <isActive>false</isActive>
                <label>Sport - Tennis</label>
            </value>
            <value>
                <fullName>Theater</fullName>
                <isActive>false</isActive>
                <label>Theater</label>
            </value>
            <value>
                <fullName>Zoo</fullName>
                <isActive>false</isActive>
                <label>Zoo</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Family_Type__c.field-meta.xml
<CustomField>
    <fullName>Family_Type__c</fullName>
    <inlineHelpText>Graduating = Families who&apos;s youngest child is turning 13 this year
Former = Graduated Families or Families who have ceased contact</inlineHelpText>
    <label>Family Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Patient</fullName>
            </value>
            <value>
                <fullName>Patient - Alternate Household</fullName>
            </value>
            <value>
                <fullName>Restricted Family</fullName>
            </value>
            <value>
                <fullName>Bereaved Family</fullName>
            </value>
            <value>
                <fullName>Offspring Family</fullName>
            </value>
            <value>
                <fullName>Offspring Bereaved Family</fullName>
            </value>
            <value>
                <fullName>Test Family</fullName>
            </value>
            <value>
                <fullName>Graduating Patient Family</fullName>
            </value>
            <value>
                <fullName>Graduating Restricted Family</fullName>
            </value>
            <value>
                <fullName>Graduating Bereaved Family</fullName>
            </value>
            <value>
                <fullName>Graduating Offspring Family</fullName>
            </value>
            <value>
                <fullName>Graduating Offspring Bereaved Family</fullName>
            </value>
            <value>
                <fullName>Former Patient Family</fullName>
            </value>
            <value>
                <fullName>Former Bereaved Family</fullName>
            </value>
            <value>
                <fullName>Former Offspring Family</fullName>
            </value>
            <value>
                <fullName>Former Offspring Bereaved Family</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Preferred_Event_Locations__c.field-meta.xml
<CustomField>
    <fullName>Preferred_Event_Locations__c</fullName>
    <label>Preferred Event Locations</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Illawarra</fullName>
            </value>
            <value>
                <fullName>Sydney</fullName>
            </value>
            <value>
                <fullName>Northern New South Wales</fullName>
            </value>
            <value>
                <fullName>South Queensland</fullName>
            </value>
            <value>
                <fullName>Victoria</fullName>
            </value>
            <value>
                <fullName>South Australia</fullName>
            </value>
            <value>
                <fullName>Australian Capital Territory</fullName>
            </value>
            <value>
                <fullName>Newcastle</fullName>
            </value>
            <value>
                <fullName>Western Australia</fullName>
            </value>
            <value>
                <fullName>Central Queensland</fullName>
            </value>
            <value>
                <fullName>Tasmania</fullName>
            </value>
            <value>
                <fullName>North Queensland</fullName>
            </value>
            <value>
                <fullName>Northern Territory</fullName>
            </value>
            <value>
                <fullName>Queensland</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/recordTypes/Family.recordType-meta.xml
<RecordType>
    <fullName>Family</fullName>
    <active>true</active>
    <label>Family</label>
</RecordType>

force-app/main/default/objects/Contact/fields/Family_Type__c.field-meta.xml
<CustomField>
    <fullName>Family_Type__c</fullName>
    <formula>text(Account.Family_Type__c)</formula>
    <label>Family Type</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Preferred_Event_Locations__c.field-meta.xml
<CustomField>
    <fullName>Preferred_Event_Locations__c</fullName>
    <label>Preferred Event Locations</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Event_Locations</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/Regionv2__c.field-meta.xml
<CustomField>
    <fullName>Regionv2__c</fullName>
    <label>Region</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Regions</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/globalValueSets/Event_Locations.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Australian Capital Territory</fullName>
    </customValue>
    <customValue>
        <fullName>Central Queensland</fullName>
    </customValue>
    <customValue>
        <fullName>Illawarra</fullName>
    </customValue>
    <customValue>
        <fullName>National</fullName>
    </customValue>
    <customValue>
        <fullName>National Office</fullName>
    </customValue>
    <customValue>
        <fullName>Newcastle</fullName>
    </customValue>
    <customValue>
        <fullName>Northern New South Wales</fullName>
    </customValue>
    <customValue>
        <fullName>Northern Territory</fullName>
    </customValue>
    <customValue>
        <fullName>North Queensland</fullName>
    </customValue>
    <customValue>
        <fullName>Queensland</fullName>
    </customValue>
    <customValue>
        <fullName>South Australia</fullName>
    </customValue>
    <customValue>
        <fullName>South Queensland</fullName>
    </customValue>
    <customValue>
        <fullName>Sydney</fullName>
    </customValue>
    <customValue>
        <fullName>Tasmania</fullName>
    </customValue>
    <customValue>
        <fullName>Victoria</fullName>
    </customValue>
    <customValue>
        <fullName>Western Australia</fullName>
    </customValue>
    <masterLabel>Event Locations</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/Regions.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>ACT - Albury</fullName>
    </customValue>
    <customValue>
        <fullName>ACT - Bega</fullName>
    </customValue>
    <customValue>
        <fullName>ACT - Cooma</fullName>
    </customValue>
    <customValue>
        <fullName>ACT - Cowra</fullName>
    </customValue>
    <customValue>
        <fullName>ACT - Dubbo</fullName>
    </customValue>
    <customValue>
        <fullName>ACT - Forbes/Parkes</fullName>
    </customValue>
    <customValue>
        <fullName>ACT - Goulburn</fullName>
    </customValue>
    <customValue>
        <fullName>ACT - Local</fullName>
    </customValue>
    <customValue>
        <fullName>ACT - Narooma</fullName>
    </customValue>
    <customValue>
        <fullName>ACT - Orange</fullName>
    </customValue>
    <customValue>
        <fullName>ACT - Queanbeyan</fullName>
    </customValue>
    <customValue>
        <fullName>ACT - Wagga Wagga</fullName>
    </customValue>
    <customValue>
        <fullName>ACT - Young</fullName>
    </customValue>
    <customValue>
        <fullName>ILLA - Far South Coast</fullName>
    </customValue>
    <customValue>
        <fullName>ILLA - Local</fullName>
    </customValue>
    <customValue>
        <fullName>ILLA - Out of Area</fullName>
    </customValue>
    <customValue>
        <fullName>ILLA - Shoalhaven</fullName>
    </customValue>
    <customValue>
        <fullName>ILLA - Southern Highlands</fullName>
    </customValue>
    <customValue>
        <fullName>NCL-Central Coast</fullName>
    </customValue>
    <customValue>
        <fullName>NCL-Central West</fullName>
    </customValue>
    <customValue>
        <fullName>NCL-Hunter</fullName>
    </customValue>
    <customValue>
        <fullName>NCL-Manning</fullName>
    </customValue>
    <customValue>
        <fullName>NCL-Newcastle</fullName>
    </customValue>
    <customValue>
        <fullName>NNSW - Armidale</fullName>
    </customValue>
    <customValue>
        <fullName>NNSW - Byron/Ballina/lismore</fullName>
        <label>NNSW - Byron/Ballina/Lismore</label>
    </customValue>
    <customValue>
        <fullName>NNSW - Coffs Harbour</fullName>
    </customValue>
    <customValue>
        <fullName>NNSW - Glen Innes/Inverell</fullName>
    </customValue>
    <customValue>
        <fullName>NNSW - Other</fullName>
    </customValue>
    <customValue>
        <fullName>NNSW - Port Macquarie/Kempsey</fullName>
    </customValue>
    <customValue>
        <fullName>NNSW - Tamworth</fullName>
    </customValue>
    <masterLabel>Regions</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/vertic_UpdateRecordsBatchTest.cls
@IsTest
private class vertic_UpdateRecordsBatchTest {
    static testMethod void testBehavior() {

        Map<String, RecordType> rMap = new Map<String, RecordType>();
        for(RecordType r : [SELECT Id, DeveloperName FROM RecordType WHERE SObjectType = 'Account']){
            rMap.put(r.DeveloperName, r);
        }
            
        Account a = New Account( Name = 'Family', RecordTypeId = rMap.get('Family').Id, Family_Type__c = 'Patient',Regionv2__c='ACT - Albury', Preferred_Event_Locations__c='Sydney', Family_Interests__c = 'Sports');
        insert a;

        Contact contactVar = new Contact(
            FirstName = 'test',
            LastName = 'test',
            Email = 'test@test.com',
            AccountId = a.Id
        );
        insert contactVar;

        Test.startTest();

        Database.executeBatch(new vertic_UpdateRecordsBatch(
            Contact.SObjectType,
            'FirstName = \'test\''
        ));

        Test.stopTest();
    }
}