force-app/main/default/objects/Account/fields/Family_Type__c.field-meta.xml
<CustomField>
    <fullName>Family_Type__c</fullName>
    <inlineHelpText>Graduating = Families who&apos;s youngest child is turning 13 this year
Former = Graduated Families or Families who have ceased contact</inlineHelpText>
    <label>Family Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Patient</fullName>
            </value>
            <value>
                <fullName>Patient - Alternate Household</fullName>
            </value>
            <value>
                <fullName>Restricted Family</fullName>
            </value>
            <value>
                <fullName>Bereaved Family</fullName>
            </value>
            <value>
                <fullName>Offspring Family</fullName>
            </value>
            <value>
                <fullName>Offspring Bereaved Family</fullName>
            </value>
            <value>
                <fullName>Test Family</fullName>
            </value>
            <value>
                <fullName>Graduating Patient Family</fullName>
            </value>
            <value>
                <fullName>Graduating Restricted Family</fullName>
            </value>
            <value>
                <fullName>Graduating Bereaved Family</fullName>
            </value>
            <value>
                <fullName>Graduating Offspring Family</fullName>
            </value>
            <value>
                <fullName>Graduating Offspring Bereaved Family</fullName>
            </value>
            <value>
                <fullName>Former Patient Family</fullName>
            </value>
            <value>
                <fullName>Former Bereaved Family</fullName>
            </value>
            <value>
                <fullName>Former Offspring Family</fullName>
            </value>
            <value>
                <fullName>Former Offspring Bereaved Family</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/Age__c.field-meta.xml
<CustomField>
    <fullName>Age__c</fullName>
    <formula>IF( NOT (ISBLANK(  Deceased_Date__c )), YEAR(Deceased_Date__c) - YEAR(Birthdate),

IF( NOT( ISBLANK( Birthdate ) ) ,
IF( DATE( 2000 , MONTH( Birthdate ) , DAY( Birthdate ) ) &lt;= DATE( 2000 , MONTH( TODAY() ) , DAY( TODAY() ) ),
YEAR (Today()) - YEAR ( Birthdate ),
YEAR (Today()) - YEAR ( Birthdate ) -1 ),
NULL))</formula>
    <label>Age</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Family_Member_Type__c.field-meta.xml
<CustomField>
    <fullName>Family_Member_Type__c</fullName>
    <label>Family Member Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Aunt</fullName>
            </value>
            <value>
                <fullName>Deceased Parent</fullName>
            </value>
            <value>
                <fullName>Father</fullName>
            </value>
            <value>
                <fullName>Grandparent</fullName>
            </value>
            <value>
                <fullName>Hospital</fullName>
            </value>
            <value>
                <fullName>Legal Guardian</fullName>
            </value>
            <value>
                <fullName>Mother</fullName>
            </value>
            <value>
                <fullName>Patient</fullName>
            </value>
            <value>
                <fullName>School</fullName>
            </value>
            <value>
                <fullName>Sibling</fullName>
            </value>
            <value>
                <fullName>Stepfather</fullName>
            </value>
            <value>
                <fullName>Stepmother</fullName>
            </value>
            <value>
                <fullName>Stepsibling</fullName>
            </value>
            <value>
                <fullName>Uncle</fullName>
            </value>
            <value>
                <fullName>Cousin</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/Family_Type__c.field-meta.xml
<CustomField>
    <fullName>Family_Type__c</fullName>
    <formula>text(Account.Family_Type__c)</formula>
    <label>Family Type</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Gender__c.field-meta.xml
<CustomField>
    <fullName>Gender__c</fullName>
    <label>Gender</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Female</fullName>
            </value>
            <value>
                <fullName>Male</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
            <value>
                <fullName>Unknown</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/Preferred_First_Name__c.field-meta.xml
<CustomField>
    <fullName>Preferred_First_Name__c</fullName>
    <label>Preferred First Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Swimming_Ability__c.field-meta.xml
<CustomField>
    <fullName>Swimming_Ability__c</fullName>
    <label>Swimming Ability</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>0-25m</fullName>
            </value>
            <value>
                <fullName>25-50m</fullName>
            </value>
            <value>
                <fullName>50m and above</fullName>
            </value>
            <value>
                <fullName>Cannot swim</fullName>
            </value>
            <value>
                <fullName>Cannot swim in public pools</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Family_Attendance__c/Family_Attendance__c.object-meta.xml
<CustomObject>
    <description>Used for recording details of families attendance on programs, linked to familiy member attendance, family guest attendance campaign member and campaign</description>
    <label>Family Attendance</label>
    <nameField>
        <displayFormat>FA{00000}</displayFormat>
        <label>Family Attendance</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Family Attendances</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Family_Attendance__c/fields/Family__c.field-meta.xml
<CustomField>
    <fullName>Family__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Family</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Family Attendances</relationshipLabel>
    <relationshipName>Family_Attendances</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Family_Member_Attendance__c/Family_Member_Attendance__c.object-meta.xml
<CustomObject>
    <description>Used for recording individual family member attendances on programs linked to family attendance</description>
    <label>Family Member Attendance</label>
    <nameField>
        <displayFormat>FMA{00000}</displayFormat>
        <label>Family Member Attendance</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Family Member Attendance</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Family_Member_Attendance__c/fields/Age__c.field-meta.xml
<CustomField>
    <fullName>Age__c</fullName>
    <formula>TEXT(Contact__r.Age__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Age</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Family_Member_Attendance__c/fields/Companion__c.field-meta.xml
<CustomField>
    <fullName>Companion__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Companion</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>$Source.Event__c</field>
            <operation>equals</operation>
            <valueField>Volunteer_Attendance__c.Event__c</valueField>
        </filterItems>
        <infoMessage>The volunteer attendance record must be for the same event.</infoMessage>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Volunteer_Attendance__c</referenceTo>
    <relationshipLabel>Companion Children</relationshipLabel>
    <relationshipName>Companion_Children</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Family_Member_Attendance__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Family Member Attendance</relationshipLabel>
    <relationshipName>Family_Member_Attendance</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Family_Member_Attendance__c/fields/Family_Attendance__c.field-meta.xml
<CustomField>
    <fullName>Family_Attendance__c</fullName>
    <label>Family Attendance</label>
    <referenceTo>Family_Attendance__c</referenceTo>
    <relationshipLabel>Family Member Attendance</relationshipLabel>
    <relationshipName>Family_Member_Attendance</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Family_Member_Attendance__c/fields/Family_Member_Type__c.field-meta.xml
<CustomField>
    <fullName>Family_Member_Type__c</fullName>
    <formula>TEXT(Contact__r.Family_Member_Type__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Family Member Type</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Family_Member_Attendance__c/fields/Requires_Medication_or_Vitamins__c.field-meta.xml
<CustomField>
    <fullName>Requires_Medication_or_Vitamins__c</fullName>
    <label>Requires Medication or Vitamins</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>No</fullName>
                <default>true</default>
                <label>No</label>
            </value>
            <value>
                <fullName>Yes</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/VolunteerChildListController.cls
public class VolunteerChildListController {

    public String vaId{
        get;
        set {
            vaId = value;
            load();
        }
    }
    
    public List<Family_Member_Attendance__c> fmas{get;set;}
	
    public VolunteerChildListController() {
        
        load();
        
    }
    
    public void load() {
        if(String.isNotEmpty(vaId)) {
            
            fmas = [SELECT Id, contact__r.firstname,contact__r.lastname, Requires_Medication_or_Vitamins__c, contact__r.preferred_first_name__c,contact__r.gender__c, contact__r.Family_Member_Type__c , contact__r.Account.family_type__C, contact__r.Swimming_Ability__c,
 contact__r.age__C,
Family_Attendance__r.Family__r.Name, Family_Attendance__r.Family__r.BillingCity,Family_Attendance__r.Family__r.npe01__One2OneContact__r.preferred_first_name__c, 
Family_Attendance__r.Family__r.npe01__One2OneContact__r.mobilephone ,
Family_Attendance__r.Family__r.npe01__One2OneContact__r.phone  FROM Family_Member_Attendance__c WHERE Companion__C = :vaId];
            
        }
    }
}