force-app/main/default/objects/Account/fields/Puppet_Show__c.field-meta.xml
<CustomField>
    <fullName>Puppet_Show__c</fullName>
    <label>Puppet Show</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Account/fields/Puppet_Shows_12__c.field-meta.xml
<CustomField>
    <fullName>Puppet_Shows_12__c</fullName>
    <label>Puppet Shows &lt; 12</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Account/fields/Puppet_Shows_1_2__c.field-meta.xml
<CustomField>
    <fullName>Puppet_Shows_1_2__c</fullName>
    <label>Puppet Shows 1 - 2</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Account/fields/Puppet_Shows_2__c.field-meta.xml
<CustomField>
    <fullName>Puppet_Shows_2__c</fullName>
    <label>Puppet Shows 2 +</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Account/recordTypes/Family.recordType-meta.xml
<RecordType>
    <fullName>Family</fullName>
    <active>true</active>
    <label>Family</label>
</RecordType>

force-app/main/default/objects/Account/recordTypes/School.recordType-meta.xml
<RecordType>
    <fullName>School</fullName>
    <active>true</active>
    <label>School</label>
</RecordType>

force-app/main/default/objects/Contact/fields/School__c.field-meta.xml
<CustomField>
    <fullName>School__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>School</label>
    <lookupFilter>
        <active>false</active>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>School</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Students</relationshipLabel>
    <relationshipName>Students</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/PSP_Show_Attendee__c/PSP_Show_Attendee__c.object-meta.xml
<CustomObject>
    <description>Which children are attending a puppet show at a school who are part of a cq family.  Note this auto populated using a trigger based on children linked to the school who are 13 and under.</description>
    <label>PSP Attendee</label>
    <nameField>
        <displayFormat>PSPA-{000}</displayFormat>
        <label>Attendee</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>PSP Attendees</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/PSP_Show_Attendee__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <label>Attendee</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Contact.RecordTypeId</field>
            <operation>equals</operation>
            <value>Family Member</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipName>PSP_Show_Attendees</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/PSP_Show_Attendee__c/fields/Puppet_Show__c.field-meta.xml
<CustomField>
    <fullName>Puppet_Show__c</fullName>
    <label>Puppet Show</label>
    <referenceTo>PuppetShow__c</referenceTo>
    <relationshipName>PSP_Show_Attendees</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/PSP_Show_Attendee__c/fields/Show_Date__c.field-meta.xml
<CustomField>
    <fullName>Show_Date__c</fullName>
    <formula>Puppet_Show__r.Show_Date__c</formula>
    <label>Show Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/PuppetShow__c/PuppetShow__c.object-meta.xml
<CustomObject>
    <description>Primary School shows are managed through this.  Tours are managed as Campaigns.  Note that hospital visit by FLC&apos;s can also be managed through this object, despite the name.</description>
    <label>Puppet Show</label>
    <nameField>
        <displayFormat>PSP-{0000}</displayFormat>
        <label>PuppetShow ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Puppet Shows</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/PuppetShow__c/fields/Child_Requesting_Show__c.field-meta.xml
<CustomField>
    <fullName>Child_Requesting_Show__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Child Requesting Show</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Contact.RecordTypeId</field>
            <operation>equals</operation>
            <value>Family Member</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Puppet Show Requests</relationshipLabel>
    <relationshipName>Puppet_Shows_Requests</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/PuppetShow__c/fields/Performance_Group__c.field-meta.xml
<CustomField>
    <fullName>Performance_Group__c</fullName>
    <label>Performance Group</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>NSW/ACT</fullName>
            </value>
            <value>
                <fullName>QLD</fullName>
            </value>
            <value>
                <fullName>SA/NT</fullName>
            </value>
            <value>
                <fullName>WA</fullName>
            </value>
            <value>
                <fullName>VIC/TAS</fullName>
            </value>
            <value>
                <fullName>National</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/PuppetShow__c/fields/Puppet_Show_Name__c.field-meta.xml
<CustomField>
    <fullName>Puppet_Show_Name__c</fullName>
    <description>Searchable name for the puppet show, similar to Campaign Name</description>
    <inlineHelpText>Searchable name for the puppet show, similar to Campaign Name</inlineHelpText>
    <label>Puppet Show Name</label>
    <length>80</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/PuppetShow__c/fields/Show_Date__c.field-meta.xml
<CustomField>
    <fullName>Show_Date__c</fullName>
    <label>Show Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/PuppetShow__c/fields/Venue__c.field-meta.xml
<CustomField>
    <fullName>Venue__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Venue</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>notEqual</operation>
            <value>Family</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Puppet Shows</relationshipLabel>
    <relationshipName>Puppet_Shows</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/PuppetShowTest.cls
@isTest

public class PuppetShowTest {

    static testMethod void testPuppetShowTrigs(){
  //Setup school, child and puppet show.
  //
  RecordType SchoolTypeID = [SELECT Id,Name FROM RecordType WHERE sObjectType = 'Account' AND Name = 'School' LIMIT 1];
  RecordType FamilyMemberTypeID = [SELECT Id,Name FROM RecordType WHERE sObjectType = 'Contact' AND Name = 'Family Member' LIMIT 1];
  RecordType FamilyAccountTypeID = [SELECT Id,Name FROM RecordType WHERE sObjectType = 'Account' AND Name = 'Family' LIMIT 1];
		Account testFam = new Account (Name='TestFam', RecordTypeId =FamilyAccountTypeID.Id );
        insert testFam;
        Account testSchool = new Account (Name= 'TestSchool' ,BillingState='VIC', RecordTypeId = SchoolTypeID.Id);
      insert testSchool;
        //,,

      Contact testChild = new Contact(LastName='Test', FirstName='Child', Birthdate=Date.today(), RecordTypeId = FamilyMemberTypeID.Id,School__c  = testSchool.id,Accountid = testFam.Id);//,);
      insert testChild;
   //    Contact testChild = [SELECT ID,school__c FROM Contact where lastname = 'Test' LIMIT 1];
      PuppetShow__c testPuppet = new PuppetShow__c(Puppet_Show_Name__c = 'Puppet Test Show', Child_Requesting_Show__c= testChild.ID,show_date__c= date.today());
      insert testPuppet;


    // Account updatedAccount = [SELECT billingState FROM Account WHERE Id = :testAccount.Id];
    // System.assertEquals('CA', updatedAccount.billingState);
    //
      PuppetShow__c testPuppetResults = [SELECT  ID, Venue__C,Performance_group__C  from PuppetShow__c where  Id =  :testPuppet.Id];
             //Test that school is added to show.
      System.assertEquals (testSchool.id, testPuppetResults.Venue__C);
        system.assertEquals('VIC/TAS', testPuppetResults.Performance_Group__c);
        PSP_Show_Attendee__c testAttendees = [SELECT ID, Contact__c  from PSP_Show_Attendee__c where Puppet_Show__c =  :testPuppet.Id];
        system.assertEquals(testChild.Id, testAttendees.Contact__c);
        //Test Rollup.
        //
        Account testa = [SELECT ID,Puppet_Shows_12__c,Puppet_Shows_1_2__c,Puppet_Shows_2__c,Puppet_Show__c FROM ACCOUNT where id = :testFam.Id ];
        system.assertEquals(testa.Puppet_Show__c, date.today());
        system.assertEquals(testa.Puppet_Shows_12__c, 1);
        system.assertEquals(testa.Puppet_Shows_1_2__c, 0);
        system.assertEquals(testa.Puppet_Shows_2__c, 0);

		delete  testAttendees;
        testa = [SELECT ID,Puppet_Shows_12__c,Puppet_Shows_1_2__c,Puppet_Shows_2__c,Puppet_Show__c FROM ACCOUNT where id = :testFam.Id ];
         system.assertEquals(testa.Puppet_Show__c, null);
        system.assertEquals(testa.Puppet_Shows_12__c, 0);
        system.assertEquals(testa.Puppet_Shows_1_2__c, 0);
        system.assertEquals(testa.Puppet_Shows_2__c, 0);
                testPuppet = new PuppetShow__c(Puppet_Show_Name__c = 'Test Puppet Show 2', Child_Requesting_Show__c= testChild.ID,show_date__c= date.today().addMonths(-14));

      insert testPuppet;

     testPuppet = new PuppetShow__c(Puppet_Show_Name__c = 'Test Puppet Show 3', Child_Requesting_Show__c= testChild.ID,show_date__c= date.today().addMonths(-36));

      insert testPuppet;


        set<id> aset = new set<id>();
        aset.add(testa.id);
        campquality.puppetShowRollup(aSet);

    }


}