force-app/main/default/objects/Account/fields/Puppet_Show__c.field-meta.xml
<CustomField>
    <fullName>Puppet_Show__c</fullName>
    <label>Puppet Show</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Age__c.field-meta.xml
<CustomField>
    <fullName>Age__c</fullName>
    <formula>IF( NOT (ISBLANK(  Deceased_Date__c )), YEAR(Deceased_Date__c) - YEAR(Birthdate),

IF( NOT( ISBLANK( Birthdate ) ) ,
IF( DATE( 2000 , MONTH( Birthdate ) , DAY( Birthdate ) ) &lt;= DATE( 2000 , MONTH( TODAY() ) , DAY( TODAY() ) ),
YEAR (Today()) - YEAR ( Birthdate ),
YEAR (Today()) - YEAR ( Birthdate ) -1 ),
NULL))</formula>
    <label>Age</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Contact/fields/School__c.field-meta.xml
<CustomField>
    <fullName>School__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>School</label>
    <lookupFilter>
        <active>false</active>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>School</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Students</relationshipLabel>
    <relationshipName>Students</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/PSP_Show_Attendee__c/PSP_Show_Attendee__c.object-meta.xml
<CustomObject>
    <description>Which children are attending a puppet show at a school who are part of a cq family.  Note this auto populated using a trigger based on children linked to the school who are 13 and under.</description>
    <label>PSP Attendee</label>
    <nameField>
        <displayFormat>PSPA-{000}</displayFormat>
        <label>Attendee</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>PSP Attendees</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/PSP_Show_Attendee__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <label>Attendee</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Contact.RecordTypeId</field>
            <operation>equals</operation>
            <value>Family Member</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipName>PSP_Show_Attendees</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/PSP_Show_Attendee__c/fields/Puppet_Show__c.field-meta.xml
<CustomField>
    <fullName>Puppet_Show__c</fullName>
    <label>Puppet Show</label>
    <referenceTo>PuppetShow__c</referenceTo>
    <relationshipName>PSP_Show_Attendees</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/PuppetShow__c/PuppetShow__c.object-meta.xml
<CustomObject>
    <description>Primary School shows are managed through this.  Tours are managed as Campaigns.  Note that hospital visit by FLC&apos;s can also be managed through this object, despite the name.</description>
    <label>Puppet Show</label>
    <nameField>
        <displayFormat>PSP-{0000}</displayFormat>
        <label>PuppetShow ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Puppet Shows</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/PuppetShow__c/fields/Child_Requesting_Show__c.field-meta.xml
<CustomField>
    <fullName>Child_Requesting_Show__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Child Requesting Show</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Contact.RecordTypeId</field>
            <operation>equals</operation>
            <value>Family Member</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Puppet Show Requests</relationshipLabel>
    <relationshipName>Puppet_Shows_Requests</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/PuppetShow__c/fields/Performance_Group__c.field-meta.xml
<CustomField>
    <fullName>Performance_Group__c</fullName>
    <label>Performance Group</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>NSW/ACT</fullName>
            </value>
            <value>
                <fullName>QLD</fullName>
            </value>
            <value>
                <fullName>SA/NT</fullName>
            </value>
            <value>
                <fullName>WA</fullName>
            </value>
            <value>
                <fullName>VIC/TAS</fullName>
            </value>
            <value>
                <fullName>National</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/PuppetShow__c/fields/Venue__c.field-meta.xml
<CustomField>
    <fullName>Venue__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Venue</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>notEqual</operation>
            <value>Family</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Puppet Shows</relationshipLabel>
    <relationshipName>Puppet_Shows</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/PuppetShow.cls
public class PuppetShow {
      
    public static void AddVenue(List<PuppetShow__c> puppetShows) {

        Set<Id> childIds = new Set<Id>();
        Set<PuppetShow__c> psSet = new Set<PuppetShow__c>();

        for(PuppetShow__c ps : puppetShows) {
            if (String.isEmpty(ps.Venue__c) && String.isNotEmpty(ps.Child_Requesting_Show__c)) {
                childIds.add(ps.Child_Requesting_Show__c);
                psSet.add(ps);
            }
        }

        Map<Id, Contact> children = new Map<Id, Contact>([SELECT Id, School__c, School__r.BillingState FROM Contact where Id IN :childIds]);

        for(PuppetShow__c ps : psSet) {

            Contact child = children.get(ps.Child_Requesting_Show__c);

            if(child <> null && String.isNotEmpty(child.School__c) && String.isNotEmpty(child.School__r.BillingState)) {

                Account Venue = child.School__r;
                ps.Venue__c  = Venue.Id;

                if (Venue.BillingState == 'VIC' || Venue.BillingState == 'TAS'  )
                    ps.Performance_group__C = 'VIC/TAS';
                if (Venue.BillingState == 'SA' || Venue.BillingState == 'NT'  )
                    ps.Performance_group__C = 'SA/NT';
                if (Venue.BillingState == 'NSW' || Venue.BillingState == 'ACT'  )
                    ps.Performance_group__C = 'NSW/ACT';
                if (Venue.BillingState == 'QLD' )
                    ps.Performance_group__C = 'QLD';
                if (Venue.BillingState == 'WA' )
                    ps.Performance_group__C = 'WA';

            }

        }
        
    }

    public static void AddKids(List<PuppetShow__c> psList) {

        List<Id> acctIds = new List<Id>();
        List<PSP_Show_Attendee__c> pspattendees = new List<PSP_Show_Attendee__c>();

        for(PuppetShow__c ps : psList) {
            if(String.isNotEmpty(ps.Venue__c)) {
                acctIds.add(ps.Venue__c);
            }
        }

        Map<Id, Account> venueMap = new Map<Id, Account>([SELECT Id, (SELECT Id, Name FROM Students__r WHERE age__C < 14) FROM Account WHERE Id IN :acctIds]);

        for(PuppetShow__c ps : psList) {

            if(String.isNotEmpty(ps.Venue__c) && venueMap.containsKey(ps.Venue__c)) {
                for(Contact c : venueMap.get(ps.Venue__c).Students__r) {

                    pspattendees.add(new PSP_Show_Attendee__c(Puppet_Show__c = ps.Id, Contact__c = c.Id));

                }
            }

        }

        try {
            insert pspattendees;
        } catch(DmlException ex) {
            System.debug(ex);
        }

    }
}