force-app/main/default/objects/Account/fields/Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Start_Date__c</fullName>
    <defaultValue>TODAY()</defaultValue>
    <label>Start Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Exclude_From_Portal__c.field-meta.xml
<CustomField>
    <fullName>Exclude_From_Portal__c</fullName>
    <defaultValue>true</defaultValue>
    <label>Exclude From Portal</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Peak_Period__c/Peak_Period__c.object-meta.xml
<CustomObject>
    <description>Used for family retreat peak period settings.  See Property__C</description>
    <label>Peak Period</label>
    <nameField>
        <label>Peak period restrictions Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Peak Periods</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Peak_Period__c/fields/End_Date__c.field-meta.xml
<CustomField>
    <fullName>End_Date__c</fullName>
    <description>Peak period end date</description>
    <inlineHelpText>Peak period end date</inlineHelpText>
    <label>End Date</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Peak_Period__c/fields/Length_of_stay__c.field-meta.xml
<CustomField>
    <fullName>Length_of_stay__c</fullName>
    <label>Length of stay</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>7 days (6 nights)</fullName>
            </value>
            <value>
                <fullName>6 days (5 nights)</fullName>
            </value>
            <value>
                <fullName>5 days (4 nights)</fullName>
            </value>
            <value>
                <fullName>4 days (3 nights)</fullName>
            </value>
            <value>
                <fullName>3 days (2 nights)</fullName>
            </value>
            <value>
                <fullName>2 days (1 nights)</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Peak_Period__c/fields/Property__c.field-meta.xml
<CustomField>
    <fullName>Property__c</fullName>
    <label>Property</label>
    <referenceTo>Property__c</referenceTo>
    <relationshipLabel>Peak Periods</relationshipLabel>
    <relationshipName>Peak_Periods</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Peak_Period__c/fields/Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Start_Date__c</fullName>
    <description>Peak period start date</description>
    <inlineHelpText>Peak period start date</inlineHelpText>
    <label>Start Date</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Property__c/Property__c.object-meta.xml
<CustomObject>
    <description>Used for family retreat - record of properties available for families to book from.  See documentation on Retreat booking under clouding around files for full details.</description>
    <label>Property</label>
    <nameField>
        <label>Property Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Properties</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Property__c/fields/Address__c.field-meta.xml
<CustomField>
    <fullName>Address__c</fullName>
    <description>Complete address shown on the portal</description>
    <inlineHelpText>Complete address shown on the portal</inlineHelpText>
    <label>Address</label>
    <length>2000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Property__c/fields/Available_for_booking_portal__c.field-meta.xml
<CustomField>
    <fullName>Available_for_booking_portal__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Shows property on the booking portal</description>
    <inlineHelpText>Shows property on the booking portal</inlineHelpText>
    <label>Available for booking portal</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Property__c/fields/Can_extend_to_full_week_an_own_expense__c.field-meta.xml
<CustomField>
    <fullName>Can_extend_to_full_week_an_own_expense__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Option to extend to the full week at the
family’s own expense</description>
    <inlineHelpText>Option to extend to the full week at the
family’s own expense</inlineHelpText>
    <label>Can extend to full week an own expense</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Property__c/fields/Guests__c.field-meta.xml
<CustomField>
    <fullName>Guests__c</fullName>
    <description>Number of guests e.g. ( 7 = Sleeps 7 people)</description>
    <inlineHelpText>Number of guests e.g. ( 7 = Sleeps 7 people)</inlineHelpText>
    <label>Guests</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Property__c/fields/Length_of_stay__c.field-meta.xml
<CustomField>
    <fullName>Length_of_stay__c</fullName>
    <label>Length of stay</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>8 days (7 nights)</fullName>
            </value>
            <value>
                <fullName>7 days (6 nights)</fullName>
            </value>
            <value>
                <fullName>6 days (5 nights)</fullName>
            </value>
            <value>
                <fullName>5 days (4 nights)</fullName>
            </value>
            <value>
                <fullName>4 days (3 nights)</fullName>
            </value>
            <value>
                <fullName>3 days (2 nights)</fullName>
            </value>
            <value>
                <fullName>2 days (1 night)</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Property__c/fields/Not_available_on_weekend__c.field-meta.xml
<CustomField>
    <fullName>Not_available_on_weekend__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Not available on weekend</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Property__c/fields/Peak_period_restrictions__c.field-meta.xml
<CustomField>
    <fullName>Peak_period_restrictions__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Restrictions for peak/off peak times</description>
    <inlineHelpText>Restrictions for peak/off peak times</inlineHelpText>
    <label>Peak period restrictions</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Property__c/fields/Portal_Description__c.field-meta.xml
<CustomField>
    <fullName>Portal_Description__c</fullName>
    <label>Portal Description</label>
    <length>32768</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/Property__c/fields/State__c.field-meta.xml
<CustomField>
    <fullName>State__c</fullName>
    <label>State</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>NSW</fullName>
            </value>
            <value>
                <fullName>QLD</fullName>
            </value>
            <value>
                <fullName>SA</fullName>
            </value>
            <value>
                <fullName>TAS</fullName>
            </value>
            <value>
                <fullName>VIC</fullName>
            </value>
            <value>
                <fullName>WA</fullName>
            </value>
            <value>
                <fullName>NT</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Property__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>General</fullName>
                <default>true</default>
                <label>General</label>
            </value>
            <value>
                <fullName>Salamander</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Retreat_Booking__c/Retreat_Booking__c.object-meta.xml
<CustomObject>
    <description>Used for retreat bookings through family portal.  See Property__C.</description>
    <label>Retreat Booking</label>
    <nameField>
        <displayFormat>RB-{000000}</displayFormat>
        <label>Booking Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Retreat Bookings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Retreat_Booking__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Retreat Bookings</relationshipLabel>
    <relationshipName>Retreat_Bookings</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Retreat_Booking__c/fields/Guests__c.field-meta.xml
<CustomField>
    <fullName>Guests__c</fullName>
    <label>Guests</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Retreat_Booking__c/fields/Length_Of_Stay__c.field-meta.xml
<CustomField>
    <fullName>Length_Of_Stay__c</fullName>
    <formula>Check_Out_Date__c -  Check_In_Date__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Length Of Stay</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Retreat_Booking__c/fields/Property__c.field-meta.xml
<CustomField>
    <fullName>Property__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Property</label>
    <referenceTo>Property__c</referenceTo>
    <relationshipLabel>Retreat Bookings</relationshipLabel>
    <relationshipName>Retreat_Bookings</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Retreat_Booking__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Confirmed</fullName>
            </value>
            <value>
                <fullName>Declined</fullName>
            </value>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Rebooked</fullName>
            </value>
            <value>
                <fullName>Waitlisted Q1</fullName>
            </value>
            <value>
                <fullName>Waitlisted Q2</fullName>
            </value>
            <value>
                <fullName>Waitlisted Q3</fullName>
            </value>
            <value>
                <fullName>Waitlisted Q4</fullName>
            </value>
            <value>
                <fullName>Waitlisted</fullName>
                <isActive>false</isActive>
                <label>Waitlisted</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/portalRespiteControllerTest.cls
@IsTest
private class portalRespiteControllerTest {
    @IsTest
    static void testPortalRespiteController() {

        User u = [select Id,AccountId from User WHERE CommunityNickname='portaluser'];

        system.runAs(u) {

            Test.startTest();

            Test.setCurrentPage(Page.portalRespite);

            portalRespiteController prc = new portalRespiteController();

            Test.stopTest();

        }


    }

    @IsTest
    static void testPortalRetreatBookingPeak() {

        User u = [select Id,AccountId,ContactId from User WHERE CommunityNickname='portaluser'];

        Account a1 = new Account(Name='t1');
        insert a1;

        Contact c1 = new Contact(FirstName='extra', LastName='guest', Email='text@user.org',AccountId = a1.Id);
        insert c1;

        system.runAs(u) {

            Test.startTest();

            Property__c pPeak = new Property__c( Name = 'pPeak',Address__c = 'test Address',Available_for_booking_portal__c = true,
                    Can_extend_to_full_week_an_own_expense__c = false,Guests__c = 5,Length_of_stay__c='5 days (4 nights)',
                    Peak_period_restrictions__c = true,Portal_Description__c = 'test Desc',State__c = 'VIC',
                    Type__c = 'General',Not_available_on_weekend__c = false);

            insert pPeak;

            Peak_Period__c pp = new Peak_Period__c(Name='Holiday', Start_Date__c = System.today() + 20 ,
                                End_Date__c =System.today()+40,Length_of_stay__c='3 days (2 nights)',Property__c = pPeak.Id);

            insert pp;


            Retreat_Booking__c rb2 = new Retreat_Booking__c( Status__c = 'Waitlisted',Check_In_Date__c = System.today() +10,
                    Check_Out_Date__c = System.today()+15,Property__c = pPeak.Id,Contact__c = u.ContactId);



            Test.setCurrentPage(Page.portalRetreatBooking);

            ApexPages.currentPage().getParameters().put('pid', pPeak.Id);

            //portalRetreatBookingController prbc = new portalRetreatBookingController();

            //String los2 = portalRetreatBookingController.lengthOfStay(pPeak.Id,'01/03/2019');

            Test.stopTest();

        }


    }

    @IsTest
    static void testPortalRetreatBookingSalamander() {

        User u = [select Id,AccountId,ContactId from User WHERE CommunityNickname='portaluser'];

        Account a1 = new Account(Name='t1');
        insert a1;

        Contact c1 = new Contact(AccountId=a1.Id, FirstName='extra', LastName='guest', Email='text@user.org');
        insert c1;

        system.runAs(u) {

            Test.startTest();

            Property__c pSalamander = new Property__c( Name = 'pSalamander',Address__c = 'test Address',Available_for_booking_portal__c = true,
                    Can_extend_to_full_week_an_own_expense__c = false,Guests__c = 5,Length_of_stay__c='5 days (4 nights)',
                    Peak_period_restrictions__c = false,Portal_Description__c = 'test Desc',State__c = 'VIC',
                    Type__c = 'Salamander',Not_available_on_weekend__c = false);

            insert pSalamander;


            Retreat_Booking__c rb = new Retreat_Booking__c( Status__c = 'Waitlisted Q1',Check_In_Date__c = System.today() - 5,
                    Check_Out_Date__c = System.today(),Property__c = pSalamander.Id,Contact__c = u.ContactId);

            insert rb;


            Test.setCurrentPage(Page.portalRetreatBooking);

            ApexPages.currentPage().getParameters().put('pid', pSalamander.Id);

            portalRetreatBookingController prbc = new portalRetreatBookingController();

            String los = portalRetreatBookingController.lengthOfStay(pSalamander.Id,'08/02/2019');

            List<Map<String, String>> rb1 =  portalRetreatBookingController.searchExistingBookings(pSalamander.Id);

            prbc.getFamily();



            Set<Id> s = new Set<Id>();
            s.add(u.ContactId);

            List<Contact> e = new List<Contact>();
            e.add(c1);

            portalRetreatBookingController.bookingWrapper bookWrap = new portalRetreatBookingController.bookingWrapper();
            bookWrap.booking = rb;
            bookWrap.guestRegister = true;
            bookWrap.familyGuest = s;
            bookWrap.extraGuest = e;

            prbc.bw = bookWrap ;

   //         prbc.removeGuestId = 1;

            prbc.countFamilychecked();
            prbc.addExtraGuest();
  //          prbc.removeExtraGuest();
            prbc.countGuestList();

            PageReference pr = prbc.save();


            Test.stopTest();

        }


    }

    @IsTest
    static void testPortalRetreatBookingWeekend() {

        User u = [select Id,AccountId,ContactId from User WHERE CommunityNickname='portaluser'];

        Account a1 = new Account(Name='t1');
        insert a1;

        Contact c1 = new Contact(FirstName='extra', LastName='guest', Email='text@user.org',AccountId = a1.Id);
        insert c1;

        system.runAs(u) {

            Test.startTest();

            Property__c pWeekend = new Property__c( Name = 'pWeekend',Address__c = 'test Address',Available_for_booking_portal__c = true,
                    Can_extend_to_full_week_an_own_expense__c = false,Guests__c = 5,Length_of_stay__c='5 days (4 nights)',
                    Peak_period_restrictions__c = false,Portal_Description__c = 'test Desc',State__c = 'VIC',
                    Type__c = 'General',Not_available_on_weekend__c = true);

            insert pWeekend;

            Retreat_Booking__c rb = new Retreat_Booking__c( Status__c = 'Waitlisted Q1',Check_In_Date__c = System.today() - 5,
                    Check_Out_Date__c = System.today(),Property__c = pWeekend.Id,Contact__c = u.ContactId);

            insert rb;

//Updated all Status__C = Pending to Status__C= Waitlisted. Megan D 1/12/2023

            Test.setCurrentPage(Page.portalRetreatBooking);

            ApexPages.currentPage().getParameters().put('pid', pWeekend.Id);

            portalRetreatBookingController prbc = new portalRetreatBookingController();

            String los1 = portalRetreatBookingController.lengthOfStay(pWeekend.Id,'11/02/2019');

            Test.stopTest();

        }


    }

    @IsTest
    static void retreatValidationTest() {

        User u = [select Id,AccountId,ContactId from User WHERE CommunityNickname='portaluser'];

        Account a1 = new Account(Name='t1');
        insert a1;

        Contact c1 = new Contact(FirstName='extra', LastName='guest', Email='text@user.org',AccountId = a1.Id);
        insert c1;

        system.runAs(u) {

            Test.startTest();

            Property__c pPeak = new Property__c( Name = 'pPeak',Address__c = 'test Address',Available_for_booking_portal__c = true,
                    Can_extend_to_full_week_an_own_expense__c = false,Guests__c = 5,Length_of_stay__c='5 days (4 nights)',
                    Peak_period_restrictions__c = true,Portal_Description__c = 'test Desc',State__c = 'VIC',
                    Type__c = 'General',Not_available_on_weekend__c = false);

            insert pPeak;

            Peak_Period__c pp = new Peak_Period__c(Name='Holiday', Start_Date__c = System.today() + 20 ,
                    End_Date__c =System.today()+40,Length_of_stay__c='3 days (2 nights)',Property__c = pPeak.Id);

            insert pp;

            Peak_Period__c pp1 = new Peak_Period__c(Name='Holiday1', Start_Date__c = System.today() + 30 ,
                    End_Date__c =System.today()+40,Length_of_stay__c='3 days (2 nights)',Property__c = pPeak.Id);

            try{
                insert pp1;
            }catch (Exception e){
                System.debug('Insertion failed');
            }



            Test.stopTest();

        }


    }

    private static User createPortalUser() {

        Account a = new Account(Name='Portal User Account');
        insert a;

        Contact c = new Contact(FirstName='Portal', LastName='User', Email='portal@user.org', AccountId=a.Id,npsp__Deceased__c = false,Exclude_From_Portal__c = false);
        insert c;

        User u = new User(ContactId=c.Id, FirstName=c.FirstName, LastName=c.LastName, ProfileId=CommunityMemberProfile.Id, UserName=c.Email, Email=c.Email, TimeZoneSidKey='Australia/Sydney', Alias='puser', CommunityNickname='portaluser', LocaleSidKey='en_AU', EmailEncodingKey='ISO-8859-1', LanguageLocaleKey='en_US');
        insert u;



        u.Contact = c;
        u.Contact.Account = a;

        return u;
    }

    private static Profile CommunityMemberProfile {
        get {
            if (CommunityMemberProfile == null) {
                try {
                    CommunityMemberProfile = [SELECT Id FROM Profile WHERE Name = 'My Camp Quality Members' LIMIT 1];
                } catch (Exception e) {
                    throw e;
                }
            }

            return CommunityMemberProfile;
        }
        set;
    }

    @testSetup static void SetupTests() {
        portalRespiteControllerTest.createPortalUser();
    }

}