force-app/main/default/objects/Account/fields/Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Start_Date__c</fullName>
    <defaultValue>TODAY()</defaultValue>
    <label>Start Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Campaign/fields/Registrations_Closed__c.field-meta.xml
<CustomField>
    <fullName>Registrations_Closed__c</fullName>
    <inlineHelpText>Date and time Event registrations close</inlineHelpText>
    <label>Registrations Closed</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Campaign/fields/Registrations_Open__c.field-meta.xml
<CustomField>
    <fullName>Registrations_Open__c</fullName>
    <inlineHelpText>Date and time Event can accept registrations</inlineHelpText>
    <label>Registrations Open</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Campaign/fields/Volunteer_Attendance__c.field-meta.xml
<CustomField>
    <fullName>Volunteer_Attendance__c</fullName>
    <label>Volunteer Attendance</label>
    <summaryFilterItems>
        <field>Volunteer_Attendance__c.Attendance__c</field>
        <operation>equals</operation>
        <value>Attended</value>
    </summaryFilterItems>
    <summaryForeignKey>Volunteer_Attendance__c.Event__c</summaryForeignKey>
    <summaryOperation>count</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Campaign/recordTypes/Volunteer.recordType-meta.xml
<RecordType>
    <fullName>Volunteer</fullName>
    <active>true</active>
    <label>Volunteer</label>
</RecordType>

force-app/main/default/objects/Contact/fields/Exclude_From_Portal__c.field-meta.xml
<CustomField>
    <fullName>Exclude_From_Portal__c</fullName>
    <defaultValue>true</defaultValue>
    <label>Exclude From Portal</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Volunteer_Attendance__c.field-meta.xml
<CustomField>
    <fullName>Volunteer_Attendance__c</fullName>
    <label>Last Volunteer Attendance</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Contact/recordTypes/Volunteer.recordType-meta.xml
<RecordType>
    <fullName>Volunteer</fullName>
    <active>true</active>
    <label>Volunteer</label>
</RecordType>

force-app/main/default/objects/Page__c/Page__c.object-meta.xml
<CustomObject>
    <description>Used to create portal pages in the programs Salesforce community</description>
    <label>Page</label>
    <nameField>
        <label>Page Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Pages</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Page__c/fields/Site__c.field-meta.xml
<CustomField>
    <fullName>Site__c</fullName>
    <label>Site</label>
    <referenceTo>Site__c</referenceTo>
    <relationshipLabel>Pages</relationshipLabel>
    <relationshipName>Pages</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Registration_Period__c/Registration_Period__c.object-meta.xml
<CustomObject>
    <description>An alternative type of session used for programs where people can choose one or more registration options for a program.</description>
    <label>Registration Period</label>
    <nameField>
        <label>Registration Period Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Registration Periods</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Registration_Period__c/fields/Campaign__c.field-meta.xml
<CustomField>
    <fullName>Campaign__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Campaign</label>
    <referenceTo>Campaign</referenceTo>
    <relationshipLabel>Registration Periods</relationshipLabel>
    <relationshipName>Registration_Periods</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Registration_Type__c/Registration_Type__c.object-meta.xml
<CustomObject>
    <description>Part of the invitation process for programs.  Registration types are used to store the settings for each type of registeration for an event (i.e. family, volunter)</description>
    <label>Registration Type</label>
    <nameField>
        <label>Registration Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Registration Types</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Registration_Type__c/fields/Event__c.field-meta.xml
<CustomField>
    <fullName>Event__c</fullName>
    <label>Event</label>
    <referenceTo>Campaign</referenceTo>
    <relationshipLabel>Registration Types</relationshipLabel>
    <relationshipName>Registration_Types</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Registration_Type__c/fields/Number_Available__c.field-meta.xml
<CustomField>
    <fullName>Number_Available__c</fullName>
    <inlineHelpText>Maximum Number of Tickets Available</inlineHelpText>
    <label>Number Available</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Registration_Type__c/recordTypes/Volunteer.recordType-meta.xml
<RecordType>
    <fullName>Volunteer</fullName>
    <active>true</active>
    <description>Volunteer Registration</description>
    <label>Volunteer</label>
</RecordType>

force-app/main/default/objects/Registration_Type_Period__c/Registration_Type_Period__c.object-meta.xml
<CustomObject>
    <description>Used to link registration types with registration periods.</description>
    <label>Registration Type Period</label>
    <nameField>
        <displayFormat>RTP{00000}</displayFormat>
        <label>Registration Type Period Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Registration Type Periods</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Registration_Type_Period__c/fields/Registration_Period__c.field-meta.xml
<CustomField>
    <fullName>Registration_Period__c</fullName>
    <label>Registration Period</label>
    <referenceTo>Registration_Period__c</referenceTo>
    <relationshipLabel>Registration Type Periods</relationshipLabel>
    <relationshipName>Registration_Type_Periods</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Registration_Type_Period__c/fields/Registration_Type__c.field-meta.xml
<CustomField>
    <fullName>Registration_Type__c</fullName>
    <label>Registration Type</label>
    <referenceTo>Registration_Type__c</referenceTo>
    <relationshipLabel>Registration Type Periods</relationshipLabel>
    <relationshipName>Registration_Type_Periods</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Site__c/Site__c.object-meta.xml
<CustomObject>
    <description>Portal custom object for the different views/subsites on portal i.e. Family Volunteer Corporate Volunteer</description>
    <label>Site</label>
    <nameField>
        <label>Site Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sites</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Special_Needs__c/Special_Needs__c.object-meta.xml
<CustomObject>
    <label>Dietary &amp; Special Needs</label>
    <nameField>
        <displayFormat>SN - {0000}</displayFormat>
        <label>Special Needs Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Dietary &amp; Special Needs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Special_Needs__c/fields/AttributeType__c.field-meta.xml
<CustomField>
    <fullName>AttributeType__c</fullName>
    <label>Attribute Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>DietryNeeds</fullName>
                <label>Dietary Needs</label>
            </value>
            <value>
                <fullName>SpecialNeeds</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Special_Needs__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipName>Special_Needs</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Special_Needs__c/fields/Long_Description__c.field-meta.xml
<CustomField>
    <fullName>Long_Description__c</fullName>
    <label>Long Description</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>ADD</fullName>
            </value>
            <value>
                <fullName>ADHD</fullName>
            </value>
            <value>
                <fullName>Allergic - All Nuts</fullName>
            </value>
            <value>
                <fullName>Allergic - Buckwheat</fullName>
            </value>
            <value>
                <fullName>Allergic - Eggs</fullName>
            </value>
            <value>
                <fullName>Allergic - Fish</fullName>
            </value>
            <value>
                <fullName>Allergic - Garlic</fullName>
            </value>
            <value>
                <fullName>Allergic - Kiwi Fruit</fullName>
            </value>
            <value>
                <fullName>Allergic - Mushrooms</fullName>
            </value>
            <value>
                <fullName>Allergic - Oranges</fullName>
            </value>
            <value>
                <fullName>Allergic - Other</fullName>
            </value>
            <value>
                <fullName>Allergic - Parmesan Cheese</fullName>
            </value>
            <value>
                <fullName>Allergic - Peanuts</fullName>
            </value>
            <value>
                <fullName>Allergic - Pork</fullName>
            </value>
            <value>
                <fullName>Allergic - Prawns</fullName>
            </value>
            <value>
                <fullName>Allergic - Seafood</fullName>
            </value>
            <value>
                <fullName>Allergic - Sesame</fullName>
            </value>
            <value>
                <fullName>Allergic - Shellfish</fullName>
            </value>
            <value>
                <fullName>Allergic - Tomatoes</fullName>
            </value>
            <value>
                <fullName>Allergic - Yeast</fullName>
            </value>
            <value>
                <fullName>Allergic to dust mites</fullName>
            </value>
            <value>
                <fullName>Allergy - Angel Cream</fullName>
            </value>
            <value>
                <fullName>Allergy - Antibiotic Erythromycin</fullName>
            </value>
            <value>
                <fullName>Allergy - Asparaginase</fullName>
            </value>
            <value>
                <fullName>Allergy - Asprin</fullName>
            </value>
            <value>
                <fullName>Allergy - Bactrim</fullName>
            </value>
            <value>
                <fullName>Allergy - Band Aids</fullName>
            </value>
            <value>
                <fullName>Allergy - Bee Stings</fullName>
            </value>
            <value>
                <fullName>Allergy - Bleomycin</fullName>
            </value>
            <value>
                <fullName>Allergy - Brietal</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Volunteer_Attendance__c/Volunteer_Attendance__c.object-meta.xml
<CustomObject>
    <description>Used for tracking volunteer attendance on programs. Linked to campaign member for communication, campaign for program, contact for volunteer</description>
    <label>Volunteer Attendance</label>
    <nameField>
        <displayFormat>VA{00000}</displayFormat>
        <label>Volunteer Attendance</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Volunteer Attendances</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Volunteer_Attendance__c/fields/Attendance__c.field-meta.xml
<CustomField>
    <fullName>Attendance__c</fullName>
    <label>Attendance</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Invited</fullName>
            </value>
            <value>
                <fullName>Request to Attend</fullName>
            </value>
            <value>
                <fullName>Accepted</fullName>
            </value>
            <value>
                <fullName>Attended</fullName>
            </value>
            <value>
                <fullName>Declined</fullName>
            </value>
            <value>
                <fullName>Unsuccessful</fullName>
            </value>
            <value>
                <fullName>No Show</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Medical Withdrawal</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Volunteer_Attendance__c/fields/Event__c.field-meta.xml
<CustomField>
    <fullName>Event__c</fullName>
    <label>Event</label>
    <referenceTo>Campaign</referenceTo>
    <relationshipLabel>Volunteer Attendances</relationshipLabel>
    <relationshipName>Volunteer_Attendances</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Volunteer_Attendance__c/fields/Registration_Period__c.field-meta.xml
<CustomField>
    <fullName>Registration_Period__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Registration Period</label>
    <referenceTo>Registration_Period__c</referenceTo>
    <relationshipLabel>Volunteer Attendances</relationshipLabel>
    <relationshipName>Volunteer_Attendances</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Volunteer_Attendance__c/fields/Registration_Type__c.field-meta.xml
<CustomField>
    <fullName>Registration_Type__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Registration Type</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>$Source.Event__c</field>
            <operation>equals</operation>
            <valueField>Registration_Type__c.Event__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Registration_Type__c</referenceTo>
    <relationshipLabel>Volunteer Attendances</relationshipLabel>
    <relationshipName>Volunteer_Attendances</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Volunteer_Attendance__c/fields/Volunteer__c.field-meta.xml
<CustomField>
    <fullName>Volunteer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Volunteer</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Volunteer Attendances</relationshipLabel>
    <relationshipName>Volunteer_Attendances</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/portalVolunteerEventsControllerTest.cls
@isTest
private class portalVolunteerEventsControllerTest {
  
  @isTest static void test_method_one() {
      
    User u = [SELECT Id FROM User WHERE Username = 'tester@noemail.com'];

    system.runAs(u) {
            
      Test.startTest();

      Test.setCurrentPage(Page.portalEvents);

      ApexPages.currentPage().getParameters().put('p', 'pageName');

      portalVolunteerEventsController pec = new portalVolunteerEventsController();

      pec.getEventTypes();

      Test.stopTest();

        }

  }
  
  @isTest static void test_method_two() {
    
    User u = [SELECT Id FROM User WHERE Username = 'tester@noemail.com'];
    Campaign cmp = [SELECT Id FROM Campaign WHERE Name = 'Campaign Name' LIMIT 1];
 
    system.runAs(u) {
            
      Test.startTest();

      Test.setCurrentPage(Page.portalEvent);

      ApexPages.currentPage().getParameters().put('p', 'pageName');
      ApexPages.currentPage().getParameters().put('e', cmp.Id);

      portalVolunteerEventController pec = new portalVolunteerEventController();

      System.assertEquals(false, pec.cancellationAvailable);
      System.assertEquals(true, pec.registrationAvailable);

      pec.beginRegistration();
      pec.registerBookingId = new List<String>(pec.bookings.keySet())[0];

      ApexPages.currentPage().getParameters().put('cancel', 'true');
      pec.autoRegister();

      ApexPages.currentPage().getParameters().put('register', 'true');
      pec.autoRegister();

      pec.addType = 'DietryNeeds';
      pec.addSpecialNeed();
      pec.addSpecialNeed();
            
            pec.setRegistrationDates();
            
	        //TODO: Fix this test. Below commented.
        	//DR - 17 Feb 2023: Temporary change to pass tests.
            //pec.regPeriodId = pec.getRegistrationPeriods()[1].getValue();

      pec.register();

      for(String s : pec.currentNeeds.keySet()) {
        pec.removeNeedId = s;
        pec.removeSpecialNeed();
      }

      pec.beginRegistration();

      pec.cancelBookingId = pec.registerBookingId;

      pec.cancel();

      Test.stopTest();

        }

  }
  
  @testSetup static void SetupTests() {

    Id p = [select id from profile where name='My Camp Quality Members'].id;
       
        Account ac = new Account(name ='Test Account') ;
        insert ac; 
       
        Contact con = new Contact(LastName ='testCon',AccountId = ac.Id,npsp__Deceased__c = false, Exclude_From_Portal__c = false);
        insert con;  
                  
        User user = new User(alias = 'test123', email='test123@noemail.com',
                      emailencodingkey='UTF-8', lastname='Testing', languagelocalekey='en_US',
                      localesidkey='en_US', profileid = p, country='United States',IsActive =true,
                      ContactId = con.Id, timezonesidkey='America/Los_Angeles', username='tester@noemail.com');
       
        insert user;
        
        Campaign cmp = new Campaign(Name = 'Campaign Name', Status = 'Planned', isActive = true, Registrations_Open__c = (Datetime.now() - 1), Registrations_Closed__c = (Datetime.now() + 1) );

        insert cmp;

        Registration_Type__c rt = new Registration_Type__c(Name = 'Test Registration', Number_Available__c = 10, Event__c = cmp.Id);

        insert rt;
        
        Registration_Period__c rp = new Registration_Period__c(Name = 'Period', Campaign__c = cmp.Id, Number_Available__c = 50, Start_Date__c = Date.today(), End_Date__c = Date.today());
        
        insert rp;
        
        Registration_Type_Period__c rtp = new Registration_Type_Period__c(Registration_Type__c = rt.Id, Registration_Period__c = rp.Id);
        
        insert rtp;

        Volunteer_Attendance__c va = new Volunteer_Attendance__c(Event__c = cmp.Id, Attendance__c = 'Invited', Volunteer__c = con.Id, Registration_Type__c = rt.Id);

        insert va;

        va = new Volunteer_Attendance__c(Event__c = cmp.Id, Attendance__c = 'Request to Attend', Volunteer__c = con.Id, Registration_Type__c = rt.Id);

        insert va;

        Special_Needs__c sn = new Special_Needs__c(AttributeType__c = 'DietryNeeds', Contact__c = con.Id, Long_Description__c = 'Allergic - Garlic');

        insert sn;

        Site__c site = new Site__c(Name = 'Volunteer Portal');

        insert site;

        Page__c page = new Page__c(Name = 'Volunteer My Events', Site__c = site.Id);

        insert page;

        Page__c page2 = new Page__c(Name = 'Volunteer Event', Site__c = site.Id);

        insert page2;


  }
  
}