force-app/main/default/objects/Lead/fields/Lead_Conversion_Validation_Errors__c.field-meta.xml
<CustomField>
    <fullName>Lead_Conversion_Validation_Errors__c</fullName>
    <formula>Diagnosis_Info_Errors__c  &amp; if( Has_Child_Under_14__c ,&apos;&apos;,&apos; No child &lt; 14&apos;)  &amp;  if(Family_Contact_Details_Provided__c,&apos;&apos;,&apos; required contact fields blank&apos;)
&amp; if ( NoPatientSelected__c , &apos;No Patient Selected&apos;,&apos;&apos;)</formula>
    <label>Lead Conversion Validation Errors</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Lead_Mapping_Processed__c.field-meta.xml
<CustomField>
    <fullName>Lead_Mapping_Processed__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Lead Mapping Processed</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Mapping_Definition_Name__c.field-meta.xml
<CustomField>
    <fullName>Mapping_Definition_Name__c</fullName>
    <defaultValue>if ( $RecordType.DeveloperName  = &quot;Family_Application&quot;,&quot;FamilyApplication&quot;,&quot;VolunteerApplication&quot;)</defaultValue>
    <label>Mapping Definition Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/ProcessLeadMappingController.cls
public class ProcessLeadMappingController {
    
    //public Id leadId{get;set;}
    public Lead lead {get; set;}
    public String msg {get; set;}
    public ProcessLeadMappingController(ApexPages.StandardController sc) {
        if (!Test.isRunningTest())  {
            sc.addFields(new List<String>{'Id', 'Lead_Mapping_Processed__c'});
            sc.addFields(new List<String>{'Id', 'Lead_Conversion_Validation_Errors__c'});
            sc.addFields(new List<String>{'Id', 'Mapping_Definition_Name__c'});
        }
        
        this.lead = (Lead)sc.getRecord();
    }
    
    public void processLeadMapping() {
        if (this.lead.Lead_Mapping_Processed__c)
            this.msg = 'Lead Mapping has already been processed for this record';
        else {
            if (this.lead.Mapping_Definition_Name__c == 'FamilyApplication' && (this.lead.Lead_Conversion_Validation_Errors__c) <> NULL ) {
                this.msg = ('This lead cannot be converted.  The following errors exist ' + this.lead.Lead_Conversion_Validation_Errors__c );
                
            }
            else {
                ProcessLeadMapping.ProcessLead(this.lead.Id);
                this.msg = 'Lead Mapping has been queued';  
            }
        }
        
        
    }
    
}