force-app/main/default/objects/Contact/fields/Branch_Office__c.field-meta.xml
<CustomField>
    <fullName>Branch_Office__c</fullName>
    <label>Contact Branch Office</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Western Australia</fullName>
            </value>
            <value>
                <fullName>South Australia</fullName>
            </value>
            <value>
                <fullName>Victoria</fullName>
            </value>
            <value>
                <fullName>SNSW</fullName>
            </value>
            <value>
                <fullName>Sydney</fullName>
            </value>
            <value>
                <fullName>Northern New South Wales</fullName>
            </value>
            <value>
                <fullName>Queensland</fullName>
            </value>
            <value>
                <fullName>Tasmania</fullName>
            </value>
            <value>
                <fullName>Northern Territory</fullName>
            </value>
            <value>
                <fullName>Newcastle</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/Constituent_ID__c.field-meta.xml
<CustomField>
    <fullName>Constituent_ID__c</fullName>
    <displayFormat>{0}</displayFormat>
    <externalId>true</externalId>
    <label>Constituent ID - Auto Number</label>
    <type>AutoNumber</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Volunteer_Types_Training__c.field-meta.xml
<CustomField>
    <fullName>Volunteer_Types_Training__c</fullName>
    <label>Volunteer_Types_Training</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Camp Leader</fullName>
            </value>
            <value>
                <fullName>Companion Support</fullName>
            </value>
            <value>
                <fullName>Companion/Rover</fullName>
            </value>
            <value>
                <fullName>DoctorAround</fullName>
            </value>
            <value>
                <fullName>Endorsed Enrolled Nurse</fullName>
            </value>
            <value>
                <fullName>Events/Fundraising</fullName>
            </value>
            <value>
                <fullName>First AiderAround</fullName>
            </value>
            <value>
                <fullName>Fundraising Support Group</fullName>
            </value>
            <value>
                <fullName>Leadership Committee Member</fullName>
            </value>
            <value>
                <fullName>Local Team Leader</fullName>
            </value>
            <value>
                <fullName>Office Administration</fullName>
            </value>
            <value>
                <fullName>Paramedic</fullName>
            </value>
            <value>
                <fullName>Photographer</fullName>
            </value>
            <value>
                <fullName>Puppeteer</fullName>
            </value>
            <value>
                <fullName>Registered Nurse</fullName>
            </value>
            <value>
                <fullName>Volunteer Consultation Committee</fullName>
            </value>
            <value>
                <fullName>z Rover</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/recordTypes/Volunteer.recordType-meta.xml
<RecordType>
    <fullName>Volunteer</fullName>
    <active>true</active>
    <label>Volunteer</label>
</RecordType>

force-app/main/default/classes/VolunteerLMSCSV.cls
public class VolunteerLMSCSV {
	
    @testVisible
    private List<Contact> cons {get;set;}
    
    public String csvString {get;set;}
    
    public VolunteerLMSCSV(ApexPages.StandardSetController controller) {
        if(!Test.isRunningTest())
            controller.addFields(new List<String>{'Constituent_ID__c', 'FirstName', 'LastName', 'Email', 'Branch_Office__c', 'MailingState', 'Volunteer_Types_Training__c'});
        
        controller.setPageSize(999);
        cons = (List<Contact>)controller.getRecords();
        getLMSExport();
    }
    
    public void getLMSExport() {
        
        csvString = 'Username,Password,First Name,Surname,Location,State,Email,Volunteer Type 1,Volunteer Type 2,Volunteer Type 3,Volunteer Type 4,Volunteer Type 5,Volunteer Type 6,Volunteer Type 7,Volunteer Type 8,Volunteer Type 9,Volunteer Type 10,Role\n';
        
        for(Contact con : cons) {
            Set<String> volTypes = new Set<String>();
            
            if(String.isNotBlank(con.Volunteer_Types_Training__c )) { 
            	volTypes.addAll(con.Volunteer_Types_Training__c.split(';'));
            }
            
            String rowString = 	con.Constituent_Id__c + ',WeLoveVolunteers1!,';
            
            rowString += String.isNotBlank(con.FirstName) ? con.FirstName + ',' : ',';
            rowString += String.isNotBlank(con.LastName) ? con.LastName + ',' : ','; 
            rowString += String.isNotBlank(con.Branch_Office__c) ? con.Branch_Office__c + ',' : ',';
            rowString += String.isNotBlank(con.MailingState) ? con.MailingState + ',' : ',';
            rowString += String.isNotBlank(con.Email) ? con.Email + ',' : ',';
            
            rowString += volTypes.contains('Registered Nurse') ? 'Registered Nurse,' : ',';
            rowString += volTypes.contains('Camp Leader') ? 'Camp Leader,' : ',';
            rowString += volTypes.contains('Companion Support') ? 'Companion Support,' : ',';
            rowString += volTypes.contains('Companion/Rover') ? 'Companion/Rover,' : ',';
            rowString += volTypes.contains('Doctor') ? 'Doctor,' : ',';
            rowString += volTypes.contains('Endorsed Enrolled Nurse') ? 'Endorsed Enrolled Nurse,' : ',';
            rowString += volTypes.contains('Events/Fundraising') ? 'Events/Fundraising,' : ',';
            rowString += volTypes.contains('Fundraising Support Group') ? 'Fundraising Support Group,' : ',';
            rowString += volTypes.contains('First Aider') ? 'First Aider,' : ',';
            rowString += volTypes.contains('Office Administration') ? 'Office Administration,' : ',';
            rowString += 'Volunteer\n';
            
            csvString += rowString;
        }
        
    }
    
}