force-app/main/default/objects/Contact/fields/Date_From__c.field-meta.xml
<CustomField>
    <fullName>Date_From__c</fullName>
    <defaultValue>today()</defaultValue>
    <label>Date From</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Family_Member_Type__c.field-meta.xml
<CustomField>
    <fullName>Family_Member_Type__c</fullName>
    <label>Family Member Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Aunt</fullName>
            </value>
            <value>
                <fullName>Deceased Parent</fullName>
            </value>
            <value>
                <fullName>Father</fullName>
            </value>
            <value>
                <fullName>Grandparent</fullName>
            </value>
            <value>
                <fullName>Hospital</fullName>
            </value>
            <value>
                <fullName>Legal Guardian</fullName>
            </value>
            <value>
                <fullName>Mother</fullName>
            </value>
            <value>
                <fullName>Patient</fullName>
            </value>
            <value>
                <fullName>School</fullName>
            </value>
            <value>
                <fullName>Sibling</fullName>
            </value>
            <value>
                <fullName>Stepfather</fullName>
            </value>
            <value>
                <fullName>Stepmother</fullName>
            </value>
            <value>
                <fullName>Stepsibling</fullName>
            </value>
            <value>
                <fullName>Uncle</fullName>
            </value>
            <value>
                <fullName>Cousin</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/Volunteer_Eligibility__c.field-meta.xml
<CustomField>
    <fullName>Volunteer_Eligibility__c</fullName>
    <description>Volunteer Eligibility reason describes what conditions of volunteering have not been meet by a volunteer.  CampQuality.volunteerEligibility code sets these values.  There is also VolunteerEligibilitySchedulable to update WWC fields</description>
    <label>Volunteer Eligibility Reason</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Code of Conduct Form Missing</fullName>
            </value>
            <value>
                <fullName>Currently Eligible</fullName>
            </value>
            <value>
                <fullName>Photo ID Not Sighted</fullName>
            </value>
            <value>
                <fullName>Volunteer Interview Missing</fullName>
            </value>
            <value>
                <fullName>Volunteer References Missing</fullName>
            </value>
            <value>
                <fullName>WWC Not Completed</fullName>
            </value>
            <value>
                <fullName>ACF Course Not Completed</fullName>
            </value>
            <value>
                <fullName>Dr Indemnity Insurance Policy No/Expiry Missing</fullName>
            </value>
            <value>
                <fullName>Health Practitioner Registration No &amp; Exp Date Missing</fullName>
            </value>
            <value>
                <fullName>Missing Safeguarding Children Guidelines</fullName>
            </value>
            <value>
                <fullName>WWC Expired</fullName>
            </value>
            <value>
                <fullName>Missing SC&amp;Y Policy</fullName>
            </value>
            <value>
                <fullName>Missing RSCA Policy</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/recordTypes/Family_Member.recordType-meta.xml
<RecordType>
    <fullName>Family_Member</fullName>
    <active>true</active>
    <label>Family Member</label>
</RecordType>

force-app/main/default/objects/Contact/recordTypes/Volunteer.recordType-meta.xml
<RecordType>
    <fullName>Volunteer</fullName>
    <active>true</active>
    <label>Volunteer</label>
</RecordType>

force-app/main/default/objects/Family_Attendance__c/Family_Attendance__c.object-meta.xml
<CustomObject>
    <description>Used for recording details of families attendance on programs, linked to familiy member attendance, family guest attendance campaign member and campaign</description>
    <label>Family Attendance</label>
    <nameField>
        <displayFormat>FA{00000}</displayFormat>
        <label>Family Attendance</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Family Attendances</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Family_Attendance__c/fields/Event__c.field-meta.xml
<CustomField>
    <fullName>Event__c</fullName>
    <label>Event</label>
    <referenceTo>Campaign</referenceTo>
    <relationshipLabel>Family Attendances</relationshipLabel>
    <relationshipName>Family_Attendances</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Family_Attendance__c/fields/Family__c.field-meta.xml
<CustomField>
    <fullName>Family__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Family</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Family Attendances</relationshipLabel>
    <relationshipName>Family_Attendances</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Family_Attendance__c/fields/Registration_Type__c.field-meta.xml
<CustomField>
    <fullName>Registration_Type__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Registration Type</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>$Source.Event__c</field>
            <operation>equals</operation>
            <valueField>Registration_Type__c.Event__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Registration_Type__c</referenceTo>
    <relationshipLabel>Family Attendances</relationshipLabel>
    <relationshipName>Family_Attendances</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Family_Member_Attendance__c/Family_Member_Attendance__c.object-meta.xml
<CustomObject>
    <description>Used for recording individual family member attendances on programs linked to family attendance</description>
    <label>Family Member Attendance</label>
    <nameField>
        <displayFormat>FMA{00000}</displayFormat>
        <label>Family Member Attendance</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Family Member Attendance</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Family_Member_Attendance__c/fields/Attendance__c.field-meta.xml
<CustomField>
    <fullName>Attendance__c</fullName>
    <label>Attendance</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Invited</fullName>
            </value>
            <value>
                <fullName>Request to Attend</fullName>
            </value>
            <value>
                <fullName>Accepted</fullName>
            </value>
            <value>
                <fullName>Attended</fullName>
            </value>
            <value>
                <fullName>Declined</fullName>
            </value>
            <value>
                <fullName>Unsuccessful</fullName>
            </value>
            <value>
                <fullName>No Show</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Cancelled &lt; 24 hours</fullName>
            </value>
            <value>
                <fullName>Medical Withdrawal</fullName>
            </value>
            <value>
                <fullName>Unsuccessful – Waitlist</fullName>
            </value>
            <value>
                <fullName>Unsuccessful – Declined</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Family_Member_Attendance__c/fields/Event__c.field-meta.xml
<CustomField>
    <fullName>Event__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Event</label>
    <referenceTo>Campaign</referenceTo>
    <relationshipLabel>Family Member Attendance</relationshipLabel>
    <relationshipName>Family_Member_Attendance</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Family_Member_Attendance__c/fields/Family_Attendance__c.field-meta.xml
<CustomField>
    <fullName>Family_Attendance__c</fullName>
    <label>Family Attendance</label>
    <referenceTo>Family_Attendance__c</referenceTo>
    <relationshipLabel>Family Member Attendance</relationshipLabel>
    <relationshipName>Family_Member_Attendance</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Family_Member_Attendance__c/fields/Family_Member_Type__c.field-meta.xml
<CustomField>
    <fullName>Family_Member_Type__c</fullName>
    <formula>TEXT(Contact__r.Family_Member_Type__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Family Member Type</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Registration_Type__c/Registration_Type__c.object-meta.xml
<CustomObject>
    <description>Part of the invitation process for programs.  Registration types are used to store the settings for each type of registeration for an event (i.e. family, volunter)</description>
    <label>Registration Type</label>
    <nameField>
        <label>Registration Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Registration Types</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Registration_Type__c/fields/Event__c.field-meta.xml
<CustomField>
    <fullName>Event__c</fullName>
    <label>Event</label>
    <referenceTo>Campaign</referenceTo>
    <relationshipLabel>Registration Types</relationshipLabel>
    <relationshipName>Registration_Types</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Registration_Type__c/fields/Family_Ticket_Size__c.field-meta.xml
<CustomField>
    <fullName>Family_Ticket_Size__c</fullName>
    <inlineHelpText>Maximum number per Family Group</inlineHelpText>
    <label>Family Ticket Size</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Registration_Type__c/fields/Initial_Allocation__c.field-meta.xml
<CustomField>
    <fullName>Initial_Allocation__c</fullName>
    <inlineHelpText>Initial Invitation Allocation</inlineHelpText>
    <label>Initial Allocation</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Registration_Type__c/fields/Number_Available__c.field-meta.xml
<CustomField>
    <fullName>Number_Available__c</fullName>
    <inlineHelpText>Maximum Number of Tickets Available</inlineHelpText>
    <label>Number Available</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Registration_Type__c/fields/Ticket_Type__c.field-meta.xml
<CustomField>
    <fullName>Ticket_Type__c</fullName>
    <label>Ticket Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Family</fullName>
            </value>
            <value>
                <fullName>Individual</fullName>
            </value>
            <value>
                <fullName>Mini Camp</fullName>
            </value>
            <value>
                <fullName>Jnr Camp</fullName>
            </value>
            <value>
                <fullName>Middle Camp</fullName>
            </value>
            <value>
                <fullName>Joint Junior and Middle Camp</fullName>
            </value>
            <value>
                <fullName>Joint Mini Jun and Middle</fullName>
            </value>
            <value>
                <fullName>Virtual Camp</fullName>
            </value>
            <value>
                <fullName>Leadership 15-17</fullName>
            </value>
            <value>
                <fullName>Teens 13- 15</fullName>
                <isActive>false</isActive>
                <label>Teens 13- 15</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Registration_Type__c/recordTypes/Aged_Camp.recordType-meta.xml
<RecordType>
    <fullName>Aged_Camp</fullName>
    <active>true</active>
    <label>Aged Camp</label>
</RecordType>

force-app/main/default/objects/Registration_Type__c/recordTypes/Volunteer.recordType-meta.xml
<RecordType>
    <fullName>Volunteer</fullName>
    <active>true</active>
    <description>Volunteer Registration</description>
    <label>Volunteer</label>
</RecordType>

force-app/main/default/objects/Volunteer_Attendance__c/Volunteer_Attendance__c.object-meta.xml
<CustomObject>
    <description>Used for tracking volunteer attendance on programs. Linked to campaign member for communication, campaign for program, contact for volunteer</description>
    <label>Volunteer Attendance</label>
    <nameField>
        <displayFormat>VA{00000}</displayFormat>
        <label>Volunteer Attendance</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Volunteer Attendances</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Volunteer_Attendance__c/fields/Attendance__c.field-meta.xml
<CustomField>
    <fullName>Attendance__c</fullName>
    <label>Attendance</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Invited</fullName>
            </value>
            <value>
                <fullName>Request to Attend</fullName>
            </value>
            <value>
                <fullName>Accepted</fullName>
            </value>
            <value>
                <fullName>Attended</fullName>
            </value>
            <value>
                <fullName>Declined</fullName>
            </value>
            <value>
                <fullName>Unsuccessful</fullName>
            </value>
            <value>
                <fullName>No Show</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Medical Withdrawal</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Volunteer_Attendance__c/fields/Event__c.field-meta.xml
<CustomField>
    <fullName>Event__c</fullName>
    <label>Event</label>
    <referenceTo>Campaign</referenceTo>
    <relationshipLabel>Volunteer Attendances</relationshipLabel>
    <relationshipName>Volunteer_Attendances</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Volunteer_Attendance__c/fields/Registration_Type__c.field-meta.xml
<CustomField>
    <fullName>Registration_Type__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Registration Type</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>$Source.Event__c</field>
            <operation>equals</operation>
            <valueField>Registration_Type__c.Event__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Registration_Type__c</referenceTo>
    <relationshipLabel>Volunteer Attendances</relationshipLabel>
    <relationshipName>Volunteer_Attendances</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/MatchChildControllerTest.cls
@isTest 
private class MatchChildControllerTest {

    static testMethod  void testChildController() {
     
		Campaign cam = [SELECT Id FROM Campaign WHERE Name = 'Campaign Name' LIMIT 1];

        
       PageReference pageRef = Page.MatchChild;
        ApexPages.StandardController sc = new ApexPages.StandardController(cam);
        
        
        MatchChildController obj  = new MatchChildController(sc);
		obj.getListOfVolunteers();
        obj.setAttendeds();
        obj.matchVolunteer();        
    }
	@testSetup static void SetupTests() {
           Map<String, RecordType> rMapRtype = new Map<String, RecordType>();
        Map<String, RecordType> rMap = new Map<String, RecordType>();
                Map<String, RecordType> aMap = new Map<String, RecordType>();
                Map<String, RecordType> cMap = new Map<String, RecordType>();

      //for(RecordType r : [SELECT Id, DeveloperName FROM RecordType where SobjectType = 'Registration_Type__C'])
        //    rMapRType.put(r.DeveloperName, r);
        for(RecordType r : [SELECT Id, DeveloperName FROM RecordType where SobjectType = 'Campaign'])
            rMap.put(r.DeveloperName, r);
        for(RecordType r : [SELECT Id, DeveloperName FROM RecordType where SobjectType = 'Account'])
            aMap.put(r.DeveloperName, r);
      for(RecordType r : [SELECT Id, DeveloperName FROM RecordType where SobjectType = 'Contact'])
            cMap.put(r.DeveloperName, r);
      
        Account a = New Account( Name = 'Family', RecordTypeId = aMap.get('Family').Id );
        insert a;

        Contact vol = new Contact( AccountId = a.Id, FirstName = 'Dad', LastName = 'Family', Volunteer_Eligibility__c  = 'Currently Eligible', Date_From__c = System.Today().addMonths(-6), RecordTypeId = cMap.get('Volunteer').Id );
        insert vol; 
        
        Contact fm1 = new Contact( FirstName = 'Dad', LastName = 'Family', Family_Member_Type__c = 'Father', AccountId = a.Id, RecordTypeId = cMap.get('Family_Member').Id );
        insert fm1;
        
        Contact fm2 = new Contact( FirstName = 'Sibling', LastName = 'Family', Family_Member_Type__c = 'Brother', AccountId = a.Id, RecordTypeId = cMap.get('Family_Member').Id );
        insert fm2;
        
          
        Campaign cam = new Campaign( Name = 'Campaign Name', isActive = true, RecordTypeId = rMap.get('Age_Camp').Id );
        Insert cam;
        
        
        
        //Registration_Type__c rt = new Registration_Type__c( Name = 'Jnr Camp', Event__c = cam.Id, Ticket_Type__c = 'Jnr Camp', RecordTypeId = rMapRType.get('Aged_Camp').Id, Number_Available__c = 20, Family_Ticket_Size__c = 2, Initial_Allocation__c = 200);
        //insert rt;
        Family_Attendance__c fa = new Family_Attendance__c(Family__c = a.Id, Event__c = cam.Id, FA_00000__c = 'Accepted');

        insert fa;
        Family_Member_Attendance__c fma1 = new Family_Member_Attendance__c(Event__c = cam.Id, Attendance__c = 'Accepted', Family_Attendance__c = fa.Id, Contact__c = fm1.Id);
        insert fma1;
                Family_Member_Attendance__c fma2 = new Family_Member_Attendance__c(Event__c = cam.Id, Attendance__c = 'Accepted', Family_Attendance__c = fa.Id, Contact__c = fm2.Id);
        insert fma2;
          //      Family_Member_Attendance__c fma3 = new Family_Member_Attendance__c(Event__c = cam.Id, Attendance__c = 'Accepted', Family_Attendance__c = fa.Id, Contact__c = fm3.Id);
   
        Volunteer_Attendance__c va = new Volunteer_Attendance__c(Event__c = cam.Id, Attendance__c = 'Accepted', Volunteer__c = vol.Id);

        insert va;
               
    }


}