force-app/main/default/objects/Contact/fields/Gender__c.field-meta.xml
<CustomField>
    <fullName>Gender__c</fullName>
    <label>Gender</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Female</fullName>
            </value>
            <value>
                <fullName>Male</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
            <value>
                <fullName>Unknown</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/Regionv2__c.field-meta.xml
<CustomField>
    <fullName>Regionv2__c</fullName>
    <label>Region</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Regions</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/Volunteer_Attendance__c.field-meta.xml
<CustomField>
    <fullName>Volunteer_Attendance__c</fullName>
    <label>Last Volunteer Attendance</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Year_Age__c.field-meta.xml
<CustomField>
    <fullName>Year_Age__c</fullName>
    <formula>YEAR(TODAY())- Year(Birthdate)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>How old the person will turn this year.</inlineHelpText>
    <label>Year Age</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Family_Attendance__c/Family_Attendance__c.object-meta.xml
<CustomObject>
    <description>Used for recording details of families attendance on programs, linked to familiy member attendance, family guest attendance campaign member and campaign</description>
    <label>Family Attendance</label>
    <nameField>
        <displayFormat>FA{00000}</displayFormat>
        <label>Family Attendance</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Family Attendances</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Family_Attendance__c/fields/Event__c.field-meta.xml
<CustomField>
    <fullName>Event__c</fullName>
    <label>Event</label>
    <referenceTo>Campaign</referenceTo>
    <relationshipLabel>Family Attendances</relationshipLabel>
    <relationshipName>Family_Attendances</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Family_Member_Attendance__c/Family_Member_Attendance__c.object-meta.xml
<CustomObject>
    <description>Used for recording individual family member attendances on programs linked to family attendance</description>
    <label>Family Member Attendance</label>
    <nameField>
        <displayFormat>FMA{00000}</displayFormat>
        <label>Family Member Attendance</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Family Member Attendance</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Family_Member_Attendance__c/fields/Attendance__c.field-meta.xml
<CustomField>
    <fullName>Attendance__c</fullName>
    <label>Attendance</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Invited</fullName>
            </value>
            <value>
                <fullName>Request to Attend</fullName>
            </value>
            <value>
                <fullName>Accepted</fullName>
            </value>
            <value>
                <fullName>Attended</fullName>
            </value>
            <value>
                <fullName>Declined</fullName>
            </value>
            <value>
                <fullName>Unsuccessful</fullName>
            </value>
            <value>
                <fullName>No Show</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Cancelled &lt; 24 hours</fullName>
            </value>
            <value>
                <fullName>Medical Withdrawal</fullName>
            </value>
            <value>
                <fullName>Unsuccessful – Waitlist</fullName>
            </value>
            <value>
                <fullName>Unsuccessful – Declined</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Family_Member_Attendance__c/fields/Companion__c.field-meta.xml
<CustomField>
    <fullName>Companion__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Companion</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>$Source.Event__c</field>
            <operation>equals</operation>
            <valueField>Volunteer_Attendance__c.Event__c</valueField>
        </filterItems>
        <infoMessage>The volunteer attendance record must be for the same event.</infoMessage>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Volunteer_Attendance__c</referenceTo>
    <relationshipLabel>Companion Children</relationshipLabel>
    <relationshipName>Companion_Children</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Family_Member_Attendance__c/fields/Companion_Name__c.field-meta.xml
<CustomField>
    <fullName>Companion_Name__c</fullName>
    <formula>Companion__r.Volunteer__r.FirstName &amp; &quot; &quot; &amp; Companion__r.Volunteer__r.LastName</formula>
    <label>Companion Name</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Family_Member_Attendance__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Family Member Attendance</relationshipLabel>
    <relationshipName>Family_Member_Attendance</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Family_Member_Attendance__c/fields/Event__c.field-meta.xml
<CustomField>
    <fullName>Event__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Event</label>
    <referenceTo>Campaign</referenceTo>
    <relationshipLabel>Family Member Attendance</relationshipLabel>
    <relationshipName>Family_Member_Attendance</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Family_Member_Attendance__c/fields/Family_Attendance__c.field-meta.xml
<CustomField>
    <fullName>Family_Attendance__c</fullName>
    <label>Family Attendance</label>
    <referenceTo>Family_Attendance__c</referenceTo>
    <relationshipLabel>Family Member Attendance</relationshipLabel>
    <relationshipName>Family_Member_Attendance</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Volunteer_Attendance__c/Volunteer_Attendance__c.object-meta.xml
<CustomObject>
    <description>Used for tracking volunteer attendance on programs. Linked to campaign member for communication, campaign for program, contact for volunteer</description>
    <label>Volunteer Attendance</label>
    <nameField>
        <displayFormat>VA{00000}</displayFormat>
        <label>Volunteer Attendance</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Volunteer Attendances</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Volunteer_Attendance__c/fields/Attendance__c.field-meta.xml
<CustomField>
    <fullName>Attendance__c</fullName>
    <label>Attendance</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Invited</fullName>
            </value>
            <value>
                <fullName>Request to Attend</fullName>
            </value>
            <value>
                <fullName>Accepted</fullName>
            </value>
            <value>
                <fullName>Attended</fullName>
            </value>
            <value>
                <fullName>Declined</fullName>
            </value>
            <value>
                <fullName>Unsuccessful</fullName>
            </value>
            <value>
                <fullName>No Show</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Medical Withdrawal</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Volunteer_Attendance__c/fields/Event__c.field-meta.xml
<CustomField>
    <fullName>Event__c</fullName>
    <label>Event</label>
    <referenceTo>Campaign</referenceTo>
    <relationshipLabel>Volunteer Attendances</relationshipLabel>
    <relationshipName>Volunteer_Attendances</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Volunteer_Attendance__c/fields/Volunteer__c.field-meta.xml
<CustomField>
    <fullName>Volunteer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Volunteer</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Volunteer Attendances</relationshipLabel>
    <relationshipName>Volunteer_Attendances</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Volunteer_Attendance__c/fields/Volunteer_Rating__c.field-meta.xml
<CustomField>
    <fullName>Volunteer_Rating__c</fullName>
    <label>Volunteer Rating</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Standout Volunteer</fullName>
            </value>
            <value>
                <fullName>Good Fit</fullName>
            </value>
            <value>
                <fullName>Still Settling In</fullName>
            </value>
            <value>
                <fullName>Needs Further Support/Training</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/globalValueSets/Regions.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>ACT - Albury</fullName>
    </customValue>
    <customValue>
        <fullName>ACT - Bega</fullName>
    </customValue>
    <customValue>
        <fullName>ACT - Cooma</fullName>
    </customValue>
    <customValue>
        <fullName>ACT - Cowra</fullName>
    </customValue>
    <customValue>
        <fullName>ACT - Dubbo</fullName>
    </customValue>
    <customValue>
        <fullName>ACT - Forbes/Parkes</fullName>
    </customValue>
    <customValue>
        <fullName>ACT - Goulburn</fullName>
    </customValue>
    <customValue>
        <fullName>ACT - Local</fullName>
    </customValue>
    <customValue>
        <fullName>ACT - Narooma</fullName>
    </customValue>
    <customValue>
        <fullName>ACT - Orange</fullName>
    </customValue>
    <customValue>
        <fullName>ACT - Queanbeyan</fullName>
    </customValue>
    <customValue>
        <fullName>ACT - Wagga Wagga</fullName>
    </customValue>
    <customValue>
        <fullName>ACT - Young</fullName>
    </customValue>
    <customValue>
        <fullName>ILLA - Far South Coast</fullName>
    </customValue>
    <customValue>
        <fullName>ILLA - Local</fullName>
    </customValue>
    <customValue>
        <fullName>ILLA - Out of Area</fullName>
    </customValue>
    <customValue>
        <fullName>ILLA - Shoalhaven</fullName>
    </customValue>
    <customValue>
        <fullName>ILLA - Southern Highlands</fullName>
    </customValue>
    <customValue>
        <fullName>NCL-Central Coast</fullName>
    </customValue>
    <customValue>
        <fullName>NCL-Central West</fullName>
    </customValue>
    <customValue>
        <fullName>NCL-Hunter</fullName>
    </customValue>
    <customValue>
        <fullName>NCL-Manning</fullName>
    </customValue>
    <customValue>
        <fullName>NCL-Newcastle</fullName>
    </customValue>
    <customValue>
        <fullName>NNSW - Armidale</fullName>
    </customValue>
    <customValue>
        <fullName>NNSW - Byron/Ballina/lismore</fullName>
        <label>NNSW - Byron/Ballina/Lismore</label>
    </customValue>
    <customValue>
        <fullName>NNSW - Coffs Harbour</fullName>
    </customValue>
    <customValue>
        <fullName>NNSW - Glen Innes/Inverell</fullName>
    </customValue>
    <customValue>
        <fullName>NNSW - Other</fullName>
    </customValue>
    <customValue>
        <fullName>NNSW - Port Macquarie/Kempsey</fullName>
    </customValue>
    <customValue>
        <fullName>NNSW - Tamworth</fullName>
    </customValue>
    <masterLabel>Regions</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/MatchChildController.cls
public class MatchChildController {

    public Id camId {get;set;}
    public Map<Id, Family_Member_Attendance__c> fmas{get;set;}
           

     public Map<Id, String> fmaVol{get;set;}

    public String selectedcompainionId {set;get;}
	public String selecteduserId {set;get;}
	private List<Volunteer_Attendance__c> va1; 
    
    public MatchChildController(ApexPages.StandardController sc) {
        
        camId = sc.getId();
        setAttendeds();
        selecteduserId ='';
        selectedcompainionId ='';
        va1 = [SELECT Id, Attendance__c, Volunteer__r.FirstName, Volunteer__r.LastName, Volunteer__r.MailingStreet, Volunteer__r.MailingCity, Volunteer__r.MailingState, Volunteer__r.MailingPostalCode, Volunteer_Rating__c FROM Volunteer_Attendance__c WHERE Event__c = :camId AND (Attendance__c = 'Accepted' OR Attendance__c = 'Attended') order by  Volunteer__r.FirstName, Volunteer__r.LastName];    
    }
	public void matchVolunteer() {
			
            if( fmas != null && fmas.containsKey(attendId)) {
	            Family_Member_Attendance__c fma = fmas.get(attendId);
                if (fmaVol.get(attendId) == ' ') {
                    fma.Companion__c = null;
                    
                }
                else{
                	fma.Companion__c = fmaVol.get(attendId);    
                }
            	
            	attendid = null;
            	
                    //va.Volunteer_Rating__c = vaRating.get(attendId);
                //va.Volunteer_Rating__c = 'Still Settling In';
              System.debug('fma: ' + fma);
            
            try {
                update fma;
                setAttendeds();
            } catch(DmlException ex) {
                System.debug(ex);
                ApexPages.addMessages(ex);
            }
        
            
        	}
        }
    public Id attendId{get;set;}
    
        
    
    public void setAttendeds() {
        selectedcompainionId ='';
		loadFamilies();
        //fmaAttendeds = new Map<Id, Boolean>();
		fmaVol = new Map<Id, String>();
        
        if(fmas != null) {
            for(Id key : fmas.keySet()) {
                if (fmas.get(key).Companion__C != null) {
	                fmaVol.put(key,fmas.get(key).Companion__C);
                    }
                else
                {
                    
                    fmaVol.put(key,' ');
                }
                
                    
            }
        }
        
        
    }
    public List<SelectOption> getListOfVolunteers()
    {
      
               List<SelectOption> VolunteerList = new List<SelectOption>();
       		
               VolunteerList.add(new SelectOption( ' ' ,'---Select---'));
               for(Volunteer_Attendance__c v : va1 )
               {
                          VolunteerList.add(new SelectOption(v.Id , v.Volunteer__r.FirstName + ' ' + v.Volunteer__r.lastname));
               }
              return VolunteerList ;
    }
 
  
    private void loadFamilies() {

        fmas = new Map<Id, Family_Member_Attendance__c>([SELECT Id, Companion__c, Companion_Name__c,Companion__r.Volunteer__r.LastName,  Attendance__c, Contact__r.year_age__C, Contact__r.gender__C, Contact__r.FirstName, Contact__r.LastName, Contact__r.MailingStreet, Contact__r.MailingCity, Contact__r.MailingState, Contact__r.MailingPostalCode, Contact__R.account.regionv2__c FROM Family_Member_Attendance__c WHERE Family_Attendance__r.Event__c = :camId AND (Attendance__c = 'Accepted' OR Attendance__c = 'Attended')]);

    }
        
}