force-app/main/default/objects/Contact/fields/Preferred_First_Name__c.field-meta.xml
<CustomField>
    <fullName>Preferred_First_Name__c</fullName>
    <label>Preferred First Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Family_Attendance__c/Family_Attendance__c.object-meta.xml
<CustomObject>
    <description>Used for recording details of families attendance on programs, linked to familiy member attendance, family guest attendance campaign member and campaign</description>
    <label>Family Attendance</label>
    <nameField>
        <displayFormat>FA{00000}</displayFormat>
        <label>Family Attendance</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Family Attendances</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Family_Member_Attendance__c/Family_Member_Attendance__c.object-meta.xml
<CustomObject>
    <description>Used for recording individual family member attendances on programs linked to family attendance</description>
    <label>Family Member Attendance</label>
    <nameField>
        <displayFormat>FMA{00000}</displayFormat>
        <label>Family Member Attendance</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Family Member Attendance</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Family_Member_Attendance__c/fields/Attendance__c.field-meta.xml
<CustomField>
    <fullName>Attendance__c</fullName>
    <label>Attendance</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Invited</fullName>
            </value>
            <value>
                <fullName>Request to Attend</fullName>
            </value>
            <value>
                <fullName>Accepted</fullName>
            </value>
            <value>
                <fullName>Attended</fullName>
            </value>
            <value>
                <fullName>Declined</fullName>
            </value>
            <value>
                <fullName>Unsuccessful</fullName>
            </value>
            <value>
                <fullName>No Show</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Cancelled &lt; 24 hours</fullName>
            </value>
            <value>
                <fullName>Medical Withdrawal</fullName>
            </value>
            <value>
                <fullName>Unsuccessful – Waitlist</fullName>
            </value>
            <value>
                <fullName>Unsuccessful – Declined</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Family_Member_Attendance__c/fields/Child_Immunisation_Schedule_Current__c.field-meta.xml
<CustomField>
    <fullName>Child_Immunisation_Schedule_Current__c</fullName>
    <inlineHelpText>Child Immunisation Schedule current to the relevant state health book.  http://www.immunise.health.gov.au/internet/immunise/publishing.nsf/Content/national-immunisation-program-schedule</inlineHelpText>
    <label>Child Immunisation Schedule Current</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>No</fullName>
                <default>true</default>
                <label>No</label>
            </value>
            <value>
                <fullName>Yes</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Family_Member_Attendance__c/fields/Companion__c.field-meta.xml
<CustomField>
    <fullName>Companion__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Companion</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>$Source.Event__c</field>
            <operation>equals</operation>
            <valueField>Volunteer_Attendance__c.Event__c</valueField>
        </filterItems>
        <infoMessage>The volunteer attendance record must be for the same event.</infoMessage>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Volunteer_Attendance__c</referenceTo>
    <relationshipLabel>Companion Children</relationshipLabel>
    <relationshipName>Companion_Children</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Family_Member_Attendance__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Family Member Attendance</relationshipLabel>
    <relationshipName>Family_Member_Attendance</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Family_Member_Attendance__c/fields/Currently_on_Treatment__c.field-meta.xml
<CustomField>
    <fullName>Currently_on_Treatment__c</fullName>
    <label>Currently on Treatment</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>No</fullName>
                <default>true</default>
                <label>No</label>
            </value>
            <value>
                <fullName>Yes</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Family_Member_Attendance__c/fields/Family_Attendance__c.field-meta.xml
<CustomField>
    <fullName>Family_Attendance__c</fullName>
    <label>Family Attendance</label>
    <referenceTo>Family_Attendance__c</referenceTo>
    <relationshipLabel>Family Member Attendance</relationshipLabel>
    <relationshipName>Family_Member_Attendance</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Family_Member_Attendance__c/fields/OTC_Comments__c.field-meta.xml
<CustomField>
    <fullName>OTC_Comments__c</fullName>
    <label>OTC Comments</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Family_Member_Attendance__c/fields/OTC_Standard__c.field-meta.xml
<CustomField>
    <fullName>OTC_Standard__c</fullName>
    <description>This field indicates whether a family gives us permission to give:
Paracetamol  
Throat lozenges 
Anti-Inflammatory          	            	
Antiseptic based creams
Antihistamine tablets</description>
    <inlineHelpText>This field indicates whether a family gives us permission to give their child the following treatments:
Paracetamol  
Throat lozenges 
Anti-Inflammatory          	            	
Antiseptic based creams
Antihistamine tablets</inlineHelpText>
    <label>Permission for OTC Standard Treatments</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>No</fullName>
                <default>true</default>
                <label>No</label>
            </value>
            <value>
                <fullName>Yes</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Family_Member_Attendance__c/fields/Requires_Doctors_Form__c.field-meta.xml
<CustomField>
    <fullName>Requires_Doctors_Form__c</fullName>
    <description>Calculated field that determines if someone needs a med form</description>
    <formula>if( text(Currently_on_Treatment__c) = &quot;Yes&quot;,True,if ( text(Medication_and_Vitamins__c)=&quot;Original Packaging&quot;, True,False ))</formula>
    <inlineHelpText>This field shows whether a child needs a med form based on rego information</inlineHelpText>
    <label>Requires Doctors Form</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Family_Member_Attendance__c/fields/Requires_Medication_or_Vitamins__c.field-meta.xml
<CustomField>
    <fullName>Requires_Medication_or_Vitamins__c</fullName>
    <label>Requires Medication or Vitamins</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>No</fullName>
                <default>true</default>
                <label>No</label>
            </value>
            <value>
                <fullName>Yes</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Family_Member_Attendance__c/fields/Transport_Drop_Off_Location__c.field-meta.xml
<CustomField>
    <fullName>Transport_Drop_Off_Location__c</fullName>
    <label>Transport-Getting Home-Location</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Transport_Locations</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Family_Member_Attendance__c/fields/Transport_Drop_Off_Time__c.field-meta.xml
<CustomField>
    <fullName>Transport_Drop_Off_Time__c</fullName>
    <label>Transport-Getting Home-Time</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Family_Member_Attendance__c/fields/Transport_Pick_Up_Location__c.field-meta.xml
<CustomField>
    <fullName>Transport_Pick_Up_Location__c</fullName>
    <label>Transport-Getting to Camp-Location</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Transport_Locations</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Family_Member_Attendance__c/fields/Transport_Pick_Up_Time__c.field-meta.xml
<CustomField>
    <fullName>Transport_Pick_Up_Time__c</fullName>
    <label>Transport-Getting to Camp-Time</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Volunteer_Attendance__c/Volunteer_Attendance__c.object-meta.xml
<CustomObject>
    <description>Used for tracking volunteer attendance on programs. Linked to campaign member for communication, campaign for program, contact for volunteer</description>
    <label>Volunteer Attendance</label>
    <nameField>
        <displayFormat>VA{00000}</displayFormat>
        <label>Volunteer Attendance</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Volunteer Attendances</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Volunteer_Attendance__c/fields/Attendance__c.field-meta.xml
<CustomField>
    <fullName>Attendance__c</fullName>
    <label>Attendance</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Invited</fullName>
            </value>
            <value>
                <fullName>Request to Attend</fullName>
            </value>
            <value>
                <fullName>Accepted</fullName>
            </value>
            <value>
                <fullName>Attended</fullName>
            </value>
            <value>
                <fullName>Declined</fullName>
            </value>
            <value>
                <fullName>Unsuccessful</fullName>
            </value>
            <value>
                <fullName>No Show</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Medical Withdrawal</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Volunteer_Attendance__c/fields/Transport_Drop_Off_Location__c.field-meta.xml
<CustomField>
    <fullName>Transport_Drop_Off_Location__c</fullName>
    <label>Transport-Getting Home-Location</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Transport_Locations</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Volunteer_Attendance__c/fields/Transport_Drop_Off_Time__c.field-meta.xml
<CustomField>
    <fullName>Transport_Drop_Off_Time__c</fullName>
    <label>Transport-Getting Home-Time</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Volunteer_Attendance__c/fields/Transport_Pick_Up_Location__c.field-meta.xml
<CustomField>
    <fullName>Transport_Pick_Up_Location__c</fullName>
    <label>Transport-Getting to Camp-Location</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Transport_Locations</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Volunteer_Attendance__c/fields/Transport_Pick_Up_Time__c.field-meta.xml
<CustomField>
    <fullName>Transport_Pick_Up_Time__c</fullName>
    <label>Transport-Getting to Camp-Time</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Volunteer_Attendance__c/fields/Volunteer__c.field-meta.xml
<CustomField>
    <fullName>Volunteer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Volunteer</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Volunteer Attendances</relationshipLabel>
    <relationshipName>Volunteer_Attendances</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/globalValueSets/Transport_Locations.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>ACT - McDonalds (Majura Road)</fullName>
    </customValue>
    <customValue>
        <fullName>Albion Park - Train Station</fullName>
    </customValue>
    <customValue>
        <fullName>Alice Springs</fullName>
    </customValue>
    <customValue>
        <fullName>Armidale - McDonalds</fullName>
        <label>Armidale</label>
    </customValue>
    <customValue>
        <fullName>Ballina</fullName>
    </customValue>
    <customValue>
        <fullName>Ballina - McDonalds</fullName>
    </customValue>
    <customValue>
        <fullName>Bathurst McDonalds</fullName>
    </customValue>
    <customValue>
        <fullName>Bowen - Visitors Information Centre</fullName>
    </customValue>
    <customValue>
        <fullName>Brisbane Domestic Terminal</fullName>
    </customValue>
    <customValue>
        <fullName>Brisbane City- 276 Albert Street</fullName>
    </customValue>
    <customValue>
        <fullName>Brooklyn Wharf</fullName>
    </customValue>
    <customValue>
        <fullName>Bulahdelah</fullName>
    </customValue>
    <customValue>
        <fullName>Bundaberg Airport</fullName>
    </customValue>
    <customValue>
        <fullName>Burleigh Heads - Stockland</fullName>
    </customValue>
    <customValue>
        <fullName>Cairns Central Railway Station Bus Stop</fullName>
    </customValue>
    <customValue>
        <fullName>Cairns Domestic Airport</fullName>
    </customValue>
    <customValue>
        <fullName>Camp</fullName>
        <label>Camp - Drop off at / Pick up from</label>
    </customValue>
    <customValue>
        <fullName>Coffs Harbour - McDonalds Sout</fullName>
        <label>Coffs Harbour - McDonalds South</label>
    </customValue>
    <customValue>
        <fullName>Coomera Train Station</fullName>
    </customValue>
    <customValue>
        <fullName>Darwin</fullName>
    </customValue>
    <customValue>
        <fullName>Distance - I live more than 2 hrs from transport stop</fullName>
    </customValue>
    <customValue>
        <fullName>Dreamworld</fullName>
    </customValue>
    <customValue>
        <fullName>Dubbo</fullName>
    </customValue>
    <customValue>
        <fullName>Emerald Airport</fullName>
    </customValue>
    <customValue>
        <fullName>Gladstone Airport</fullName>
    </customValue>
    <customValue>
        <fullName>Glen Innes</fullName>
    </customValue>
    <customValue>
        <fullName>Goulburn South - McDonalds</fullName>
    </customValue>
    <customValue>
        <fullName>Grafton - McDonalds</fullName>
    </customValue>
    <customValue>
        <fullName>Gundagai Visitors Centre</fullName>
    </customValue>
    <customValue>
        <fullName>Heatherbrae Pies</fullName>
    </customValue>
    <masterLabel>Transport Locations</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/FamilyMemberAttendanceListController.cls
public class FamilyMemberAttendanceListController {
    
    public String aStatus{get;
        set {
            aStatus = value;
            load();
        }
    }
    public String faId{
        get;
        set {
            faId = value;
            load();
        }
    }
    
    public List<Family_Member_Attendance__c> fmas{get;set;}
	
    public FamilyMemberAttendanceListController() {
        
        load();
        
    }
    
    public void load() {
        if(String.isNotEmpty(aStatus) && String.isNotEmpty(faId)) {
            
            fmas = [SELECT Id, Attendance__c, Contact__c, Contact__r.FirstName, Contact__r.PREFERRED_FIRST_NAME__C, Contact__r.LastName,TRANSPORT_PICK_UP_TIME__C,TRANSPORT_PICK_UP_LOCATION__C, TRANSPORT_DROP_OFF_TIME__C, TRANSPORT_DROP_OFF_LOCATION__C,CURRENTLY_ON_TREATMENT__C,REQUIRES_MEDICATION_OR_VITAMINS__C,REQUIRES_DOCTORS_FORM__C,CHILD_IMMUNISATION_SCHEDULE_CURRENT__C,OTC_STANDARD__C, OTC_COMMENTS__C, COMPANION__R.VOLUNTEER__R.PREFERRED_FIRST_NAME__C FROM Family_Member_Attendance__c WHERE Family_Attendance__c = :faId AND Attendance__c = :aStatus];
            
        }
    }
    
}