force-app/main/default/objects/Contact/fields/Volunteer_Eligibility__c.field-meta.xml
<CustomField>
    <fullName>Volunteer_Eligibility__c</fullName>
    <description>Volunteer Eligibility reason describes what conditions of volunteering have not been meet by a volunteer.  CampQuality.volunteerEligibility code sets these values.  There is also VolunteerEligibilitySchedulable to update WWC fields</description>
    <label>Volunteer Eligibility Reason</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Code of Conduct Form Missing</fullName>
            </value>
            <value>
                <fullName>Currently Eligible</fullName>
            </value>
            <value>
                <fullName>Photo ID Not Sighted</fullName>
            </value>
            <value>
                <fullName>Volunteer Interview Missing</fullName>
            </value>
            <value>
                <fullName>Volunteer References Missing</fullName>
            </value>
            <value>
                <fullName>WWC Not Completed</fullName>
            </value>
            <value>
                <fullName>ACF Course Not Completed</fullName>
            </value>
            <value>
                <fullName>Dr Indemnity Insurance Policy No/Expiry Missing</fullName>
            </value>
            <value>
                <fullName>Health Practitioner Registration No &amp; Exp Date Missing</fullName>
            </value>
            <value>
                <fullName>Missing Safeguarding Children Guidelines</fullName>
            </value>
            <value>
                <fullName>WWC Expired</fullName>
            </value>
            <value>
                <fullName>Missing SC&amp;Y Policy</fullName>
            </value>
            <value>
                <fullName>Missing RSCA Policy</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/Volunteer_Status__c.field-meta.xml
<CustomField>
    <fullName>Volunteer_Status__c</fullName>
    <label>Volunteer Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Volunteer</fullName>
            </value>
            <value>
                <fullName>On Hold</fullName>
            </value>
            <value>
                <fullName>Withdrawn</fullName>
            </value>
            <value>
                <fullName>Onboarding</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/Volunteer_Types__c.field-meta.xml
<CustomField>
    <fullName>Volunteer_Types__c</fullName>
    <label>Volunteer Types</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Camp Leader</fullName>
            </value>
            <value>
                <fullName>Companion Support</fullName>
            </value>
            <value>
                <fullName>Companion/Rover</fullName>
            </value>
            <value>
                <fullName>Doctor</fullName>
            </value>
            <value>
                <fullName>Endorsed Enrolled Nurse</fullName>
            </value>
            <value>
                <fullName>Events/Fundraising</fullName>
            </value>
            <value>
                <fullName>First Aider</fullName>
            </value>
            <value>
                <fullName>Fundraising Support Group</fullName>
            </value>
            <value>
                <fullName>Leadership Committee Member</fullName>
            </value>
            <value>
                <fullName>Local Team Leader</fullName>
            </value>
            <value>
                <fullName>Office Administration</fullName>
            </value>
            <value>
                <fullName>Photographer</fullName>
            </value>
            <value>
                <fullName>Puppeteer</fullName>
            </value>
            <value>
                <fullName>Registered Nurse</fullName>
            </value>
            <value>
                <fullName>Volunteer Consultation Committee</fullName>
            </value>
            <value>
                <fullName>Corporate Volunteer</fullName>
            </value>
            <value>
                <fullName>Midwife</fullName>
            </value>
            <value>
                <fullName>Camp Support Officer</fullName>
            </value>
            <value>
                <fullName>Mentor</fullName>
            </value>
            <value>
                <fullName>Paramedic</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/recordTypes/Volunteer.recordType-meta.xml
<RecordType>
    <fullName>Volunteer</fullName>
    <active>true</active>
    <label>Volunteer</label>
</RecordType>

force-app/main/default/objects/Volunteer_Compliance__c/Volunteer_Compliance__c.object-meta.xml
<CustomObject>
    <description>Used for tracking all volunteer eligibility requirements including WWC, ACF, courses and certifications.</description>
    <label>Volunteer Compliance</label>
    <nameField>
        <displayFormat>VC-{00000}</displayFormat>
        <label>Volunteer Compliance ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Volunteer Compliance</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Volunteer_Compliance__c/fields/Criteria_Type__c.field-meta.xml
<CustomField>
    <fullName>Criteria_Type__c</fullName>
    <inlineHelpText>Matches to Volunteer Criteria on volunteers portal</inlineHelpText>
    <label>Criteria Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Online Learning</fullName>
            </value>
            <value>
                <fullName>Onboarding</fullName>
            </value>
            <value>
                <fullName>Certifications</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Volunteer_Compliance__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <inlineHelpText>Status of volunteer&apos;s compliance requirements.</inlineHelpText>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Assigned</fullName>
                <label>Not Started</label>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Active</fullName>
                <label>Completed</label>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Volunteer_Compliance__c/fields/Volunteer_Criteria__c.field-meta.xml
<CustomField>
    <fullName>Volunteer_Criteria__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Volunteer Criteria</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Volunteer_Criteria__c.Criteria_Status__c</field>
            <operation>equals</operation>
            <value>Active</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Volunteer_Criteria__c</referenceTo>
    <relationshipLabel>Volunteer Compliance</relationshipLabel>
    <relationshipName>Volunteer_Compliance</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Volunteer_Compliance__c/fields/Volunteer_Name__c.field-meta.xml
<CustomField>
    <fullName>Volunteer_Name__c</fullName>
    <label>Volunteer Name</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Volunteer Compliance</relationshipLabel>
    <relationshipName>Volunteer_Compliance</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Volunteer_Compliance__c/recordTypes/Compliance.recordType-meta.xml
<RecordType>
    <fullName>Compliance</fullName>
    <active>true</active>
    <description>For tracking volunteer compliance such as online learning, licenses, certifications and policies.</description>
    <label>Compliance</label>
</RecordType>

force-app/main/default/objects/Volunteer_Criteria__c/Volunteer_Criteria__c.object-meta.xml
<CustomObject>
    <description>Recording of all eligibility criteria for volunteers in the organisation.</description>
    <label>Volunteer Criteria</label>
    <nameField>
        <label>Volunteer Criteria Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Volunteer Criteria</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Volunteer_Criteria__c/fields/Criteria_Status__c.field-meta.xml
<CustomField>
    <fullName>Criteria_Status__c</fullName>
    <label>Criteria Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Volunteer_Criteria__c/fields/Criteria_Type__c.field-meta.xml
<CustomField>
    <fullName>Criteria_Type__c</fullName>
    <inlineHelpText>Defines where it sits on Volunteer Portal home page.</inlineHelpText>
    <label>Criteria Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Certifications</fullName>
            </value>
            <value>
                <fullName>Online Learning</fullName>
            </value>
            <value>
                <fullName>Onboarding</fullName>
            </value>
            <value>
                <fullName>License</fullName>
                <isActive>false</isActive>
                <label>License</label>
            </value>
            <value>
                <fullName>Policy</fullName>
                <isActive>false</isActive>
                <label>Policy</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Volunteer_Criteria__c/fields/Volunteer_Criteria__c.field-meta.xml
<CustomField>
    <fullName>Volunteer_Criteria__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Criteria it was replaced by for version history.</inlineHelpText>
    <label>Replaced by:</label>
    <referenceTo>Volunteer_Criteria__c</referenceTo>
    <relationshipLabel>Volunteer Criteria</relationshipLabel>
    <relationshipName>Volunteer_Criteria</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Volunteer_Eligibility__c/Volunteer_Eligibility__c.object-meta.xml
<CustomObject>
    <description>Records the different eligibility requirements for each volunteer type.</description>
    <label>Volunteer Eligibility</label>
    <nameField>
        <displayFormat>VE- {00000}</displayFormat>
        <label>Volunteer Eligibility ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Volunteer Eligibility</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Volunteer_Eligibility__c/fields/Eligibility_Active__c.field-meta.xml
<CustomField>
    <fullName>Eligibility_Active__c</fullName>
    <defaultValue>true</defaultValue>
    <inlineHelpText>Check if this eligibility criteria is still in use</inlineHelpText>
    <label>Eligibility Active</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Volunteer_Eligibility__c/fields/Volunteer_Eligibility_Criteria__c.field-meta.xml
<CustomField>
    <fullName>Volunteer_Eligibility_Criteria__c</fullName>
    <label>Volunteer Eligibility Criteria</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Volunteer_Eligibility</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Volunteer_Eligibility__c/fields/Volunteer_Role__c.field-meta.xml
<CustomField>
    <fullName>Volunteer_Role__c</fullName>
    <description>Types of roles the volunteer plays in the organisation. Defines eligibility criteria.</description>
    <label>Volunteer Role</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Volunteer_Types</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Volunteer_Eligibility__c/fields/Volunteer_Status__c.field-meta.xml
<CustomField>
    <fullName>Volunteer_Status__c</fullName>
    <inlineHelpText>Defines if eligibility applies to volunteers based on their volunteer status.</inlineHelpText>
    <label>Assigned Volunteer Status</label>
    <required>true</required>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Onboarding</fullName>
            </value>
            <value>
                <fullName>Volunteer</fullName>
            </value>
            <value>
                <fullName>Withdrawn</fullName>
            </value>
            <value>
                <fullName>On Hold</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Volunteer_Type__c/Volunteer_Type__c.object-meta.xml
<CustomObject>
    <description>Used for recording types of volunteer a volunteer can do.  I.e. Rover, Companion, Camp Leader, Medical</description>
    <label>Volunteer Type</label>
    <nameField>
        <displayFormat>VT-{0000}</displayFormat>
        <label>Volunteer Type Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Volunteers Type</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Volunteer_Type__c/fields/Volunteer__c.field-meta.xml
<CustomField>
    <fullName>Volunteer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Volunteer</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Volunteers Type</relationshipLabel>
    <relationshipName>Volunteers_Type</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Volunteer_Type__c/fields/Volunteer_Status__c.field-meta.xml
<CustomField>
    <fullName>Volunteer_Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Assigned</fullName>
            </value>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Inactive</fullName>
                <label>Former</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Volunteer_Type__c/fields/Volunteer_Type__c.field-meta.xml
<CustomField>
    <fullName>Volunteer_Type__c</fullName>
    <label>Volunteer Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Volunteer_Types</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/globalValueSets/Volunteer_Eligibility.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Meet the Vollie Team</fullName>
    </customValue>
    <customValue>
        <fullName>Our Values</fullName>
    </customValue>
    <customValue>
        <fullName>What If</fullName>
    </customValue>
    <customValue>
        <fullName>Volunteer at Camp Quality</fullName>
    </customValue>
    <customValue>
        <fullName>Safety</fullName>
    </customValue>
    <customValue>
        <fullName>Wills Journey</fullName>
    </customValue>
    <customValue>
        <fullName>Oranges</fullName>
    </customValue>
    <customValue>
        <fullName>ySafe Training</fullName>
    </customValue>
    <customValue>
        <fullName>Being a Rec Vollie</fullName>
    </customValue>
    <customValue>
        <fullName>Rec Programs 101</fullName>
    </customValue>
    <customValue>
        <fullName>Helping you on your Recreation Adventure</fullName>
    </customValue>
    <customValue>
        <fullName>Safeguarding Children and Young People Policy</fullName>
    </customValue>
    <customValue>
        <fullName>Responding to Suspected Child Abuse Policy</fullName>
    </customValue>
    <customValue>
        <fullName>Code of Conduct</fullName>
    </customValue>
    <customValue>
        <fullName>Commitment to Safeguarding Children</fullName>
    </customValue>
    <customValue>
        <fullName>Volunteer Interview</fullName>
    </customValue>
    <customValue>
        <fullName>Photo ID Sighted</fullName>
    </customValue>
    <customValue>
        <fullName>Volunteer References</fullName>
    </customValue>
    <customValue>
        <fullName>Australian Safeguarding Certificate (ACF)</fullName>
    </customValue>
    <customValue>
        <fullName>WWCC</fullName>
    </customValue>
    <customValue>
        <fullName>Induction</fullName>
    </customValue>
    <customValue>
        <fullName>Doctor Indemnity Insurance Policy</fullName>
    </customValue>
    <customValue>
        <fullName>Food Handling Training</fullName>
    </customValue>
    <customValue>
        <fullName>Health Practitioner Registration</fullName>
    </customValue>
    <customValue>
        <fullName>CPR Certificate</fullName>
    </customValue>
    <customValue>
        <fullName>First Aid Certificate</fullName>
    </customValue>
    <customValue>
        <fullName>Lifeguard Certificate</fullName>
    </customValue>
    <customValue>
        <fullName>RSA License</fullName>
    </customValue>
    <customValue>
        <fullName>Running Rec Programs</fullName>
    </customValue>
    <customValue>
        <fullName>First Aid and Medical Management</fullName>
    </customValue>
    <description>Eligibility &amp; Compliance requirements for volunteers</description>
    <masterLabel>Volunteer Eligibility</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/VolunteerEligibilityBatch.cls
/********************************************************************************************
* @Name         VolunteerEligibilityBatch
* @Author       Amit Yadav
* @Date         06/08/2024
* @Description   This Apex class is a batch process that updates the volunteer status based on 
*               compliance criteria and eligibility requirements. The batch processes the 
*               Volunteer_Type__c records, checks their associated Volunteer_Compliance__c 
*               records, and updates the Volunteer_Type__c records' status accordingly.
******************************************************************************************* 
MODIFICATION LOG
* Version          Developer          Date               Description
*
*  1.0             Amit Yadav         06/08/2024       Initial Creation                                                      
********************************************************************************************/

global class VolunteerEligibilityBatch implements Database.Batchable<SObject>, Database.Stateful {
    String query;
    String contactId;
    public VolunteerEligibilityBatch(String conId){
        this.contactId = conId;
        query = 'SELECT Id, Volunteer_Status__c, Volunteer_Type__c, Volunteer__c, ' +
            'Volunteer__r.Volunteer_Types__c, ' +
            'Volunteer__r.RecordType.DeveloperName, ' +
            'Volunteer__r.Volunteer_Status__c ' +
            'FROM Volunteer_Type__c ' +
            'WHERE Volunteer_Status__c != \'Inactive\' ' +
            'AND Volunteer__r.RecordType.DeveloperName = \'volunteer\' ' +
            'AND Volunteer__c = :contactId ' +
            'AND (Volunteer__r.Volunteer_Status__c = \'Volunteer\' ' +
            'OR Volunteer__r.Volunteer_Status__c = \'OnBoarding\')' ;
    }
    
    public Database.QueryLocator start(Database.BatchableContext BC) {
        system.debug('Inside Start Method ==>');
        return Database.getQueryLocator(query);
    }
    
    public void execute(Database.BatchableContext BC, List<Volunteer_Type__c> scope) {
        system.debug('Inside Execute Method ==>'+scope);
        // Collect necessary IDs and maps from the scope records
        Set<Id> volunteerTypeIds = new Set<Id>();
        Map<Id,string> volunteerTypeMap= new Map<Id, string>();
        Map<Id, List<Volunteer_Compliance__c>> complianceMap = new Map<Id, List<Volunteer_Compliance__c>>();
        Map<Id, string> volunteerTypesContactMap = new Map<Id, string>();
        for (Volunteer_Type__c vt : scope) {
            if(vt.Volunteer__c != NULL ){
                volunteerTypeIds.add(vt.Volunteer__c); 
                if(!volunteerTypesContactMap.containsKey(vt.Volunteer__c)){
                    volunteerTypesContactMap.put(vt.Volunteer__c, vt.Volunteer_Type__c);
                }
                
            }
        }
        system.debug('volunteerTypeIds---'+volunteerTypeIds);
        system.debug('volunteerTypesContactMap- KEYSET--'+volunteerTypesContactMap.keyset());
        system.debug('volunteerTypesContactMap- VALUES--'+volunteerTypesContactMap.values());
        // Fetch and organize Volunteer_Compliance__c records
        for (Volunteer_Compliance__c compliance : [SELECT Id, Status__c, Volunteer_Name__c, Volunteer_Name__r.RecordType.DeveloperName , Volunteer_Name__r.RecordTypeId FROM Volunteer_Compliance__c WHERE Volunteer_Name__r.RecordType.DeveloperName = 'Volunteer' AND  Volunteer_Name__c IN :volunteerTypeIds AND Volunteer_Name__r.Volunteer_Status__c IN ('Volunteer', 'Onboarding') ]) {
            if (!complianceMap.containsKey(compliance.Volunteer_Name__c)) {
                complianceMap.put(compliance.Volunteer_Name__c, new List<Volunteer_Compliance__c>());
            }
            complianceMap.get(compliance.Volunteer_Name__c).add(compliance);
        }
        system.debug('complianceMap KEYSET ==> '+complianceMap.keySet());
        system.debug('complianceMap VALUES ==> '+complianceMap.values());
        // Fetch Volunteer Eligibility Criteria
        Set<String> criteriaValue = new Set<String>();
        List<Volunteer_Eligibility__c> eligibilityCriteria = [ SELECT Id, Volunteer_Eligibility_Criteria__c, Eligibility_Active__c, Volunteer_Role__c 
                                                              FROM Volunteer_Eligibility__c  WHERE Eligibility_Active__c = true AND Volunteer_Role__c IN: volunteerTypesContactMap.values()];
        System.debug('eligibilityCriteria =LIST=> ' + eligibilityCriteria);
        System.debug('eligibilityCriteria =SIZE=> ' + eligibilityCriteria.size());
        for (Volunteer_Eligibility__c ve : eligibilityCriteria) {
            if (ve.Volunteer_Eligibility_Criteria__c != null) {
                String[] values = ve.Volunteer_Eligibility_Criteria__c.split(';');
                for (String value : values) {
                    criteriaValue.add(value.trim());
                    system.debug('value.trim() ==> '+ value.trim());
                }
            }
        }        
        system.debug('criteriaValue =SIZE=> '+ criteriaValue.size());
        system.debug('criteriaValue =LIST=> '+ criteriaValue);
        Set<Id> volunteerCriteriaId = new Set<Id>();
        // Fetch and filter Volunteer_Criteria__c records
        List<Volunteer_Criteria__c> volunteerCriteriaList = [
            SELECT Id, Volunteer_Criteria__c, Criteria_Status__c, Name FROM Volunteer_Criteria__c where Criteria_Status__c = 'Active'];
        for (Volunteer_Criteria__c vc : volunteerCriteriaList) {
            if (criteriaValue.contains(vc.Name)) {
                system.debug('vc.Name ==> '+ vc.Name );
                volunteerCriteriaId.add(vc.Id); 
            }
        }
        
        Map<Id, String> contactIdvsStatusMap = new Map<Id, String>();
        for (Volunteer_Compliance__c compliance : [SELECT Id, Status__c, Criteria_Type__c  FROM Volunteer_Compliance__c WHERE Volunteer_Name__c = :scope[0].Volunteer__c AND Volunteer_Criteria__c = :volunteerCriteriaId]) {
            
            if (compliance.Status__c == 'Active') {
                contactIdvsStatusMap.put(scope[0].Volunteer__c, 'Active');
                system.debug('line 117-----'+compliance.Status__c);
                system.debug('line 118-----'+contactIdvsStatusMap.values());
            }  if (compliance.Status__c == 'Inactive') {
                contactIdvsStatusMap.put(scope[0].Volunteer__c, 'Pending');
                system.debug('line 121-----'+compliance.Status__c);
                system.debug('line 122-----'+contactIdvsStatusMap.values());
            }
            
            if(compliance.Status__c != 'Active' && compliance.Status__c != 'Inactive'){
                contactIdvsStatusMap.put(scope[0].Volunteer__c, 'Assigned');
                system.debug('line 127-----'+compliance.Status__c);
                system.debug('line 128-----'+contactIdvsStatusMap.values());
            }
        }
        
        // Update Volunteer_Type__c records with the new status
        List<Volunteer_Type__c> updateList = new List<Volunteer_Type__c>();
        for(Volunteer_Type__c vt : scope){
            if(vt.Volunteer__c != NULL  ){
                String status = contactIdvsStatusMap.get(vt.Volunteer__c);
                if (status != null) {
                    vt.Volunteer_Status__c = status;
                    updateList.add(vt);
                    System.debug('--updateList--'+ updateList);
                }
            }
        }
        if(!updateList.isEmpty()){
            system.debug('updateList 146=='+updateList);
            UPDATE updateList;
        }
    }
    public void finish(Database.BatchableContext BC) {
        system.debug('Inside Finish Method ==>');
    } 
}