force-app/main/default/objects/Contact/fields/Volunteer_Status__c.field-meta.xml
<CustomField>
    <fullName>Volunteer_Status__c</fullName>
    <label>Volunteer Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Volunteer</fullName>
            </value>
            <value>
                <fullName>On Hold</fullName>
            </value>
            <value>
                <fullName>Withdrawn</fullName>
            </value>
            <value>
                <fullName>Onboarding</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/recordTypes/Volunteer.recordType-meta.xml
<RecordType>
    <fullName>Volunteer</fullName>
    <active>true</active>
    <label>Volunteer</label>
</RecordType>

force-app/main/default/objects/Volunteer_Compliance__c/Volunteer_Compliance__c.object-meta.xml
<CustomObject>
    <description>Used for tracking all volunteer eligibility requirements including WWC, ACF, courses and certifications.</description>
    <label>Volunteer Compliance</label>
    <nameField>
        <displayFormat>VC-{00000}</displayFormat>
        <label>Volunteer Compliance ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Volunteer Compliance</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Volunteer_Compliance__c/fields/Criteria_Type__c.field-meta.xml
<CustomField>
    <fullName>Criteria_Type__c</fullName>
    <inlineHelpText>Matches to Volunteer Criteria on volunteers portal</inlineHelpText>
    <label>Criteria Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Online Learning</fullName>
            </value>
            <value>
                <fullName>Onboarding</fullName>
            </value>
            <value>
                <fullName>Certifications</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Volunteer_Compliance__c/fields/Litmos_Course_ID__c.field-meta.xml
<CustomField>
    <fullName>Litmos_Course_ID__c</fullName>
    <inlineHelpText>The course ID in Litmos, used for the Volunteer Portal assignment.</inlineHelpText>
    <label>Litmos Course ID</label>
    <length>24</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Volunteer_Compliance__c/fields/Litmos_Course_Overdue__c.field-meta.xml
<CustomField>
    <fullName>Litmos_Course_Overdue__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>Checks against Litmos Due Date</inlineHelpText>
    <label>Litmos Course Overdue</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Volunteer_Compliance__c/fields/PercentageComplete__c.field-meta.xml
<CustomField>
    <fullName>PercentageComplete__c</fullName>
    <inlineHelpText>Pulled from Litmos</inlineHelpText>
    <label>PercentageComplete</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Volunteer_Compliance__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <inlineHelpText>Status of volunteer&apos;s compliance requirements.</inlineHelpText>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Assigned</fullName>
                <label>Not Started</label>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Active</fullName>
                <label>Completed</label>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Volunteer_Compliance__c/fields/Volunteer_Criteria__c.field-meta.xml
<CustomField>
    <fullName>Volunteer_Criteria__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Volunteer Criteria</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Volunteer_Criteria__c.Criteria_Status__c</field>
            <operation>equals</operation>
            <value>Active</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Volunteer_Criteria__c</referenceTo>
    <relationshipLabel>Volunteer Compliance</relationshipLabel>
    <relationshipName>Volunteer_Compliance</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Volunteer_Compliance__c/fields/Volunteer_Name__c.field-meta.xml
<CustomField>
    <fullName>Volunteer_Name__c</fullName>
    <label>Volunteer Name</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Volunteer Compliance</relationshipLabel>
    <relationshipName>Volunteer_Compliance</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Volunteer_Compliance__c/recordTypes/Compliance.recordType-meta.xml
<RecordType>
    <fullName>Compliance</fullName>
    <active>true</active>
    <description>For tracking volunteer compliance such as online learning, licenses, certifications and policies.</description>
    <label>Compliance</label>
</RecordType>

force-app/main/default/objects/Volunteer_Criteria__c/Volunteer_Criteria__c.object-meta.xml
<CustomObject>
    <description>Recording of all eligibility criteria for volunteers in the organisation.</description>
    <label>Volunteer Criteria</label>
    <nameField>
        <label>Volunteer Criteria Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Volunteer Criteria</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Volunteer_Criteria__c/fields/Criteria_Status__c.field-meta.xml
<CustomField>
    <fullName>Criteria_Status__c</fullName>
    <label>Criteria Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Volunteer_Criteria__c/fields/Criteria_Type__c.field-meta.xml
<CustomField>
    <fullName>Criteria_Type__c</fullName>
    <inlineHelpText>Defines where it sits on Volunteer Portal home page.</inlineHelpText>
    <label>Criteria Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Certifications</fullName>
            </value>
            <value>
                <fullName>Online Learning</fullName>
            </value>
            <value>
                <fullName>Onboarding</fullName>
            </value>
            <value>
                <fullName>License</fullName>
                <isActive>false</isActive>
                <label>License</label>
            </value>
            <value>
                <fullName>Policy</fullName>
                <isActive>false</isActive>
                <label>Policy</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Volunteer_Criteria__c/fields/Display_Order__c.field-meta.xml
<CustomField>
    <fullName>Display_Order__c</fullName>
    <inlineHelpText>Order in which it will be displayed on volunteer portal</inlineHelpText>
    <label>Display Order</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Volunteer_Criteria__c/fields/Volunteer_Criteria__c.field-meta.xml
<CustomField>
    <fullName>Volunteer_Criteria__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Criteria it was replaced by for version history.</inlineHelpText>
    <label>Replaced by:</label>
    <referenceTo>Volunteer_Criteria__c</referenceTo>
    <relationshipLabel>Volunteer Criteria</relationshipLabel>
    <relationshipName>Volunteer_Criteria</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/VolunteerComplianceProcessorTest.cls
/*********************************************************************************************************************************************
* @Name         VolunteerComplianceProcessorTest
* @Author       Amit Yadav
* @Date         30/05/2024
* @Description  The VolunteerComplianceProcessorTest class sets up test data, mocks HTTP responses, and verifies that the 
				VolunteerComplianceProcessorbatch class updates Volunteer_Compliance__c records correctly. It also tests the
                scheduling of the batch job to ensure it runs 
                at the specified time.
********************************************************************************************************************************************** 
MODIFICATION LOG
* Version          Developer          Date               Description
*
*  1.0             Amit Yadav         30/05/2024      Initial Creation                                                      
*********************************************************************************************************************************************/


/*The VolunteerComplianceProcessorTest class sets up test data, mocks HTTP responses, and verifies that the 
VolunteerComplianceProcessorbatch class updates Volunteer_Compliance__c records correctly. It also tests the
scheduling of the batch job to ensure it runs at the specified time.*/
@isTest
public class VolunteerComplianceProcessorTest {
	@testSetup
    public static void createAllData(){
        // Creating test Account records.
        Account ac = new Account();
        ac.Name = 'test';
        ac.Phone = '1234567890';
        ac.BillingStreet = 'testStreet';
        ac.BillingCity = 'Sydney';
        ac.BillingPostalCode = '778855';
        ac.BillingState = 'test';     
        insert ac;
        
        // Creating test Contact records.
        contact con = new contact();
        con.LastName = 'testq con';
        con.Email = 'test@22user.com';
        con.AccountId = ac.Id;
        con.Volunteer_Status__c = 'Volunteer';
        insert con;        
                                   
        // Creating test Volunteer Criteria record
        Volunteer_Criteria__c volCri = new Volunteer_Criteria__c();        
        volCri.Criteria_Type__c = 'Online Learning';
        volCri.Criteria_Status__c = 'Active';
        volCri.Display_Order__c = 12;
        volCri.Name = 'Code of Conduct';
        insert volCri;
        
        // Creating test Volunteer Compliance records
        List<Volunteer_Compliance__c> volComplianceList = new List<Volunteer_Compliance__c>();
        for(Integer i = 0; i < 5; i++) {
            Volunteer_Compliance__c volComp = new Volunteer_Compliance__c();
            volComp.Volunteer_Criteria__c = volCri.Id;
            volComp.Status__c = 'Assigned'; // or 'In Progress'
            volComp.Litmos_Course_ID__c = '1207831'; // Change to actual Litmos Course ID
            volComp.Volunteer_Name__c = con.Id;
            volComplianceList.add(volComp);
        }
        insert volComplianceList;
    }
    
    @istest
    public static void testVolunteerComplianceProcessor(){
        
		List<Volunteer_Compliance__c> volList = [SELECT Id,Status__c, PercentageComplete__c, Litmos_Course_Overdue__c, Date_Completed__c FROM Volunteer_Compliance__c WHERE Criteria_Type__c = 'Online Learning'];
        Test.setMock(HttpCalloutMock.class, new MockHttpResponseGenerator());
		 Test.startTest();
        VolunteerComplianceProcessor volCom = new VolunteerComplianceProcessor();
        Id jobid= Database.executeBatch(volCom);  
        Test.stopTest();        
        // Add assertions to check the results of the batch execution
        List<Volunteer_Compliance__c> listVol = [SELECT Id, Status__c, PercentageComplete__c, Litmos_Course_Overdue__c, Date_Completed__c FROM Volunteer_Compliance__c WHERE Criteria_Type__c = 'Online Learning'];
		Assert.isNotNull(listVol, 'String should be null'); // Succeeds
    }
    
    @isTest
    public static void testScheduledBatchExecution() {
        Test.setMock(HttpCalloutMock.class, new MockHttpResponseGenerator());
        
        Test.startTest();
        // Schedule the batch class
        String jobId = System.schedule('Test Compliance Processor', '0 0 7 * * ? *', new VolunteerComplianceProcessor());
        Test.stopTest();      
        //  add assertions here to check that the job was scheduled correctly
        List<CronTrigger> cronTriggers = [SELECT Id, CronExpression, TimesTriggered, NextFireTime FROM CronTrigger WHERE Id = :jobId];
        System.assertEquals(1, cronTriggers.size(), 'The batch job should be scheduled.');
        System.assertNotEquals(null, cronTriggers[0].NextFireTime, 'The batch job should have a next fire time.');
    }
   
     // Mock HTTP Response Generator
    private class MockHttpResponseGenerator implements HttpCalloutMock {
        public HTTPResponse respond(HTTPRequest req) {
            // Create a fake HTTP response
            HttpResponse res = new HttpResponse();
            res.setHeader('Content-Type', 'application/json');
            res.setStatusCode(200);
            res.setBody('[{"OriginalId": "1207831", "Complete": true, "PercentageComplete": 100, "Overdue": false, "DateCompleted": "/Date(1651190400000+0000)/"}]');
            return res;
        }
    }   
}