force-app/main/default/objects/Contact/fields/Volunteer_Eligibility__c.field-meta.xml
<CustomField>
    <fullName>Volunteer_Eligibility__c</fullName>
    <description>Volunteer Eligibility reason describes what conditions of volunteering have not been meet by a volunteer.  CampQuality.volunteerEligibility code sets these values.  There is also VolunteerEligibilitySchedulable to update WWC fields</description>
    <label>Volunteer Eligibility Reason</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Code of Conduct Form Missing</fullName>
            </value>
            <value>
                <fullName>Currently Eligible</fullName>
            </value>
            <value>
                <fullName>Photo ID Not Sighted</fullName>
            </value>
            <value>
                <fullName>Volunteer Interview Missing</fullName>
            </value>
            <value>
                <fullName>Volunteer References Missing</fullName>
            </value>
            <value>
                <fullName>WWC Not Completed</fullName>
            </value>
            <value>
                <fullName>ACF Course Not Completed</fullName>
            </value>
            <value>
                <fullName>Dr Indemnity Insurance Policy No/Expiry Missing</fullName>
            </value>
            <value>
                <fullName>Health Practitioner Registration No &amp; Exp Date Missing</fullName>
            </value>
            <value>
                <fullName>Missing Safeguarding Children Guidelines</fullName>
            </value>
            <value>
                <fullName>WWC Expired</fullName>
            </value>
            <value>
                <fullName>Missing SC&amp;Y Policy</fullName>
            </value>
            <value>
                <fullName>Missing RSCA Policy</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Volunteer_Eligibility__c/Volunteer_Eligibility__c.object-meta.xml
<CustomObject>
    <description>Records the different eligibility requirements for each volunteer type.</description>
    <label>Volunteer Eligibility</label>
    <nameField>
        <displayFormat>VE- {00000}</displayFormat>
        <label>Volunteer Eligibility ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Volunteer Eligibility</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Volunteer_Skill__c/Volunteer_Skill__c.object-meta.xml
<CustomObject>
    <description>Used for recording volunteer skills like CPR etc.</description>
    <label>Volunteer Skill</label>
    <nameField>
        <displayFormat>VS - {00000}</displayFormat>
        <label>Volunteer Skill ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Volunteer Skills</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Volunteer_Skill__c/fields/Expires__c.field-meta.xml
<CustomField>
    <fullName>Expires__c</fullName>
    <label>Expires</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Volunteer_Skill__c/fields/Skill_Description__c.field-meta.xml
<CustomField>
    <fullName>Skill_Description__c</fullName>
    <label>Skill Description</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Anaphalaxis Training</fullName>
            </value>
            <value>
                <fullName>Blue Card (QLD) Registration No &amp; Exp Date</fullName>
            </value>
            <value>
                <fullName>Dr Indemnity Insurance Policy No/Expiry</fullName>
            </value>
            <value>
                <fullName>First Aid</fullName>
            </value>
            <value>
                <fullName>CPR</fullName>
            </value>
            <value>
                <fullName>Food Handling Training</fullName>
            </value>
            <value>
                <fullName>Health Practitioner Registration No &amp; Exp Date</fullName>
            </value>
            <value>
                <fullName>Lifeguard</fullName>
            </value>
            <value>
                <fullName>Ochre Card (NT) Registration Number &amp; Exp Date</fullName>
            </value>
            <value>
                <fullName>Police Check (SA) Releasable Record &amp; Exp Date</fullName>
            </value>
            <value>
                <fullName>RSA</fullName>
            </value>
            <value>
                <fullName>WWCC/Police Check</fullName>
            </value>
            <value>
                <fullName>WWCC (NSW) Validation No &amp; Exp Date</fullName>
            </value>
            <value>
                <fullName>WWCC (TAS/WA/VIC/ACT) Card No &amp; Exp Date</fullName>
            </value>
            <value>
                <fullName>WWC Stat Dec (JPNo, NextCheck)</fullName>
            </value>
            <value>
                <fullName>Driver&apos;s License</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Volunteer_Skill__c/fields/Volunteer__c.field-meta.xml
<CustomField>
    <fullName>Volunteer__c</fullName>
    <label>Volunteer</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Volunteer Skills</relationshipLabel>
    <relationshipName>Volunteer_Skills</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/VolunteerEligibilitySchedulable.cls
global class VolunteerEligibilitySchedulable implements Schedulable {
	global void execute(SchedulableContext sc) {
		
		Set<Id> cSet = new Set<Id>();

		//for(Volunteer_Skill__c vs : [SELECT Id, Volunteer__c FROM Volunteer_Skill__c WHERE Volunteer__r.Volunteer_Eligibility__c = 'Currently Eligible' AND (Skill_Description__c LIKE '%WWC%' OR Skill_Description__c = 'Blue Card (QLD) Registration No & Exp Date') AND Expires__c <= :Date.today()]) {
		for(Volunteer_Skill__c vs : [SELECT Id, Volunteer__c FROM Volunteer_Skill__c WHERE Volunteer__r.Volunteer_Eligibility__c = 'Currently Eligible' AND  Expires__c <= :Date.today()]) {
			cSet.add(vs.Volunteer__c);
		}

		campQuality.volunteerEligibility(cSet);

	}
}