force-app/main/default/objects/Special_Needs__c/Special_Needs__c.object-meta.xml
<CustomObject>
    <label>Dietary &amp; Special Needs</label>
    <nameField>
        <displayFormat>SN - {0000}</displayFormat>
        <label>Special Needs Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Dietary &amp; Special Needs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Special_Needs__c/fields/Comments__c.field-meta.xml
<CustomField>
    <fullName>Comments__c</fullName>
    <label>Comments</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Special_Needs__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipName>Special_Needs</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Special_Needs__c/fields/Long_Description__c.field-meta.xml
<CustomField>
    <fullName>Long_Description__c</fullName>
    <label>Long Description</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>ADD</fullName>
            </value>
            <value>
                <fullName>ADHD</fullName>
            </value>
            <value>
                <fullName>Allergic - All Nuts</fullName>
            </value>
            <value>
                <fullName>Allergic - Buckwheat</fullName>
            </value>
            <value>
                <fullName>Allergic - Eggs</fullName>
            </value>
            <value>
                <fullName>Allergic - Fish</fullName>
            </value>
            <value>
                <fullName>Allergic - Garlic</fullName>
            </value>
            <value>
                <fullName>Allergic - Kiwi Fruit</fullName>
            </value>
            <value>
                <fullName>Allergic - Mushrooms</fullName>
            </value>
            <value>
                <fullName>Allergic - Oranges</fullName>
            </value>
            <value>
                <fullName>Allergic - Other</fullName>
            </value>
            <value>
                <fullName>Allergic - Parmesan Cheese</fullName>
            </value>
            <value>
                <fullName>Allergic - Peanuts</fullName>
            </value>
            <value>
                <fullName>Allergic - Pork</fullName>
            </value>
            <value>
                <fullName>Allergic - Prawns</fullName>
            </value>
            <value>
                <fullName>Allergic - Seafood</fullName>
            </value>
            <value>
                <fullName>Allergic - Sesame</fullName>
            </value>
            <value>
                <fullName>Allergic - Shellfish</fullName>
            </value>
            <value>
                <fullName>Allergic - Tomatoes</fullName>
            </value>
            <value>
                <fullName>Allergic - Yeast</fullName>
            </value>
            <value>
                <fullName>Allergic to dust mites</fullName>
            </value>
            <value>
                <fullName>Allergy - Angel Cream</fullName>
            </value>
            <value>
                <fullName>Allergy - Antibiotic Erythromycin</fullName>
            </value>
            <value>
                <fullName>Allergy - Asparaginase</fullName>
            </value>
            <value>
                <fullName>Allergy - Asprin</fullName>
            </value>
            <value>
                <fullName>Allergy - Bactrim</fullName>
            </value>
            <value>
                <fullName>Allergy - Band Aids</fullName>
            </value>
            <value>
                <fullName>Allergy - Bee Stings</fullName>
            </value>
            <value>
                <fullName>Allergy - Bleomycin</fullName>
            </value>
            <value>
                <fullName>Allergy - Brietal</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/SpecialNeedsListController.cls
public class SpecialNeedsListController {
public String cId{
        get;
        set {
            cId = value;
            load();
        }
    }
    
    public List<Special_Needs__C> sneeds{get;set;}
	
    public SpecialNeedsListController() {
        
        load();
        
    }
    
    public void load() {
        if(String.isNotEmpty(cId)) {
            
            sneeds = [select Long_Description__c, Comments__c, Date__c
                      FROM Special_Needs__C where  Contact__c   = :cId];
            
        }
    }
}